<div class="main-col-inner">
<div id="messages"></div>
<div class="content-header" style="visibility: visible;">
    <h3 class="icon-head head-adminhtml-followprice">Magik Fees Help & FAQ</h3>    
</div>
<div class="clear:both"></div>
	<div>
	<h3>How It Works?</h3>
	Magik Fees extension makes it possible to add any number extra fees to different individual product,entire category or in shipping. <br/>
	Admin can have following options - <br/>
	<b>1. All Extra Fees -</b> Under this admin can add / edit N number of fees for product,category,order or shipping. This includes fee name , fee type ( fixed / percent), amount , apply to (product,category,shipping), mandatory / optional , & status. <br/><br/>

	<b>2. System > Configuration > Magikfees Configuration Tab -</b> Admin can manage the fee custom title from here which can be  displayed in all places where the fee is get applied. Admin can set this specific to store views. 	
	</div><br/>
	Magik Extra fee will allow to add fees either fixed or percentage of the product price to individual product, entire category or shipping. <br/>

	<b>For Product & category Fees -</b><br/>
	If extra fee type is mandatory, the extension will automatically add the fee to sub-total in the cart. This will also show disabled selected checkbox as confirmation to the customers. In other words, if product is purchased which has a mandatory fee associated with it then this extra fee is automatically added to the total and customers have to pay (product cost + extra fee).
All optional fees associated with either product or entire category will generate an additional row showing checkboxes, fee, and fee name on cart page. Customers can anytime select any extra fee checkbox to confirm they are willing to pay extra for these specific offerings. After selection page is refreshed and extra fee is added to the sub total. Similarly, customers can also de-select the checkbox and the extra fee will be subtracted from the cart total.<br/><br/>
	  
	<b>For Order Fee -</b><br/>
	In this type the extra fees will be applied on entire order. If order type fee is of mandatory type, the extra fee will be add directly to the order total. In case the order fee is optional then this extension will generate checkboxes to select optional fee for the order just below the cart on shopping cart page . Once selected the amount (%fee or fixed) is calculate and on click of "Add to Total" button it is added to the total.<br/><br/>  

	<b>For Shipping Fee -</b><br/>
	In this type the extra fees will be listed on checkout page under “Shipping Method”. If shipping fee is of mandatory type, the extra fee will be add the shipping amount directly. In case the shipping fee is optional then this extension will generate checkboxes to select optional fee. Once selected the amount (%fee or fixed) is calculate and added to the total.<br/><br/>
	<br/>
	<div>
	<h3>Support</h3>
	For any queries <a href="http://www.magikcommerce.com/contact-us.html" target="_blank" style="cursor:pointer">Contact Us</a> OR
	Discuss it on our <a href="http://forum.magikcommerce.com/" target="_blank" style="cursor:pointer">Forum</a>	 
	</div>
	
</div>
