<div class="col-main">
  <div class="category-description std">
    <h1>Shop HMR&reg; Categories</h1>
    <p>HMR foods are delicious, filling, and versatile­—what more could you ask for in a weight-loss food?</p>
    <p>HMR Shakes can be blended with fruit, extracts, or any sugar-free flavorings to create hundreds of different recipes. Delicious calorie and portion-controlled HMR Entrees are a convenient and nutritious “fast food” option for weight management that require no refrigeration or freezing, making them a great choice for work or home.</p><p>In addition to Shakes and Entrees, HMR offers a variety of other delicious food options you can enjoy as part of your weight loss or weight maintenance plan.</p><p><strong>This time, losing weight can be different.</strong></p>
  </div>
  <div class="category-products">
    <ul class="products-grid">
      <li class="item calc-price-box" style="height: 327px;">
        <div class="regular"><a class="product-image" title="" href="/hmr-at-home-program"> <img src="/media/categories/at-home-cat.jpg" alt="" /> </a> <a class="product-name" title="" href="/hmr-at-home-program">HMR&reg; At Home Program</a>
          <p class="shop-now-sub">Automatic food delivery, personalized support, &amp; extra savings!</p>
        </div>
      </li>
      <li class="item calc-price-box" style="height: 327px;">
        <div class="regular"><a class="product-image" title="" href="/hmr-diet-accessories"> <img src="/media/categories/accessories-cat.jpg" alt="" /> </a> <a class="product-name" title="" href="/hmr-diet-accessories">HMR&reg; Diet Accessories</a></div>
      </li>
      <li class="item calc-price-box" style="height: 327px;">
        <div class="regular"><a class="product-image" title="" href="/hmr-diet-entrees"> <img src="/media/categories/entrees-cat.jpg" alt="" /> </a> <a class="product-name" title="" href="/hmr-diet-entrees">HMR&reg; Diet Entrees</a></div>
      </li>
      <li class="item calc-price-box" style="height: 327px;">
        <div class="regular"><a class="product-image" title="" href="/hmr-shakes"> <img src="/media/categories/shakes-cat.jpg" alt="" /> </a> <a class="product-name" title="" href="/hmr-shakes">HMR&reg; Diet Shakes/Puddings</a></div>
      </li>
      <li class="item calc-price-box" style="height: 327px;">
        <div class="regular"><a class="product-image" title="" href="/hmr-multigrain-cereal"> <img src="/media/categories/cereal-cat.jpg" alt="" /> </a> <a class="product-name" title="" href="/hmr-multigrain-cereal">HMR&reg; Diet Multigrain Cereal</a></div>
      </li>
      <li class="item calc-price-box" style="height: 327px;">
        <div class="regular"><a class="product-image" title="" href="/hmr-diet-benefit-bars"> <img src="/media/categories/bars-cat.jpg" alt="" /> </a> <a class="product-name" title="" href="/hmr-diet-benefit-bars">HMR&reg; Diet BeneFit Bars</a></div>
      </li>
      <li class="item calc-price-box" style="height: 327px;">
        <div class="regular"><a class="product-image" title="" href="/hmr-500-chicken-soup"> <img src="/media/categories/soup-cat.jpg" alt="" /> </a> <a class="product-name" title="" href="/hmr-500-chicken-soup">HMR&reg; Diet 500 Chicken Soup</a></div>
      </li>
      <li class="item calc-price-box" style="height: 327px;">
        <div class="regular"><a class="product-image" title="" href="/hmr-healthy-shakes-diet-kit"> <img src="/media/categories/hs-shakes-diet-kit-cat.jpg" alt="" /> </a> <a class="product-name" title="" href="/hmr-healthy-shakes-diet-kit">HMR&reg; Healthy Shakes&trade; Diet Kit</a></div>
</li>
      <li class="item calc-price-box" style="height: 327px;">
        <div class="regular"><a class="product-image" title="" href="/kit-hs-variety"> <img src="/media/categories/variety-cat.jpg" alt="" /> </a> <a class="product-name" title="" href="/kit-hs-variety">HMR&reg; Healthy Solutions&reg; Variety Pack</a></div>
      </li>
      <li class="item calc-price-box" style="height: 327px;">
        <div class="regular"><a class="product-image" title="" href="/lorann-extract-flavorings"> <img src="/media/categories/flavors-cat.jpg" alt="" /> </a> <a class="product-name" title="" href="/lorann-extract-flavorings">LorAnn Extract Flavorings</a></div>
      </li>
    </ul>
  </div>
</div>
<?php
// Uncomment below and comment the above for cyber monday changes!
?>
<!--<div class="col-main">
  <div class="category-description std">
    <h1>Shop HMR&reg; Categories</h1>
  </div>
  <div class="category-products">
<div class="cyber-categories-wrapper">
<h2 class="cyber-category-header">Cyber <span style="text-decoration: underline;">WEEK</span> Savings!</h2>
<p>Don't wait until January to make a change in your health for the better!  Now is the time to plan your attack in tackling that healthy new you (Especially if doing it now means big savings too!). It's not too late to find your Cyber Monday Savings! We have extended our sale through the end of the week, so register using the form to the left (or below if you're on your mobile device!) today and watch your email inbox for special Cyber <strike>Monday</strike> Week saving opportunities!</p>
<ul class="products-grid">
      <li class="item calc-price-box cybermonday" style="height: 327px;">
        <div class="regular"><a class="product-image" title="" href="/shop/hmr-diet-shakes-puddings"> <img src="/media/categories/shakes-cat.jpg" alt="" /> </a> <a class="product-name cybermonday_link" title="" href="/shop/hmr-diet-shakes-puddings">HMR&reg; Diet Shakes/Puddings</a></div>
      </li>
      <li class="item calc-price-box cybermonday" style="height: 327px;">
        <div class="regular"><a class="product-image" title="" href="/shop/hmr-diet-multigrain-cereal/hmr-multigrain-cereal"> <img src="/media/categories/cereal-cat.jpg" alt="" /> </a> <a class="product-name cybermonday_link" title="" href="/shop/hmr-diet-multigrain-cereal/hmr-multigrain-cereal">HMR&reg; Diet Multigrain Cereal</a></div>
      </li>
      <li class="item calc-price-box cybermonday" style="height: 327px;">
        <div class="regular"><a class="product-image" title="" href="/shop/hmr-diet-500-chicken-soup/hmr-500-chicken-soup"> <img src="/media/categories/soup-cat.jpg" alt="" /> </a> <a class="product-name cybermonday_link" title="" href="/shop/hmr-diet-500-chicken-soup/hmr-500-chicken-soup">HMR&reg; Diet 500 Chicken Soup</a></div>
      </li>
      </ul>
      </div>
      <ul class="products-grid">
      <li class="item calc-price-box" style="height: 327px;">
        <div class="regular"><a class="product-image" title="" href="/shop/hmr-at-home"> <img src="/media/categories/at-home-cat.jpg" alt="" /> </a> <a class="product-name" title="" href="/about/hmr-at-home">HMR&reg; At Home Program</a>
          <p class="shop-now-sub">Automatic food delivery, personalized support, &amp; extra savings!</p>
        </div>
      </li>
      <li class="item calc-price-box" style="height: 327px;">
        <div class="regular"><a class="product-image" title="" href="/shop/hmr-diet-accessories"> <img src="/media/categories/accessories-cat.jpg" alt="" /> </a> <a class="product-name" title="" href="/shop/hmr-diet-accessories">HMR&reg; Diet Accessories</a></div>
      </li>
      <li class="item calc-price-box" style="height: 327px;">
        <div class="regular"><a class="product-image" title="" href="/shop/hmr-diet-entrees"> <img src="/media/categories/entrees-cat.jpg" alt="" /> </a> <a class="product-name" title="" href="/shop/hmr-diet-entrees">HMR&reg; Diet Entrees</a></div>
      </li>
      <li class="item calc-price-box" style="height: 327px;">
        <div class="regular"><a class="product-image" title="" href="/shop/hmr-diet-benefit-bars"> <img src="/media/categories/bars-cat.jpg" alt="" /> </a> <a class="product-name" title="" href="/shop/hmr-diet-benefit-bars">HMR&reg; Diet BeneFit Bars</a></div>
      </li>
      <li class="item calc-price-box" style="height: 327px;">
        <div class="regular"><a class="product-image" title="" href="/shop/hmr-healthy-shakes-diet-kit"> <img src="/media/categories/hs-shakes-diet-kit-cat.jpg" alt="" /> </a> <a class="product-name" title="" href="/shop/hmr-healthy-shakes-diet-kit">HMR&reg; Healthy Shakes&trade; Diet Kit</a></div>
      </li>
      <li class="item calc-price-box" style="height: 327px;">
        <div class="regular"><a class="product-image" title="" href="/shop/hmr-healthy-solutions-quick-start-diet-kit"> <img src="/media/categories/hs-diet-kit-cat.jpg" alt="" /> </a> <a class="product-name" title="" href="/shop/hmr-healthy-solutions-quick-start-diet-kit">HMR&reg; Healthy Solutions&reg; Quick Start&trade; Diet Kit</a></div>
      </li>
      <li class="item calc-price-box" style="height: 327px;">
        <div class="regular"><a class="product-image" title="" href="/shop/hmr-healthy-solutions-variety-pack"> <img src="/media/categories/variety-cat.jpg" alt="" /> </a> <a class="product-name" title="" href="/shop/hmr-healthy-solutions-variety-pack">HMR&reg; Healthy Solutions&reg; Variety Pack</a></div>
      </li>
      <li class="item calc-price-box" style="height: 327px;">
        <div class="regular"><a class="product-image" title="" href="/shop/lorann-extract-flavorings"> <img src="/media/categories/flavors-cat.jpg" alt="" /> </a> <a class="product-name" title="" href="/shop/lorann-extract-flavorings">LorAnn Extract Flavorings</a></div>
      </li>
    </ul>
  </div>
</div>-->
