  <div class="about-us-title">
    <h1>Shipping Disclaimer</h1>
  </div>
<p>All orders are processed Monday - Friday, during normal business hours, excluding holidays. <a href="http://www.hackleyhealthmanagement.com">www.hackleyhealthmanagement.com</a> will not guarantee the delivery time of any order. www.hackleyhealthmanagement.com cannot be responsible for shipping delays caused by shipping companies which are beyond our reasonable control. Shipping costs will not automatically be refunded for delayed deliveries.</p>
<p><strong>Expedited orders placed after 3:00pm EST will ship out the following business day.</strong></p>
<p>Orders that will be shipped to Alaska, Hawaii, and all U.S. Territories will need to contact Hackley Health Management at <strong>800.521.9054</strong> for a shipping estimates before placing your order.</p>
<p>Note: we cannot ship to PO boxes or military bases.</p>

