<style>
#join-link li, .at-home-cta ul#join-link li {
	background: none repeat scroll 0 0 #860037;
	margin-right: 15px;
}
#at-home-menu li {
	float: left;
	margin: 0 0 0 7px;
	position: relative;
}
#at-home-menu li.first {
}
.at-home-nav ul {
	float: left;
}
.at-home-nav ul li a, .at-home-cta ul#join-link li a {
	display: block;
	line-height: 40px;
	font-weight: bold;
}
.at-home-nav ul li a span {
	padding: 10px 41px;
}
.at-home-cta ul#join-link li a span {
	padding: 20px 61px;
}
.at-home-nav ul#join-link li a, .at-home-cta ul#join-link li a {
	text-transform: uppercase;
	color: #fff;
}
.at-home-nav {
	position: absolute;
}
.at-home-nav ul#join-link li:hover a, .at-home-nav ul#at-home-menu li:hover a, .at-home-cta ul#join-link li:hover a {
	text-decoration: none;
	color: #860038;
}
.at-home-nav ul#join-link li:hover, .at-home-nav ul#at-home-menu li:hover, .at-home-nav ul#at-home-menu li a.tablink.active {
	background: url("/skin/frontend/default/shopper/images/topnav_bkg_on1.gif") repeat-x scroll left top transparent !important;
	height: 55px !important;
	max-height: 55px !important;
	min-height: 55px !important;
	color: #860038;
}
.at-home-nav ul#at-home-menu li {
	background: url("/skin/frontend/default/shopper/images/topnav_bkg.gif") repeat-x scroll left top transparent;
}
.at-home-nav ul#at-home-menu li a {
	color: #373230;
}
.at-home-wrapper {
	background: url("/skin/frontend/default/shopper/images/at-home-tabs-bg.png") no-repeat scroll left 50px transparent;
}
.tab-wrapper {
	font-size: 140%;
	clear: both;
	overflow: hidden;
	padding-top: 5px;
	position: relative;
	top: 90px;
}
.at-home-nav ul > li > a, .at-home-cta ul > li > a {
	transition: background 600ms ease-in-out 0s;
}
.content-right {
	float: right;
	position: relative;
	width: 500px;
	z-index: 1;
}
.content-right div > h2, .at-home-cta h2 {
	color: #860038;
	margin-bottom: 15px;
	text-transform: none;
}
.content-right div > ul > li {
	background: url("/skin/frontend/default/shopper/images/at-home-list-bullet.png") no-repeat scroll 5px 10px transparent;
	line-height: 150%;
	padding-left: 15px;
	padding-bottom: 10px;
}
.content-right div img {
	margin-top: 10px;
}
.at-home-tab-image {
	width: 100%;
	text-align: center;
	position: absolute;
}
.at-home-cta {
	clear: both;
	z-index: 3;
	width: 430px;
	margin-top: 40px;
}
.at-home-cta #joinLink > a {
	font-size: 70% !important;
}
.at-home-cta-image {
	float: left;
}
.at-home-cta ul#join-link li a {
	font-size: 18px !important;
	line-height: 62px;
}
.at-home-cta ul#join-link li:hover {
	background: url("/skin/frontend/default/shopper/images/topnav_bkg_on1.gif") repeat-x scroll left top / contain transparent !important;
	height: 109px !important;
	max-height: 109px !important;
}
.at-home-cta-button {
	float: left;
	max-height: 80px;
	overflow: hidden;
	width: 250px;
}
</style>
<?php

/****************************************************** ORIGINAL BLOCK OF CODE 

	//Set block flag
	$kitInCartFlag = false;

	//Get data.
	$kitIds = Array(130, 131, 132, 136); //Kit product IDs
	$cartItems = Mage::helper('checkout/cart')->getCart()->getItems(); //Products in cart

	//For each product in cart...
	foreach($cartItems as $item){
		if(in_array($item->getProduct()->getId(), $kitIds)){ //If this cart item's product id is a kit, and the product being added to the cart is a kit...
			$kitInCartFlag = true; //Mark flag to prevent adding this kit to cart!
		}
	}

	if($kitInCartFlag){
		$joinLink = '<ul id="join-link"><li id="joinLink"><a href="/checkout/cart/"><span>Checkout!*</span></a></li></ul>';
	}else{
		$joinLink = '<ul id="join-link"><li id="joinLink"><a href="/shop/hmr-at-home/hmr-programs" onclick="kitAlert();"><span>Join Now!</span></a></li></ul>';
	}
***************************************************** ORIGINAL BLOCK OF CODE *****/

//Set block flag
$kitInCartFlag = false;

//Get data.
$kitIds = Array(130, 131, 132, 136); //Kit product IDs
$cartItems = Mage::helper('checkout/cart')->getCart()->getItems(); //Products in cart

//For each product in cart...
foreach($cartItems as $item){
	if(in_array($item->getProduct()->getId(), $kitIds)){ //If this cart item's product id is a kit, and the product being added to the cart is a kit...
		$kitInCartFlag = true; //Mark flag to prevent adding this kit to cart!
	}
}

if($kitInCartFlag){
	$joinLink = '<ul id="join-link"><li id="joinLink"><a href="/checkout/cart/"><span>Checkout!*</span></a></li></ul>';
}else{
	$joinLink = '<ul id="join-link"><li id="joinLink"><a href="/shop/hmr-at-home/hmr-programs" onclick="kitAlert();"><span>Join Now!</span></a></li></ul>';
}

/* if ($_SERVER['REMOTE_ADDR'] != '200.127.196.22') {
	$joinLink = '<ul id="join-link"><li id="joinLink"><a href="#"><span>800.521.9054</span></a></li></ul>';
} */

?>
<script type="text/javascript">
	function kitAlert(){
		return true;// alert('If you would like to participate in multiple HMR at Home programs, you must complete the checkout process with your first program and then begin a new order for any additional programs you would like to register.');
	}
</script>
<?php if($kitInCartFlag):?>
<p style="background-color: #f2dede; border-color: #ebccd1; color: #a94442; border: 1px solid; padding: 15px;">*Please note that in order to add an additional HMR At Home Program to your account, your must first complete the checkout with the HMR At Home Program that is in your cart. Please either click on the checkout button below or <a href="/checkout/cart/">click here</a> to continue.</p>
<?php endif; ?>
<div class="at-home-wrapper">
  <div class="at-home-nav"> <?php echo $joinLink; ?>
    <ul id="at-home-menu">
      <li id="link1" class="at-home-list first at-home-active"><a href="#" class="tablink active"><span>HMR at Home Benefits</span></a></li>
      <li id="link2" class="at-home-list"><a href="#" class="tablink"><span>Savings</span></a></li>
      <li id="link3" class="at-home-list"><a href="#" class="tablink"><span>Your Daily Diet Plan</span></a></li>
      <li id="link4" class="at-home-list last"><a href="#" class="tablink"><span>Free Support</span></a></li>
    </ul>
    <div id="resposive-at-home-menu-wrapper"><span>Current Page: </span>
      <select id="resposive-at-home-menu" name="responsive-at-home-menu">
        <option value="page1" class="tablink active">HMR&reg; at Home Benefits</option>
        <option value="page2" class="tablink">Savings</option>
        <option value="page3" class="tablink">Your Daily Diet Plan</option>
        <option value="page4" class="tablink">Free Support</option>
      </select>
    </div>
    <div class="clear"></div>
  </div>
  <div class="tab-wrapper">
    <div class="content-left-athome-sale"></div>
    <div class="content-right">
      <div id="page1" class="tab-content">
        <h2>WHAT IS HMR AT HOME?</h2>
        <p>The HMR at Home Program makes losing weight easy and convenient with automatic food delivery, personalized support, and extra savings – so you can save more money and lose more weight.</p>
        <h2>HMR at Home members receive:</h2>
        <ul>
          <li>Great savings on HMR Healthy Solutions Quick Start<sup>&trade;</sup> Diet Kits</li>
          <li>Automated Kit delivery for uninterrupted weight loss</li>
          <li>Detailed, step-by-step dieting “how-to” materials with your first Kit order</li>
          <li>Free Quick Start<sup>&trade;</sup> CD to help you lose the most weight in the first few weeks</li>
          <li>Free customer service calls to answer any questions at any point during your diet</li>
        </ul>
        <div class="at-home-tab-image"> <img src="/media/wysiwyg/at-home-tab-kit.png" alt="" /></div>
      </div>
      <div id="page2" class="tab-content" style="display: none;">
        <h2>HMR AT HOME SAVINGS</h2>
        <p>When you join HMR at Home, you will receive automatic discounts and free shipping on each scheduled Kit order. With no initiation or subscription fees, becoming a part of HMR at Home helps you lose more weight while saving more money.</p>
        <h2>HMR at Home savings:</h2>
        <ul>
          <li>Free to join - there are no initial fees or charges</li>
          <li>Save 10% on your first Kit order</li>
          <li>Save another 10% on every Kit re-order</li>
          <li>Save 10% on any extra HMR<sup>&reg;</sup> foods purchased at the time of your order</li>
          <li>Receive free shipping on all Kit orders</li>
          <li>Change or cancel your order at any time</li>
        </ul>
        <div class="at-home-tab-image"> <img src="/media/wysiwyg/at-home-tab-calc.png" alt="" /> </div>
      </div>
      <div id="page3" class="tab-content" style="display: none;">
        <h2>YOUR DAILY DIET PLAN</h2>
        <p>If you want to reach your goal weight, it’s important to always feel full so you’re not tempted to go off your diet. Each HMR Healthy Solutions Quick Start<sup>&trade;</sup> Diet Kit includes enough low-calorie and filling HMR® food to keep you satisfied, so you keep losing weight week after week.</p>
        <h2>The Healthy Solutions<sup>&reg;</sup> Diet Plan:</h2>
        <ul>
          <li>Each day you will enjoy at least 3 creamy HMR Shakes and 2 flavorful Entrees - just add fruits and vegetables to complete your meal.</li>
          <li>HMR foods are proven to work - published studies show that dieters using meal replacements lose 2½-3 times more weight than those on traditional diets.</li>
          <li>Lose even more weight by following the simple, proven weight-loss strategies outlined in the Diet Kit materials and Quick Start<sup>&trade;</sup> CD included in your first Kit order.</li>
        </ul>
        <div class="at-home-tab-image"> <img src="/media/wysiwyg/at-home-tab-tape.png" alt="" /></div>
      </div>
      <div id="page4" class="tab-content" style="display: none;">
        <h2>FREE SUPPORT</h2>
        <p>We want you to lose the most weight possible! As a member of the HMR at Home Program, you’re invited to call one of our friendly and supportive Weight-Loss Consultants at any point during your diet. They all use HMR® foods to manage their weight, and they have lots of tips and recipe ideas they can share with you to keep you on track to reach your goal.</p>
        <h2>FREE SUPPORT</h2>
        <ul>
          <li>FREE Quick Start® CD with proven strategies to help you lose the most weight:
            <ul>
              <li>Hear how to maximize your weight loss while staying full and satisfied. </li>
              <li>Learn the best way to prepare HMR Shakes and Entrees for delicious variety.</li>
              <li>Avoid common dieting mistakes.</li>
            </ul>
          </li>
          <li>Free ongoing support: Call any time you have a question about HMR foods or the diet plan. We’re dedicated to your success!</li>
        </ul>
        <div class="at-home-tab-image"> <img src="/media/wysiwyg/at-home-tab-phone.png" alt="" /></div>
      </div>
    </div>
    <div class="clear clearfix"></div>
    <div class="at-home-cta">
      <h2>JOIN NOW &amp; LOSE THE MOST WEIGHT!</h2>
      <p>Join HMR at Home and get 10% off your Health Solutions Quick Start<sup>&trade;</sup> Diet Kits. Plus, receive FREE shipping on every HMR at Home order. Cancel any time.</p>
      <div class="at-home-cta-button"> <?php echo $joinLink; ?> </div>
      <div class="at-home-cta-image"> <img src="/media/wysiwyg/hmr-truck-at-home.jpg" alt="" /> </div>
      <div class="clear"></div>
      <?php if($kitInCartFlag):?>
      <p style="background-color: #f2dede; border-color: #ebccd1; color: #a94442; border: 1px solid; padding: 15px;">*Please note that in order to add an additional HMR At Home Program to your account, your must first complete the checkout with the HMR At Home Program that is in your cart. Please either click on the checkout button above or <a href="/checkout/cart/">click here</a> to continue.</p>
      <?php endif; ?>
    </div>
    <div class="clear clearfix"></div>
  </div>
</div>
<script type="text/javascript">
	jQuery('#at-home-menu a.tablink').click(function(e){
		e.preventDefault();
		hideContentDivs();
		var tmp_div = jQuery(this).parent().index();
		jQuery('.tab-wrapper .tab-content').eq(tmp_div).show();
		jQuery('ul.at-home-menu li a.tablink').removeClass('active');
		jQuery(this).addClass('active');
	});

	function hideContentDivs(){
		jQuery('.tab-wrapper .tab-content').each(function(){
			jQuery(this).hide();
			jQuery('#at-home-menu a.tablink').removeClass('active');
		});
	}

	jQuery('#resposive-at-home-menu').change(function(){
		jQuery('.tab-content').hide();
		jQuery('#' + jQuery(this).val()).show();
	});
</script> 
