<?php
/**
 * KAbel_BundlePlus
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to a BSD 3-Clause License
 * that is bundled with this package in the file LICENSE_BSD_NU.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www1.unl.edu/wdn/wiki/Software_License
 *
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2012 Regents of the University of Nebraska (http://www.nebraska.edu/)
 * @license     http://www1.unl.edu/wdn/wiki/Software_License  BSD 3-Clause License
 */
?>

<?php /* @var $this Mage_Bundle_Block_Catalog_Product_View_Type_Bundle_Option_Checkbox */ ?>
<?php $_option = $this->getOption(); 
		?>
<?php $_selections = $_option->getSelections() ?>
<dt><label<?php if ($_option->getRequired()) echo ' class="required"' ?>><?php 

if(substr($_option->getTitle(),2,6) == 'Choose'){
	$newTitle = explode(" ", $_option->getTitle());
	echo "<span class='kits-step'>".$newTitle[0]."</span>".$newTitle[1]." ".$newTitle[2]." ".substr($newTitle[3],0,3)."<sup>".substr($newTitle[3],3)."</sup> ".$newTitle[4];
} else {
	echo $_option->getTitle();
}

 ?><?php if ($_option->getRequired()) echo '<em>*</em>' ?></label></dt>
<dd<?php if ($_option->decoratedIsLast){?> class="last"<?php }?>>
    <div class="input-box">
    <?php if (count($_selections) == 1 && $_option->getRequired()): ?>
        <?php echo $this->getSelectionQtyTitlePrice($_selections[0]) ?>
        <input type="hidden" name="bundle_option[<?php echo $_option->getId() ?>]" value="<?php echo $_selections[0]->getSelectionId() ?>"/>
    <?php else:?>
        <ul class="options-list">
        <?php foreach($_selections as $_selection): ?>
        <?php /* @var $_selection Mage_Bundle_Model_Selection */
		/*echo $this->getSelectionTitlePrice($_selection);
		echo "right here ".$_selection->getSelectionQty();*/
		$thisTitle = explode(' ', $_option->getTitle());
		$thisFlavorArray = explode(' ', $this->getSelectionTitlePrice($_selection));
		
		for($h = 0; $h < count($thisFlavorArray); $h++){
			if($thisFlavorArray[$h] == '-'){
				$thisFlavor = $thisFlavorArray[$h+1];
			}
		}
		/*echo "<pre>";
		print_r($_option); 
		echo "</pre>";*/

		?>
        
            <li>
                <?php $_isSelected = $this->_isSelected($_selection); ?>
                <input 
                	onclick="bundle.limitSelection(this, '<?php echo $thisTitle[2]; ?>')" 
                    class="change-container-classname checkbox bundle-option-<?php echo $_option->getId() ?> <?php if ($_option->getRequired()) echo 'validate-one-required-by-name' ?>" 
                    id="bundle-option-<?php echo $thisFlavorArray[1]; ?>-<?php echo $thisFlavor; ?>" 
                    type="checkbox" 
                    name="bundle_option[<?php echo $_option->getId() ?>][]"<?php if($_selection->getSelectionQty() > 0) echo ' checked="checked"' ?><?php if (!$_selection->isSaleable()) echo ' disabled="disabled"' ?> 
                    value="<?php echo $_selection->getSelectionId() ?>"/>
                 
                <?php if ($_selection->getSelectionCanChangeQty()): ?>
                <span class="qty-holder"><label for="bundle-option-<?php echo $_option->getId() ?>-<?php echo $_selection->getSelectionId() ?>-qty-input"><?php echo $this->__('Qty:') ?>&nbsp;</label>
                    <input 
                    	onblur="bundle.limitQuantity(this.id, this.value, '<?php echo $thisTitle[2]; ?>')" 
                        class="input-text qty<?php if (!$_isSelected) echo ' qty-disabled' ?>" 
                        maxlength="1" 
                        id="bundle-option-<?php echo $thisFlavorArray[1]; ?>-<?php echo $thisFlavor; ?>-qty-input" 
                        type="text" 
                        name="bundle_option_qty[<?php echo $_option->getId() ?>][<?php echo $_selection->getSelectionId() ?>]"
                        value="<?php echo number_format($_selection->getSelectionQty(), 0) ?>" />
                    <input 
                    	id="bundle-option-<?php echo $thisFlavorArray[1]; ?>-<?php echo $thisFlavor; ?>-qty-input-default" 
                        type="hidden" 
                        value="<?php echo number_format($_selection->getSelectionQty(), 0) ?>" />
                        </span>
                <?php else: ?>
                <span class="qty-holder"><label><?php echo $this->__('Qty:') ?>&nbsp;</label><?php echo $_selection->getSelectionQty()*1 ?></span>
                <?php endif; ?>
                <span class="label"><label for="bundle-option-<?php echo $_option->getId() ?>-<?php echo $_selection->getSelectionId() ?>"><?php echo $this->getSelectionTitlePrice($_selection) ?></label></span>

                <?php if($_option->getRequired()): ?>
                    <?php echo $this->setValidationContainer('bundle-option-'.$_option->getId().'-'.$_selection->getSelectionId(), 'bundle-option-'.$_option->getId().'-container') ?>
                <?php endif; ?>
            </li>
        <?php endforeach; ?>
        </ul>
        <div id="bundle-option-<?php echo $_option->getId() ?>-container"></div>
    <?php endif; ?>
    </div>
</dd>
<script src="http://code.jquery.com/ui/1.9.2/jquery-ui.js"></script>
<script type="text/javascript">
//<![CDATA[
    jQuery(function() {
        jQuery("#product-options-wrapper").accordion({
			header: 'dt',
			animated: 'easeInSine',
            collapsible: true,
			autoHeight: false
        });
    });
	//]]>
</script>
