<img style="padding: 0px 0px 10px 10px; max-width: 209px!important; height: auto;" src="/media/wysiwyg/alisa.jpg" alt="Alisa Ruby-Torres" align="right" />
<h1>Now, the World is My Oyster!</h1>
<p>&ldquo;Before I found HMR I was a size 24. I was an obese child and have always had weight problems. I tried more diets than I can count, but I&rsquo;d lose the weight and gain it back. I felt like I was twice my age and I was exhausted. I am a teacher, so typically I&rsquo;d go to the cafeteria and have whatever unhealthy food was coming out of the kitchen that day. I went to my physician and I was told that if I kept up with my unhealthy habits I would be a candidate for a heart attack within the next 5-10 years. She told me that unless I did something about my weight, she would have to refer me to a bariatric surgeon.</p>
<p>&ldquo;If I had kept going at the rate I was, I would have physically done some irreversible things to my body. My weight was not creeping up&hellip; it was galloping!</p>
<p>&ldquo;With HMR I have changed my entire life. I have new friends, I go to the gym, everything has changed. HMR eliminated my decision-making. I didn&rsquo;t have a history of good decision-making surrounding food, so I was glad to have HMR make them for me! I still eat a tremendous amount&mdash;I&rsquo;ve just learned to change what I&rsquo;m eating. I can see myself in the HMR classes and using meal replacements ten years from now. I need the support and the skills they offer.</p>
<p>&ldquo;I&rsquo;m a realist. I know obesity and I&rsquo;m going to need the accountability that HMR give me for a long time. Now that I have lost the weight I am a size 6. I bought an entire wardrobe. I couldn&rsquo;t stop shopping&mdash;I was so thrilled not to go into the plus-size section of the department stores. I&rsquo;m living my life as a healthy person now, and nothing is more important than that.</p>
<p>&ldquo;Now, the world is my oyster!&rdquo;</p>
<div style="width: 33%; float: left;">
  <p>Very Low-Calorie Diet <br />
    44 years old <br />
    Pounds lost: 112 <br />
    Lost her weight in: 2002</p>
</div>
<div style="width: 33%; float: left;">
  <p>Physical Activity (calories burned per week) <br />
    Before HMR: 0 <br />
    After HMR: 3,500</p>
</div>
<div style="width: 33%; float: left;">
  <p>Triglycerides (normal: under 150) <br />
    Before HMR: 208 <br />
    After HMR: 64</p>
</div>
<p style="clear: both;"><strong>Alisa Ruby-Torres</strong></p>
<div class="success-notice">
  <h3>Share your story today!</h3>
  <p>We'd like to hear, in your own words, how the HMR Program has affected you - your health, your life, your family, and your friends. By sharing your experiences, you may help another person to lose weight and get healthier.</p>
  <ul>
    <li>Why did you search for a weight loss program?</li>
    <li>What was the hardest part of your struggle?</li>
    <li>What advice would you give to others?</li>
  </ul>
  <p>Be sure to include your mailing address, fax and phone number. We may be contacting you and asking you to share your story with the world!</p>
  <p>Please email <a href="mailto:success@hackleyhealthmanagement.com">success@hackleyhealthmanagement.com</a> with your story to be considered.</p>
</div>
<p style="color: #777; font-size: 10px; margin-top: 10px;">Results not typical.<br />
  HMR makes no claims that these results are representative of all patients in the HMR program.</p>
