<img style="padding: 0px 0px 10px 10px; max-width: 240px!important; height: auto; float: right;" src="/media/wysiwyg/GingerAfterWow.jpg" alt="Ginger Gonyon" />
<h1>"This weight loss has been about my health, and I am meeting my goal."</h1>
<p>In August of 2014, Ginger Gonyon made her health a priority, after her annual physical went less than ideal. "My lab results were not favorable; high cholesterol, elevated blood sugar, and high blood pressure," Gonyon said.  She was not on medications at the time and she had no desire to start. Together, Ginger and her physician decided a weight loss program would be a good option to see if her medical conditions would improve.</p><p>
Ginger made a phone call and the following week she attended a free information session for the Mercy Health Weight Management program in Muskegon, MI </p><p>
"I had my doubts if this program would work for me because I tried other diets with little results," Gonyon recalled.</p><p>
Through phase one of the program, Gonyon lost 55 pounds in only seven months. She explained what led her to great success.</p><p>
"I attend a weekly class where I am taught how to use HMR meal replacement products, add at least five fruits and vegetables, and importance of daily water intake. I feel the weekly classes are a large part of my weight loss success," Gonyon explained.</p><p>
Gonyon is now enrolled in Mercy's phase two program where she continues to be successful. </p><p>
"These classes keep me accountable for my weekly progress and encourage me to set higher goals to maintain a healthy environment and lifestyle. During class we come together and can share our struggles as well as accomplishments, after all we are there to support each other," Gonyon said.</p><p>
Gonyon recently visited her primary care physician for updated lab work and was well pleased with the result.</p><p>
"The results were better than I expected. My cholesterol, triglycerides, and blood sugar were all at normal levels. My blood pressure has been normal for three months. The knee and back pain I suffered in the past is seldom noticed anymore," she reflected.</p><p>
She now looks forward to her future. "I have become more active and plan to do more things with my family, she said. "I am signing up with my family for a 5k run this summer and I know I am healthy enough to do it".</p>
<p><strong>Ginger Gonyon</strong></p>
<div class="success-notice">
  <h3>Share your story today!</h3>
  <p>We'd like to hear, in your own words, how the HMR Program has affected you - your health, your life, your family, and your friends. By sharing your experiences, you may help another person to lose weight and get healthier.</p>
  <ul>
    <li>Why did you search for a weight loss program?</li>
    <li>What was the hardest part of your struggle?</li>
    <li>What advice would you give to others?</li>
  </ul>
  <p>Be sure to include your mailing address, fax and phone number. We may be contacting you and asking you to share your story with the world!</p>
  <p>Please email <a href="mailto:success@hackleyhealthmanagement.com">success@hackleyhealthmanagement.com</a> with your story to be considered.</p>
</div>
<p style="color: #777; font-size: 10px; margin-top: 10px;">Results not typical.<br />
  HMR makes no claims that these results are representative of all patients in the HMR program.</p>
