<img style="padding: 0px 0px 10px 10px; max-width: 240px!important; height: auto;" src="/media/wysiwyg/JimAfterWow.jpg" alt="Jim Oros" align="right" />
<h1>Lost Over 200lbs. with HHM since January 2006!</h1>
<p>If the tri-county area held its own "Biggest Loser" contest, Very Low Calorie Diet faithful Jim Oros would surely be in the running for the top prize.</p>
<p>Oros has dedicated his diet to mostly liquid for 11 months and is half the man for it -- literally. Oros, of Grand Haven, weighed in at 411 pounds when he started the same rapid weight-loss diet late last January.</p>
<p>He hit 210 in November and has no plans of quitting. Maintenance now has become the focus for both.</p>
<p>Hackley Health Management offers the national Health Management Resources program locally and sells HMR shakes, entrees and BeneFit bars. The HMR program offers a variety of options for people battling the bulge.</p>
<p>Personalized plans (that range from medically supervised to home do-it-yourself diet kits) can help a person lose 10 to 200 pounds, said Carrie Kelly, Hackley Health Management's program coordinator.</p>
<p>Whereas many weight-loss plans require participants to count calories and points or pick and choose food, the HMR Very Low Calorie Diet, also called Decision Free, makes it easy.</p>
<p>"They don't have to think about their choices," Kelly said. "There's no guesswork involved. The accountability also helps. When people don't attend their classes, you can tell. The weight comes back."</p>
<p>The program does have rules, including a strict attendance policy, exercise requirements and a restrictive diet monitored by blood tests. However, both Rieger and Oros found them helpful.</p>
<p>"They have to be ready. Jim is a perfect example. The mind has to be in sync with the body," she said.</p>
<p>Oros gives the credit to God and even wrote a small story about his weight-loss journey for his church's newsletter. Obese for most of his life, Oros tried different diets and exercise without much luck. His weight climbed to 460 at different times.</p>
<p>He went for an annual physical last January and his doctor suggested Hackley Health's plan. Oros agreed to try it, and after insurance approval for the medical portion, signed on -- with an impressive 19-pound weight loss in the first week.</p>
<p>The single 44-year-old became a dedicated shake drinker and, even now that he can have food, still drinks about five a day.</p>
<p>"I like doing that because it's easy to follow," he said. "One thing that's different with this program is that if you need to have six or seven shakes a day, then you can have them. I had a hard time grasping that at first. This is the only diet I've been on where they say more is better."</p>
<p>Oros learned to be creative with flavoring extracts and sugar- and fat-free gelatin and pudding mixes combined with the vanilla and chocolate flavored powder. He has experimented with blending and baking the mixture in different ways.</p>
<p>His favorite concoctions are brownies and cheesecake and chicken chips made with HMR's chicken soup variety. His latest recipe is a tasty mousse with frozen fruit.</p>
<p>"I really didn't miss anything because I was in the right frame of mind for losing weight," he said.</p>
<p><strong>Jim Oros</strong></p>
<div class="success-notice">
  <h3>Share your story today!</h3>
  <p>We'd like to hear, in your own words, how the HMR Program has affected you - your health, your life, your family, and your friends. By sharing your experiences, you may help another person to lose weight and get healthier.</p>
  <ul>
    <li>Why did you search for a weight loss program?</li>
    <li>What was the hardest part of your struggle?</li>
    <li>What advice would you give to others?</li>
  </ul>
  <p>Be sure to include your mailing address, fax and phone number. We may be contacting you and asking you to share your story with the world!</p>
  <p>Please email <a href="mailto:success@hackleyhealthmanagement.com">success@hackleyhealthmanagement.com</a> with your story to be considered.</p>
</div>
<p style="color: #777; font-size: 10px; margin-top: 10px;">Results not typical.<br />
  HMR makes no claims that these results are representative of all patients in the HMR program.</p>
