<img style="padding: 0px 0px 10px 10px; width: 240px!important; height: auto;" src="/media/wysiwyg/chittenden.jpg" alt="Kirby Chittenden" align="right" />
<h1>Teacher loses 67 pounds</h1>
<p>After his weight ballooned to 238 pounds in 2008, Kirby Chittenden knew it was time to change his lifestyle.</p>
<p>Not only was Chittenden gaining weight, his health was suffering.</p>
<p>Fast-forward to 2011 and you'll find a different Kirby Chittenden, 57. He is now a svelte 171 pounds and exercising on a regular basis.</p>
<p>In November 2008, Chittenden &mdash; a Spring Lake resident and fifth-grade teacher at Lake Hills Elementary School &mdash; enrolled in the Hackley Health (under the umbrella of Mercy Health Partners) Management program and was soon on the road to getting his life back in order.</p>
<p>"I was pretty much a 'couch potato,'" recalled the 5-foot-9-inch Chittenden. "I wasn't able to handle stress and comfort food was very relieving. I'd eat any kind of dessert."</p>
<p>Gaining weight has been something that Chittenden said he's struggled with ever since his college days. Doughnuts and other sweets were common fare.</p>
<p>He had heard through friends that Mercy Health Partners offered the Hackley Health Management program in Muskegon.</p>
<p>"I found a brochure on the program in my doctor's office and asked him about it. He spoke highly of the program," Chittenden said.</p>
<p>Chittenden was soon onboard and enrolled in the program.</p>
<p>"My family wasn't too happy with me at first, because I entered the program just before the holidays," he said.</p>
<p>On the program, Chittenden would have to eliminate holiday treats from his diet.</p>
<p>"A few people thought I was crazy for approaching a weight-loss program at such a time," he said. "However, I figured there never was going to be a convenient time &mdash; and that if I could do it during the holidays, I might actually head into the New Year with a chance."</p>
<p>The Hackley program promotes significant weight loss under medical supervision, using only nutritionally complete weight-loss shakes and entrees instead of grocery store food, according to Donna Marie Phillips, a health educator for the program.</p>
<p>"I didn't have a choice on what I could eat for several months," Chittenden recalled.</p>
<p>But Chittenden no longer felt the urge to feast on junk food, and the weight began to come off. He lost most of his goal of losing 60 pounds in the first five months of the program.</p>
<p>An added bonus for Chittenden is that he was able to eliminate taking medications for hypertension and cholesterol, as well as anti-inflammatory medications.</p>
<p>Phillips said Chittenden is now enrolled in Hackley's maintenance program &mdash; in which he attends weekly classes, receives support and learns additional strategies for weight management.</p>
<p>Chittenden not only has lost more than 60 pounds, he has become dedicated to exercise. Several friends encouraged him to take up running and even participate in a road race.</p>
<p>"At first, even running a half-mile was difficult, but I ventured into the challenge anyway," he recalled.</p>
<p>This past summer, Chittenden completed his first duathlon (running and bicycling), and he also participated in the One Day Ride Across America in August.</p>
<p>Chittenden's lifestyle change has also helped him in the classroom. He said he now has the stamina required to work alongside 10-year-old students, and to model good nutrition and fitness.</p>
<p>Chittenden works out on a regular basis, setting a goal for himself to burn off 2,000 calories on a weekly basis.</p>
<p>The changes in Chittenden's lifestyle are for good, he said.</p>
<p>"I don't want to go back to the dark side," he said. "All this can only be described as a reinvention of life for me. To sustain good health requires good habits, and I am making excellent progress. Life is truly good."</p>
<p>Chittenden jokingly said he has become the "poster child" for the Hackley Health Management program.</p>
<p><strong>Kirby Chittenden</strong></p>
<div class="success-notice">
  <h3>Share your story today!</h3>
  <p>We'd like to hear, in your own words, how the HMR Program has affected you - your health, your life, your family, and your friends. By sharing your experiences, you may help another person to lose weight and get healthier.</p>
  <ul>
    <li>Why did you search for a weight loss program?</li>
    <li>What was the hardest part of your struggle?</li>
    <li>What advice would you give to others?</li>
  </ul>
  <p>Be sure to include your mailing address, fax and phone number. We may be contacting you and asking you to share your story with the world!</p>
  <p>Please email <a href="mailto:success@hackleyhealthmanagement.com">success@hackleyhealthmanagement.com</a> with your story to be considered.</p>
</div>
<p style="color: #777; font-size: 10px; margin-top: 10px;">Results not typical.<br />
  HMR makes no claims that these results are representative of all patients in the HMR program.</p>
