<img style="padding: 0px 0px 10px 10px; max-width: 235px!important; height: auto;" src="/media/wysiwyg/kris_07_lg.jpg" alt="Kris Rieger" align="right" />
<h1>Dropped more than 130 pounds with the strict diet and daily exercise.</h1>
<p>It was suppose to be a fun day at Ohio's Cedar Point Amusement Park. Rural Fruitport resident Kris Rieger braved a long wait with her brother to ride the Raptor roller coaster and they settled into the seat.</p>
<p>Then it came. Rieger's life-changing wake-up call. She couldn't buckle the seatbelt and had to exit the ride.</p>
<p>A month later, the Monday after Thanksgiving 2005, Rieger committed to Hackley Health Management's Very Low Calorie Diet program. She has since dropped more than 130 pounds with the strict diet and daily exercise.</p>
<p>If the tri-county area held its own "Biggest Loser" contest, Rieger and fellow Very Low Calorie Diet faithful Jim Oros would surely be in the running for the top prize.</p>
<p>"Those two were extraordinary in the fact they followed the program100 percent," said Becki Krueger, a Hackley Health Management health educator. "They made physical activity a priority and problem-solved attendance, activities and events. They were two very coachable people."</p>
<p>Hackley Health Management offers the national Health Management Resources program locally and sells HMR shakes, entrees and BeneFit bars. The HMR program offers a variety of options for people battling the bulge.</p>
<p>Personalized plans (that range from medically supervised to home do-it-yourself diet kits) can help a person lose 10 to 200 pounds, said Carrie Kelly, Hackley Health Management's program coordinator.</p>
<p>Whereas many weight-loss plans require participants to count calories and points or pick and choose food, the HMR Very Low Calorie Diet, also called Decision Free, makes it easy.</p>
<p>"They don't have to think about their choices," Kelly said. "There's no guesswork involved. The accountability also helps. When people don't attend their classes, you can tell. The weight comes back."</p>
<p>The program does have rules, including a strict attendance policy, exercise requirements and a restrictive diet monitored by blood tests. However, both Rieger and Oros found them helpful.</p>
<p>"For me, it's key having that accountability," Rieger said. "And it's not like you can't ever have it (regular food) again."</p>
<p>Ultimately, sustained weight-loss success comes down to commitment and attitude, Krueger said.</p>
<p>"They have to be ready. Kris is a perfect example. The mind has to be in sync with the body," she said.</p>
<p><strong>Kris Rieger</strong></p>
<div class="success-notice">
  <h3>Share your story today!</h3>
  <p>We'd like to hear, in your own words, how the HMR Program has affected you - your health, your life, your family, and your friends. By sharing your experiences, you may help another person to lose weight and get healthier.</p>
  <ul>
    <li>Why did you search for a weight loss program?</li>
    <li>What was the hardest part of your struggle?</li>
    <li>What advice would you give to others?</li>
  </ul>
  <p>Be sure to include your mailing address, fax and phone number. We may be contacting you and asking you to share your story with the world!</p>
  <p>Please email <a href="mailto:success@hackleyhealthmanagement.com">success@hackleyhealthmanagement.com</a> with your story to be considered.</p>
</div>
<p style="color: #777; font-size: 10px; margin-top: 10px;">Results not typical.<br />
  HMR makes no claims that these results are representative of all patients in the HMR program.</p>
