<img style="padding: 0px 0px 10px 10px; width: 175px!important; height: auto;" src="/media/wysiwyg/lois-after-wow.jpg" alt="Lois Wilterdink" align="right" />
<h1>My Story - Lois Wilterdink, Muskegon, MI</h1>
<p>I've had many medical problems in my life that run in my family. My main problem has been fibromyalgia and osteoarthritis. When you have these, the more you weigh, the more you hurt. Pain was my life and it was almost unbearable when I weighed 210 pounds. Now, at 135 pounds, it is almost unnoticeable!</p>
<p>The Hackley Health Management program works if you work the program. It was better than the weight loss surgery I might have had or heart attack I could have had. My mom had passed away with many major health problems. I promised her before she passed that I would do something about my weight and I did. &ldquo;Here&rsquo;s to you, mom!&rdquo;</p>
<p>I started the weight-loss program at Hackley Health Management because my doctor said it would ease some of my pain to lose some weight. Not only has it done that, but it has also lowered my cholesterol and I been able to cut back on most of my medications. I have maintained the 75-pound weight loss with the help and support of Hackley Health Management&rsquo;s Maintenance program. I like the fact that they don&rsquo;t just leave you hanging after you lose weight. They teach you how to keep it off and support you with any challenges you encounter along the way.</p>
<p>After I lost the weight, my husband said to me, "I love being able to put my arms around you!" I love that! WOW! What a compliment.</p>
<p><strong>Lois Wilterdink</strong><br />
  Muskegon, MI</p>
<div class="success-notice">
  <h3>Share your story today!</h3>
  <p>We'd like to hear, in your own words, how the HMR Program has affected you - your health, your life, your family, and your friends. By sharing your experiences, you may help another person to lose weight and get healthier.</p>
  <ul>
    <li>Why did you search for a weight loss program?</li>
    <li>What was the hardest part of your struggle?</li>
    <li>What advice would you give to others?</li>
  </ul>
  <p>Be sure to include your mailing address, fax and phone number. We may be contacting you and asking you to share your story with the world!</p>
  <p>Please email <a href="mailto:success@hackleyhealthmanagement.com">success@hackleyhealthmanagement.com</a> with your story to be considered.</p>
</div>
<p style="color: #777; font-size: 10px; margin-top: 10px;">Results not typical.<br />
  HMR makes no claims that these results are representative of all patients in the HMR program.</p>