<img style="padding: 0px 0px 10px 10px; max-width: 147px!important; height: auto;" src="/media/wysiwyg/peggy-success.jpg" alt="Peggy Silvis" align="right" />
<h1>I lost 90 pounds in six months and I feel GREAT!</h1>
<p>I have tried many weight loss programs before, and I really feel wonderful about Hackley Health Management and its staff! Their program has excellent food (entrees, bars, and shakes), weekly meetings (a must!) and weekly weigh-ins (to keep you honest).</p>
<p>The health educators taught me the importance of eating 5 or more fruits and vegetables a day, and how keeping records helps you stay on track. It has been especially difficult seeing I am around food all day long, working as a Chef at the Hearthstone Restaurant in Muskegon.</p>
<p>Hackley Health Management helped me lose 90 pounds in six months and I feel GREAT! More importantly, their maintenance program has helped me keep my weight off since October of 2001.</p>
<p>I recommend this program to you if you are serious and ready to lose weight.</p>
<p><strong>Peggy Silvis</strong><br />
  Muskegon, MI</p>
<div class="success-notice">
  <h3>Share your story today!</h3>
  <p>We'd like to hear, in your own words, how the HMR Program has affected you - your health, your life, your family, and your friends. By sharing your experiences, you may help another person to lose weight and get healthier.</p>
  <ul>
    <li>Why did you search for a weight loss program?</li>
    <li>What was the hardest part of your struggle?</li>
    <li>What advice would you give to others?</li>
  </ul>
  <p>Be sure to include your mailing address, fax and phone number. We may be contacting you and asking you to share your story with the world!</p>
  <p>Please email <a href="mailto:success@hackleyhealthmanagement.com">success@hackleyhealthmanagement.com</a> with your story to be considered.</p>
</div>
<p style="color: #777; font-size: 10px; margin-top: 10px;">Results not typical.<br />
  HMR makes no claims that these results are representative of all patients in the HMR program.</p>
