<img style="padding: 0px 0px 10px 10px; max-width: 211px!important; height: auto;" src="/media/wysiwyg/rick-success.jpg" alt="Rick Genter" align="right" />
<h1>I Even Walked the Boston Marathon This Year!</h1>
<p>&ldquo;I&rsquo;ve been overweight my whole life. Before HMR, I used to go out for lunch all the time and the only vegetables I ate came on a pizza. My waist was 58 inches and I was at high risk for a heart attack and for diabetes. I had tried other diets before and would have initial success, but could never maintain the weight loss.</p>
<p>&ldquo;Today, I feel like a 17 year old. I feel much more alive, can move more easily and have more energy. I weigh less now, at 43, than I did when I was 13! In my mind, HMR is the only program out there that doesn&rsquo;t just focus on results, but helps people change their lifestyles. It is a scientifically-based program proven to work. I am the proof! Other weight-loss group meetings seemed more like a social hour to me. Not HMR - it is about learning and problem solving. If I have a problem &ndash; it gets addressed not only by the health educator, but also by the group of adults in the class. I haven't missed one HMR meeting in two years.</p>
<p>&ldquo;I&rsquo;ve tried other low-calorie frozen entrees&copy; and I really prefer HMR&rsquo;s menu options. I see myself using meal replacements forever. They are nutritious and make good, hearty meals. They work because they control the portions and calories for me. I&rsquo;ve seen the progress every week, practically everyday. I&rsquo;ve replaced my wardrobe four times now and am able to shop for clothes in &ldquo;normal&rdquo; stores.</p>
<p>&ldquo;I recently had a physical and my doctor was amazed. He said that I now have the cardiovascular system of a top athlete. I&rsquo;m feeling so much healthier &ndash; I even walked the Boston Marathon this year!&rdquo;</p>
<div style="width: 33%; float: left;">
  <p>Very Low-Calorie Diet <br />
    43 years old <br />
    Pounds lost: 187 <br />
    Lost her weight in: 2002</p>
</div>
<div style="width: 33%; float: left;">
  <p>BMI (normal under 25)<br />
    Before HMR: 50 <br />
    After HMR: 34</p>
</div>
<div style="width: 33%; float: left;">
  <p>Triglycerides (normal: under 150)<br />
    Before HMR: 220<br />
    After HMR: 20</p>
</div>
<p style="clear: both;"><strong>Rick Genter</strong></p>
<div class="success-notice">
  <h3>Share your story today!</h3>
  <p>We'd like to hear, in your own words, how the HMR Program has affected you - your health, your life, your family, and your friends. By sharing your experiences, you may help another person to lose weight and get healthier.</p>
  <ul>
    <li>Why did you search for a weight loss program?</li>
    <li>What was the hardest part of your struggle?</li>
    <li>What advice would you give to others?</li>
  </ul>
  <p>Be sure to include your mailing address, fax and phone number. We may be contacting you and asking you to share your story with the world!</p>
  <p>Please email <a href="mailto:success@hackleyhealthmanagement.com">success@hackleyhealthmanagement.com</a> with your story to be considered.</p>
</div>
<p style="color: #777; font-size: 10px; margin-top: 10px;">Results not typical.<br />
  HMR makes no claims that these results are representative of all patients in the HMR program.</p>
