<img style="padding: 0px 0px 10px 10px; max-width: 210px!important; height: auto;" src="/media/wysiwyg/ruth-success.jpg" alt="Ruth Davidson" align="right" />
<h1>I'm a &lsquo;Life-r&rsquo;</h1>
<p>I had not done a lot of diets before HMR. I just wasn't interested and I kept gaining weight. At my highest weight I was 226 pounds. To maintain that, you eat a lot of junk. You're not eating foods that make you feel good physically. If I went on vacation or a day trip it was all about eating. Before, I would always try to cover up my body, even in the summer. I was hot all the time.</p>
<p>When I started with HMR, I lost the weight really quickly. I lost 10 pounds the first week. Within 2-3 weeks, people were noticing. All of a sudden, I could shop in "regular" stores because I'm now a "standard size".</p>
<p>Today I can run upstairs, wear shorts comfortably, and not worry about id I get the middle seat on an airplane, because now I can fit comfortably. People often do double takes. I ran into an old friend and she still had a hard time believing it was really me.</p>
<p>I am into fast and convenient and HMR meal replacements fit my lifestyle. The HMR program is all about calorie-control. I have completely adapted my strategies based on what I have learned. HMR gave me the knowledge, willpower, and support to do it.</p>
<p>"I'm a 'life-r'"</p>
<div style="width: 33%; float: left;">
  <p>Very Low-Calorie Diet <br />
    46 years old <br />
    Pounds lost: 80 <br />
    Lost her weight in: 2000</p>
</div>
<div style="width: 33%; float: left;">
  <p>Physical Activity (calories burned per week) <br />
    Before HMR: 1,350 <br />
    After HMR: 3,500</p>
</div>
<div style="width: 33%; float: left;">
  <p>Fruit and Vegetables Intake (per week) <br />
    Before HMR: 0-7<br />
    After HMR: 35 or more</p>
</div>
<p style="clear: both;"><strong>Ruth Davidson </strong></p>
<div class="success-notice">
  <h3>Share your story today!</h3>
  <p>We'd like to hear, in your own words, how the HMR Program has affected you - your health, your life, your family, and your friends. By sharing your experiences, you may help another person to lose weight and get healthier.</p>
  <ul>
    <li>Why did you search for a weight loss program?</li>
    <li>What was the hardest part of your struggle?</li>
    <li>What advice would you give to others?</li>
  </ul>
  <p>Be sure to include your mailing address, fax and phone number. We may be contacting you and asking you to share your story with the world!</p>
  <p>Please email <a href="mailto:success@hackleyhealthmanagement.com">success@hackleyhealthmanagement.com</a> with your story to be considered.</p>
</div>
<p style="color: #777; font-size: 10px; margin-top: 10px;">Results not typical.<br />
  HMR makes no claims that these results are representative of all patients in the HMR program.</p>
