<img style="padding: 0px 0px 10px 10px; max-width: 213px!important; height: auto;" src="/media/wysiwyg/shannon-success.jpg" alt="Shannon Moon" align="right" />
<h1>I'll Always be HMR's number one fan!</h1>
<p>&ldquo;I have always been overweight&mdash;even as a child. When you are as overweight as I was, you become almost invisible. I never had a thin moment, and for my whole life I had been belittled because of this. I&rsquo;ve bought every fad diet book, taken diet pills, and even tried starving myself. Every time I lost a little bit of weight and the gained it right back. I didn&rsquo;t have any education about calories and fats and my sweet tooth always got me in trouble. There wasn&rsquo;t enough ice cream in the world to satisfy me. I could eat an entire gallon.</p>
<p>&ldquo;Before I started on the program I went through all me receipts for a month and discovered that I was spending $800 on groceries and eating out. So I made a choice to spend this on my health.</p>
<p>&ldquo;HMR is life changing. I feel like I have my life back. People I haven&rsquo;t seen in some time don&rsquo;t recognize me&mdash;I love it when this happens. People treat me differently. People are friendlier and make more eye contact.</p>
<p>&ldquo;The positive environment HMR offered in their classes was so important. They were non-judgmental and always supportive. I love coming to my weekly meetings because the accountability helps me. HMR is the easiest diet I&rsquo;ve ever done. Between all the entrees and shakes I had plenty of choices, but it was all laid out for me. I still use HMR meal replacements. I eat them everyday for breakfast and lunch and sometimes dinner. All the dishes are quick and easy to make. Today I sleep more soundly and have more energy. I can run now that my body is lighter. I have my self-esteem back.</p>
<p>&ldquo;I&rsquo;ll always be HMR&rsquo;s number one fan!&rdquo;</p>
<div style="width: 33%; float: left;">
  <p>Healthy Solutions&reg;<br />
    34 years old <br />
    Pounds lost: 70 <br />
    Lost her weight in: 2002</p>
</div>
<div style="width: 33%; float: left;">
  <p>Cholesterol (normal under 200)<br />
    Before HMR: 183 <br />
    After HMR: 129</p>
</div>
<div style="width: 33%; float: left;">
  <p>Blood Pressure (normal 120/80 or lower)<br />
    Before HMR: 120/60 <br />
    After HMR: 90/60</p>
</div>
<p style="clear: both;"><strong>Shannon Moon</strong></p>
<div class="success-notice">
  <h3>Share your story today!</h3>
  <p>We'd like to hear, in your own words, how the HMR Program has affected you - your health, your life, your family, and your friends. By sharing your experiences, you may help another person to lose weight and get healthier.</p>
  <ul>
    <li>Why did you search for a weight loss program?</li>
    <li>What was the hardest part of your struggle?</li>
    <li>What advice would you give to others?</li>
  </ul>
  <p>Be sure to include your mailing address, fax and phone number. We may be contacting you and asking you to share your story with the world!</p>
  <p>Please email <a href="mailto:success@hackleyhealthmanagement.com">success@hackleyhealthmanagement.com</a> with your story to be considered.</p>
</div>
<p style="color: #777; font-size: 10px; margin-top: 10px;">Results not typical.<br />
  HMR makes no claims that these results are representative of all patients in the HMR program.</p>
