<img style="padding: 0px 0px 10px 10px; width: 240px!important; height: auto;" src="/media/wysiwyg/ShirleyLemon.jpg" alt="Shirley Lemon" align="right" />
<h1>Losing Weight is Never Easy but I was Diligent and in the First Week Lost 9 Pounds.</h1>
<p>I don't believe anyone has a plan to become overweight. In my case it was a combination of genetics, bad eating habits, lack of exercise and treating eating as a reward . 'I deserve this cookie because I had a great day at work', or 'I had a bad day so I need this cookie to feel better.' Well, one cookie leads to two, four, ten . . It became a real problem.</p>
<p>After spending much of my life eating then dieting, and continuing to repeat the entire cycle, I found myself 100 pounds overweight, on the verge of being diabetic, pain in my knees and feet and the feeling that I was going to die after chaperoning my daughter's sixth grade trip to Mackinaw Island.</p>
<p>There are many wonderful diet programs in the world but I feel you have to find the one that is right for you. I needed one with few choices. Choices, albeit poor ones, were the reason for my weight gain. I had a dear friend that was losing weight and when asked, recommended with much enthusiasm the Hackley Health Management program.</p>
<p>One visit with one of their health educators and I was ready to choose the program that fit me the best. I decided on Decisions Free, the total meal replacement program. Losing weight is never easy but I was diligent and in the first week lost 9 pounds. What great incentive to continue! Every person handles the program differently but I found that I needed to be around food so I cooked and baked constantly. My family and friends were thrilled to have so many home cooked meals. I never just tasted or took a bite and felt so proud that I was gaining control over my overeating. Much to my surprise after following the program religiously for eight months, I lost 100 pounds! I was never hungry and the physical activity requirement gave me more energy and pride than I could ever have imagined.</p>
<p>I transferred to Healthy Solutions, adding fruits and vegetables to the meal replacements. Green beans never tasted so good! One of the most important aspects of the program is the weekly classes to keep everyone accountable but more importantly, to teach healthy eating, portion size, eating and living in the real world.</p>
<p>I've transferred to the maintenance program and will continue for the prescribed eighteen months. What a fabulous journey it has been! I couldn't have done it without the care and guidance of the Hackley staff and the marvelous weight loss program.</p>
<p>I am proud that I have taken control of my health. My life depended on it.</p>
<p><strong>Shirley Lemon</strong></p>
<div class="success-notice">
  <h3>Share your story today!</h3>
  <p>We'd like to hear, in your own words, how the HMR Program has affected you - your health, your life, your family, and your friends. By sharing your experiences, you may help another person to lose weight and get healthier.</p>
  <ul>
    <li>Why did you search for a weight loss program?</li>
    <li>What was the hardest part of your struggle?</li>
    <li>What advice would you give to others?</li>
  </ul>
  <p>Be sure to include your mailing address, fax and phone number. We may be contacting you and asking you to share your story with the world!</p>
  <p>Please email <a href="mailto:success@hackleyhealthmanagement.com">success@hackleyhealthmanagement.com</a> with your story to be considered.</p>
</div>
<p style="color: #777; font-size: 10px; margin-top: 10px;">Results not typical.<br />
  HMR makes no claims that these results are representative of all patients in the HMR program.</p>
