<img style="padding: 0px 0px 10px 10px; max-width: 213px!important; height: auto;" src="/media/wysiwyg/shirly-success.jpg" alt="Shirly Santana" align="right" />
<h1>I'll Always be HMR's number one fan!</h1>
<p><strong>How did you first hear of Hackley Health Management?</strong><br />
  I found HHM in the phone book, and had heard of it about 10 years ago, when I was looking for a weight loss program.</p>
<p><strong>How did the staff treat you?</strong><br />
  With dignity, respect, and professionalism.</p>
<p><strong>What did you like about the program?</strong><br />
  The staff are great people, the group settings with others striving toward the same goals, and the information given on health, exercise, nutrition and weight management.</p>
<p><strong>What would you tell people that say they can't do it?</strong><br />
  I would tell them that at one time I had felt the same way, but that HHM has changed my life.</p>
<p><strong>What motivated you about the program?</strong><br />
  Seeing results week after week and being able to maintain my weight loss.</p>
<p><strong>How do you feel now that you have lost weight?</strong><br />
  I feel great about how I look and feel!</p>
<p>I once believed I couldn't do it, but HHM changed my life!</p>
<p><strong>Shirly Santana</strong><br />
  Muskegon, MI</p>
<div class="success-notice">
  <h3>Share your story today!</h3>
  <p>We'd like to hear, in your own words, how the HMR Program has affected you - your health, your life, your family, and your friends. By sharing your experiences, you may help another person to lose weight and get healthier.</p>
  <ul>
    <li>Why did you search for a weight loss program?</li>
    <li>What was the hardest part of your struggle?</li>
    <li>What advice would you give to others?</li>
  </ul>
  <p>Be sure to include your mailing address, fax and phone number. We may be contacting you and asking you to share your story with the world!</p>
  <p>Please email <a href="mailto:success@hackleyhealthmanagement.com">success@hackleyhealthmanagement.com</a> with your story to be considered.</p>
</div>
<p style="color: #777; font-size: 10px; margin-top: 10px;">Results not typical.<br />
  HMR makes no claims that these results are representative of all patients in the HMR program.</p>
