<h3><a href="https://www.youtube.com/watch?v=4jwq-y4gq_Q&feature=youtu.be" target="_blank"><img src="/media/wysiwyg/kevin-feature.jpg" alt="" /></a></h3>
<div class="success-wrapper">
  <div class="success-feature">
    <div class="feature-item">
      <h3><a href="http://www.youtube.com/watch?v=cfl1VhbCFbA&amp;lr=1" target="_blank">Diane's Success Story</a></h3>
      <p>Watch Diane tell her story of how her success in the HMR Program positively impacted her life.</p>
    </div>
    <div class="feature-item"><a href="http://www.youtube.com/watch?v=cfl1VhbCFbA&amp;lr=1" target="_blank"><img src="/media/wysiwyg/diane-sub-feature.jpg" alt="Watch Diane's success story" /></a></div>
  </div>
  <br/>
  <div class="success-feature">
    <div class="feature-item">
      <h3><a href="http://www.youtube.com/user/HackleyHealthMgmt?feature=mhee#p/a/u/0/VHqXHfzr9fg" target="_blank">Dirk Fuller</a></h3>
      <p>Fuller's success story as a participant at Mercy Health Partner's "Hackley Health Management".</p>
      <p>DSE-TV's "Alive &amp; Well"<br />
        <em>Hosted by Lynda Balkema.</em></p>
    </div>
    <div class="feature-item"><a href="http://www.youtube.com/user/HackleyHealthMgmt?feature=mhee#p/a/u/0/VHqXHfzr9fg" target="_blank"><img src="/media/wysiwyg/success-vid_r3_c2.jpg" alt="Watch Dirk Fuller's success story" /></a></div>
  </div>
  <br/>
  <div class="clear">&nbsp;</div>
    <div class="success-item no-border"><a href="/success/ginger-gonyon-success-story"><img src="/media/wysiwyg/ginger-success-thumb.png" alt="Ginger Gonyon" /></a>
    <h3><a href="/success/ginger-gonyon-success-story">Ginger Gonyon</a></h3>
    <p>"The results were better than I expected. My cholesterol, triglycerides, and blood sugar were all at normal levels. My blood pressure has been normal for three months. The knee and back pain I suffered in the past is seldom noticed anymore"........</p>
    <p><a href="/success/ginger-gonyon-success-story">Read More...</a></p>
  </div>
  <div class="success-item"><a href="/success/kirby-chittenden-success-story"><img src="/media/wysiwyg/chittenden-sm.jpg" alt="Kirby Chittenden" /></a>
    <h3><a href="/success/kirby-chittenden-success-story">Kirby Chittenden</a></h3>
    <p>After his weight ballooned to 238 pounds in 2008, Kirby Chittenden knew it was time to change his lifestyle. Not only was Chittenden gaining weight, his health was suffering. Fast-forward to 2011 and you'll find a different Kirby Chitt........</p>
    <p><a href="/success/kirby-chittenden-success-story">Read More...</a></p>
  </div>
  <div class="success-item"><a href="/success/lois-wilterdink-success-story"><img src="/media/wysiwyg/lois-after-wow-sm.jpg" alt="Lois Wilterdink" /></a>
    <h3><a href="/success/lois-wilterdink-success-story">Lois Wilterdink <em>(Muskegon, MI)</em></a></h3>
    <p>I've had many medical problems in my life that run in my family. My main problem has been fibromyalgia and osteoarthritis. When you have these, the more you weigh, the more you hurt. Pain was my life and it was almost unbearable w........</p>
    <p><a href="/success/lois-wilterdink-success-story">Read More...</a></p>
  </div>
  <div class="success-item"><a href="/success/shirley-lemon-success-story"><img src="/media/wysiwyg/ShirleyLemon-sm.jpg" alt="Shirley Lemon" /></a>
    <h3><a href="/success/shirley-lemon-success-story">Shirley Lemon</a></h3>
    <p>I don't believe anyone has a plan to become overweight. In my case it was a combination of genetics, bad eating habits, lack of exercise and treating eating as a reward . 'I deserve this cookie because I had a great day at work', or 'I had a........</p>
    <p><a href="/success/shirley-lemon-success-story">Read More...</a></p>
  </div>
  <div class="success-item"><a href="/success/susan-starbuck-success-story"><img src="/media/wysiwyg/Susanweb-sm.jpg" alt="Susan Starbuck" /></a>
    <h3><a href="/success/susan-starbuck-success-story">Susan Starbuck</a></h3>
    <p>I started my journey to health with Hackley Health Management's HMR program under protest, and not with the greatest attitude! My primary care physician referred me to the program after I informed him that I intended to go off of all 9 of my p........</p>
    <p><a href="/success/susan-starbuck-success-story">Read More...</a></p>
  </div>
  <div class="success-item"><a href="/success/kris-rieger-success-story"><img src="/media/wysiwyg/kris_07_lg-sm.jpg" alt="Kris Rieger" /></a>
    <h3><a href="/success/kris-rieger-success-story">Kris Rieger</a></h3>
    <p>It was suppose to be a fun day at Ohio's Cedar Point Amusement Park. Rural Fruitport resident Kris Rieger braved a long wait with her brother to ride the Raptor roller coaster and they settled into the seat. Then it came. Rieger's li........</p>
    <p><a href="/success/kris-rieger-success-story">Read More...</a></p>
  </div>
  <div class="success-item"><a href="/success/jim-oros-success-story"><img src="/media/wysiwyg/JimAfterWow-sm.jpg" alt="Jim Oros" /></a>
    <h3><a href="/success/jim-oros-success-story">Jim Oros</a></h3>
    <p>If the tri-county area held its own "Biggest Loser" contest, Very Low Calorie Diet faithful Jim Oros would surely be in the running for the top prize. Oros has dedicated his diet to mostly liquid for 11 months and is half the........</p>
    <p><a href="/success/jim-oros-success-story">Read More...</a></p>
  </div>
  <div class="success-item"><a href="/success/successful-dieter-success-story"><img src="/media/wysiwyg/successful-dieter-sm.jpg" alt="Successful dieter" /></a>
    <h3><a href="/success/successful-dieter-success-story">Successful dieter</a></h3>
    <p>I started my journey to health with Hackley Health Management's HMR program under protest, and not with the greatest attitude! My primary care physician referred me to the program after I informed him that I intended to go off of all 9 of my p........</p>
    <p><a href="/success/successful-dieter-success-story">Read More...</a></p>
  </div>
  <div class="success-item"><a href="/success/alisa-ruby-torres-success-story"><img src="/media/wysiwyg/alisa-sm.jpg" alt="Alisa Ruby-Torres" /></a>
    <h3><a href="/success/alisa-ruby-torres-success-story">Alisa Ruby-Torres</a></h3>
    <p>"Before I found HMR I was a size 24. I was an obese child and have always had weight problems. I tried more diets than I can count, but I'd lose the weight and gain it back. I felt like I was twice my age and I was exhausted. I am a teacher, so typic........</p>
    <p><a href="/success/alisa-ruby-torres-success-story">Read More...</a></p>
  </div>
  <div class="success-item"><a href="/success/ruth-davidson-success-story"><img src="/media/wysiwyg/ruth-success-sm.jpg" alt="Ruth Davidson" /></a>
    <h3><a href="/success/ruth-davidson-success-story">Ruth Davidson</a></h3>
    <p>I had not done a lot of diets before HMR. I just wasn't interested and I kept gaining weight. At my highest weight I was 226 pounds. To maintain that, you eat a lot of junk. You're not eating foods that make you feel good physically. If I went on vac........</p>
    <p><a href="/success/ruth-davidson-success-story">Read More...</a></p>
  </div>
  <div class="success-item"><a href="/success/rick-genter-success-story"><img src="/media/wysiwyg/rick-success-sm.jpg" alt="Rick Genter" /></a>
    <h3><a href="/success/rick-genter-success-story">Rick Genter</a></h3>
    <p>"I've been overweight my whole life. Before HMR, I used to go out for lunch all the time and the only vegetables I ate came on a pizza. My waist was 58 inches and I was at high risk for a heart attack and for diabetes. I had tried other diets befor........</p>
    <p><a href="/success/rick-genter-success-story">Read More...</a></p>
  </div>
  <div class="success-item"><a href="/success/shannon-moon-success-story"><img src="/media/wysiwyg/shannon-success-sm.jpg" alt="Shannon Moon" /></a>
    <h3><a href="/success/shannon-moon-success-story">Shannon Moon</a></h3>
    <p>"I have always been overweight&mdash;even as a child. When you are as overweight as I was, you become almost invisible. I never had a thin moment, and for my whole life I had been belittled because of this. I've bought every fad diet book, taken diet pills........</p>
    <p><a href="/success/shannon-moon-success-story">Read More...</a></p>
  </div>
  <div class="success-item"><a href="/success/shirly-santana-success-story"><img src="/media/wysiwyg/shirly-success-sm.jpg" alt="Shirly Santana" /></a>
    <h3><a href="/success/shirly-santana-success-story">Shirly Santana <em>(Muskegon, MI)</em></a></h3>
    <p><strong>How did you first hear of Hackley Health Management?</strong><br />
      I found HHM in the phone book, and had heard of it about 10 years ago, when I was looking for a weight loss program.</p>
    <p><a href="/success/shirly-santana-success-story">Read More...</a></p>
  </div>
  <div class="success-item"><a href="/success/peggy-silvis-success-story"><img src="/media/wysiwyg/peggy-success-sm.jpg" alt="Peggy Silvis" /></a>
    <h3><a href="/success/peggy-silvis-success-story">Peggy Silvis <em>(Muskegon, MI)</em></a></h3>
    <p>I have tried many weight loss programs before, and I really feel wonderful about Hackley Health Management and its staff! Their program has excellent food (entrees, bars, and shakes), weekly meetings (a must!) and weekly weigh-ins (to keep you honest........</p>
    <p><a href="/success/peggy-silvis-success-story">Read More...</a></p>
  </div>
  <div class="success-notice">
  <h3>Share your story today!</h3>
  <p>We'd like to hear, in your own words, how the HMR Program has affected you - your health, your life, your family, and your friends. By sharing your experiences, you may help another person to lose weight and get healthier.</p>
  <ul>
    <li>Why did you search for a weight loss program?</li>
    <li>What was the hardest part of your struggle?</li>
    <li>What advice would you give to others?</li>
  </ul>
  <p>Be sure to include your mailing address, fax and phone number. We may be contacting you and asking you to share your story with the world!</p>
  <p>Please email <a href="mailto:success@hackleyhealthmanagement.com">success@hackleyhealthmanagement.com</a> with your story to be considered.</p>
</div>
<p style="color: #777; font-size: 10px; margin-top: 10px;">Results not typical.<br />
  HMR makes no claims that these results are representative of all patients in the HMR program.</p>
</div>