<div id="container" class="cf">
  <div id="main" role="main">
    <section class="slider">
      <div class="flexslider newsletters">
        <ul class="slides">
          <li> <img src="http://hhm.next-it.net/media/pdf/fall2012_thumb.jpg" alt="Fall - 2012" /> </li>
          <li> <img src="http://hhm.next-it.net/media/pdf/spring2012_thumb.jpg" alt="Spring - 2012" /> </li>
          <li> <img src="http://hhm.next-it.net/media/pdf/spring2011_thumb.jpg" alt="Spring - 2011" /> </li>
        </ul>
      </div>
    </section>
  </div>
  <div class="newsletters-title">
  <h1>Hackley Health Management Newsletters</h1>
</div>
  <div id="newsletters_thumbnails">
    <div class="newsletters_issue">
      <h3><a href="../media/pdf/winter2011.pdf" target="_blank">Winter - 2011</a></h3>
      <a href="../media/pdf/winter2011.pdf" target="_blank"> <img src="../media/pdf/winter2011_thumb.jpg" alt="Winter - 2011" /></a> </div>
    <div class="newsletters_issue">
      <h3><a href="../media/pdf/fall2009.pdf" target="_blank">Fall - 2009</a></h3>
      <a href="../media/pdf/fall2009.pdf" target="_blank"> <img src="../media/pdf/fall2009_thumb.jpg" alt="Fall - 2009" /></a> </div>
    <div class="newsletters_issue">
      <h3><a href="../media/pdf/summer2009.pdf" target="_blank">Summer - 2009</a></h3>
      <a href="../media/pdf/summer2009.pdf" target="_blank"><img src="../media/pdf/summer2009_thumb.jpg" alt="Summer - 2009" /></a> </div>
    <div class="newsletters_issue">
      <h3><a href="../media/pdf/spring2009.pdf" target="_blank">Spring - 2009</a></h3>
      <a href="../media/pdf/spring2009.pdf" target="_blank"><img src="../media/pdf/spring2009_thumb.jpg" alt="Spring - 2009" /></a> </div>
    <div class="newsletters_issue">
      <h3><a href="../media/pdf/winter2009.pdf" target="_blank">Winter - 2009</a></h3>
      <a href="../media/pdf/winter2009.pdf" target="_blank"><img src="../media/pdf/winter2009_thumb.jpg" alt="Winter2009" /></a> </div>
    <div class="newsletters_issue">
      <h3><a href="../media/pdf/fall2008.pdf" target="_blank">Fall - 2008</a></h3>
      <a href="../media/pdf/fall2008.pdf" target="_blank"><img src="../media/pdf/fall2008_thumb.jpg" alt="Fall - 2008" /></a> </div>
    <div class="newsletters_issue">
      <h3><a href="../media/pdf/summer2008.pdf" target="_blank">Summer - 2008</a></h3>
      <a href="../media/pdf/summer2008.pdf" target="_blank"><img src="../media/pdf/summer2008_thumb.jpg" alt="Summer2008" /></a> </div>
    <div class="newsletters_issue">
      <h3><a href="../media/pdf/spring2008.pdf" target="_blank">Spring - 2008</a></h3>
      <a href="../media/pdf/spring2008.pdf" target="_blank"><img src="../media/pdf/spring2008_thumb.jpg" alt="Spring - 2008" /></a> </div>
    <div class="newsletters_issue">
      <h3><a href="../media/pdf/winter2008.pdf" target="_blank">Winter - 2008</a></h3>
      <a href="../media/pdf/winter2008.pdf" target="_blank"><img src="../media/pdf/winter2008_thumb.jpg" alt="Winter - 2008" /></a> </div>
    <div class="newsletters_issue">
      <h3><a href="../media/pdf/fall2007.pdf" target="_blank">Fall - 2007</a></h3>
      <a href="../media/pdf/fall2007.pdf" target="_blank"><img src="../media/pdf/fall2007_thumb.jpg" alt="Fall - 2007" /></a> </div>
    <div class="newsletters_issue">
      <h3><a href="../media/pdf/spring2007.pdf" target="_blank">Spring - 2007</a></h3>
      <a href="../media/pdf/spring2007.pdf" target="_blank"><img src="../media/pdf/spring2007_thumb.jpg" alt="Spring - 2007" /></a> </div>
    <div class="newsletters_issue">
      <h3><a href="../media/pdf/winter2007.pdf" target="_blank">Winter - 2007</a></h3>
      <a href="../media/pdf/winter2007.pdf" target="_blank"><img src="../media/pdf/winter2007_thumb.jpg" alt="Winter - 2007" /></a> </div>
    <div class="newsletters_issue">
      <h3><a href="../media/pdf/fall2006.pdf" target="_blank">Fall - 2006</a></h3>
      <a href="../media/pdf/fall2006.pdf" target="_blank"><img src="../media/pdf/fall2006_thumb.jpg" alt="Fall - 2006" /></a> </div>
    <div class="newsletters_issue">
      <h3><a href="../media/pdf/summer2006.pdf" target="_blank">Summer - 2006</a></h3>
      <a href="../media/pdf/summer2006.pdf" target="_blank"><img src="../media/pdf/summer2006_thumb.jpg" alt="Summer - 2006" /></a> </div>
  </div>
</div>

<!-- jQuery --> 
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script> 
<script>window.jQuery || document.write('<script src="js/libs/jquery-1.7.min.js">\x3C/script>')</script> 

<!-- FlexSlider --> 
<script defer src="http://hhm.next-it.net/skin/frontend/default/shopper/js/jquery.flexslider.js"></script> 
<script type="text/javascript">
    $(function(){
      SyntaxHighlighter.all();
    });
    $(window).load(function(){
      $('.flexslider').flexslider({
        animation: "slide",
        start: function(slider){
          $('body').removeClass('loading');
        }
      });
    });
  </script> 

<!-- Syntax Highlighter --> 
<script type="text/javascript" src="http://hhm.next-it.net/skin/frontend/default/shopper/js/shCore.js"></script> 
<script type="text/javascript" src="http://hhm.next-it.net/skin/frontend/default/shopper/js/shBrushXml.js"></script> 
<script type="text/javascript" src="http://hhm.next-it.net/skin/frontend/default/shopper/js/shBrushJScript.js"></script> 

<!-- Optional FlexSlider Additions --> 
<script src="http://hhm.next-it.net/skin/frontend/default/shopper/js/jquery.easing.js"></script> 
<script src="http://hhm.next-it.net/skin/frontend/default/shopper/js/jquery.mousewheel.js"></script> 
<script defer src="http://hhm.next-it.net/skin/frontend/default/shopper/js/demo.js"></script>