<?php
/**
 * Product view nutrition tab file
 * LICENSE: This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * @category  Mage
 * @package   Mage_Catalog
 * @copyright Copyright (c) 2014 Next I.T. (http://www.next-it.net/)
 * @license   http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/**
 * Product view nutrition template
 * @see Mage_Catalog_Block_Product_View_Ingredients
 */
?>
<?php /* @var $this Mage_Catalog_Block_Product_View_Ingredients */ ?>
<?php $ingredients = $this->getIngredients(); ?>
<?php if (!empty($ingredients)): ?>
    <strong>Ingredients: </strong><?php echo $ingredients; ?>
<?php else: ?>
	<?php if ( $this->isKitOrShake() === 'kit' ): ?>
		<p class="text-center">To view the ingredients for an at-home kit, please view the individual entree product pages.<br /><a href="/shop/hmr-diet-entrees" target="_blank">You may click here to view the Entree category.</a></p>
	<?php elseif ( $this->isKitOrShake() === 'shake' ):?>
		<p class="text-center">To view the ingredients for a shake kit, please view the individual shake product pages.<br/><a href="/shop/hmr-diet-shakes-puddings" target="_blank">You may click here to view the Shake category.</a></p>
	<?php else: ?>
    <h1><?php echo $this->__('Coming Soon'); ?></h1>
	<?php endif; ?>
<?php endif; ?>