<div class="col-main recipe-categories-main">
  <div class="category-description std recipe-categories">
    <h1>HMR Recipes - Categories</h1>
  </div>
  <div class="category-products">
    <ul class="products-grid">
      <li class="item calc-price-box" style="height: 327px;">
        <div class="regular"><a class="product-image" title="HMR&reg; Shake and Smoothie Recipes" href="/hmr-recipes/shake-and-smoothie"> <img src="/media/recipes/shakes-smoothies-rec-cat.jpg" alt="HMR&reg; Shake and Smoothie Recipes" /> </a> <a class="product-name" title="HMR&reg; Shake and Smoothie Recipes" href="/hmr-recipes/shake-and-smoothie">HMR<sup>&reg;</sup> Shake and Smoothie Recipes</a></div>
      </li>
      <li class="item calc-price-box" style="height: 327px;">
        <div class="regular"><a class="product-image" title="HMR&reg; Recipes for Pudding and Mousse" href="hmr-recipes/pudding-and-mousse"> <img src="/media/recipes/pudding-rec-cat.jpg" alt="HMR&reg; Recipes for Pudding and Mousse" /> </a> <a class="product-name" title="HMR&reg; Recipes for Pudding and Mousse" href="hmr-recipes/pudding-and-mousse">HMR<sup>&reg;</sup> Recipes for Pudding and Mousse</a></div>
      </li>
      <li class="item calc-price-box" style="height: 327px;">
        <div class="regular"><a class="product-image" title="HMR&reg; Multigrain Cereal Recipes" href="hmr-recipes/multigrain-cereal"> <img src="/media/recipes/cereal-rec-cat.jpg" alt="HMR&reg; Multigrain Cereal Recipes" /> </a> <a class="product-name" title="HMR&reg; Multigrain Cereal Recipes" href="hmr-recipes/multigrain-cereal">HMR<sup>&reg;</sup> Multigrain Cereal Recipes</a></div>
      </li>
      <li class="item calc-price-box" style="height: 327px;">
        <div class="regular"><a class="product-image" title="HMR&reg; Entree Recipes" href="/hmr-recipes/entree"> <img src="/media/recipes/entrees-rec-cat.jpg" alt="HMR&reg; Entree Recipes" /> </a> <a class="product-name" title="HMR&reg; Entree Recipes" href="/hmr-recipes/entree">HMR<sup>&reg;</sup> Entree Recipes</a></div>
      </li>
      <li class="item calc-price-box" style="height: 327px;">
        <div class="regular"><a class="product-image" title="HMR&reg; Recipes for Soup" href="/hmr-recipes/soup"> <img src="/media/recipes/soup-rec-cat.jpg" alt="HMR&reg; Recipes for Soup" /> </a> <a class="product-name" title="HMR&reg; Recipes for Soup" href="/hmr-recipes/soup">HMR<sup>&reg;</sup> Recipes for Soup</a></div>
      </li>
      <!--<li class="item calc-price-box" style="height: 327px;">
        <div class="regular"><a class="product-image" title="HMR&reg; BeneFit Bar Recipes" href="/hmr-recipes/benefit-bar"> <img src="/media/recipes/bars-rec-cat.jpg" alt="HMR&reg; BeneFit Bar Recipes" /> </a> <a class="product-name" title="HMR&reg; BeneFit Bar Recipes" href="/hmr-recipes/benefit-bar">HMR<sup>&reg;</sup> BeneFit Bar Recipes</a></div>
      </li>-->
      <li class="item calc-price-box" style="height: 327px;">
        <div class="regular"><a class="product-image" title="HMR&reg; Dessert Recipes" href="/hmr-recipes/desserts"> <img src="/media/recipes/dessert-rec-cat.jpg" alt="HMR&reg; Dessert Recipes" /> </a> <a class="product-name" title="HMR&reg; Dessert Recipes" href="/hmr-recipes/desserts">HMR<sup>&reg;</sup> Dessert Recipes</a></div>
      </li>
      <li class="item calc-price-box" style="height: 327px;">
        <div class="regular"><a class="product-image" title="HMR&reg; Hot Drink Recipes" href="/hmr-recipes/hot-drink"> <img src="/media/recipes/hot-drink-rec-cat.jpg" alt="HMR&reg; Hot Drink Recipes" /> </a> <a class="product-name" title="HMR&reg; Hot Drink Recipes" href="/hmr-recipes/hot-drink">HMR<sup>&reg;</sup> Hot Drink Recipes</a></div>
      </li>
      <li class="item calc-price-box" style="height: 327px;">
        <div class="regular"><a class="product-image" title="Misc. HMR&reg; Recipes" href="/hmr-recipes/misc"> <img src="/media/recipes/misc-rec-cat.jpg" alt="Misc. HMR&reg; Recipes" /> </a> <a class="product-name" title="Misc. HMR&reg; Recipes" href="/hmr-recipes/misc">Misc. HMR<sup>&reg;</sup> Recipes</a></div>
      </li>
    </ul>
  </div>
</div>