<div class="about-header">
  <div class="about-us-title">
    <h1>Hackley Health Management has been servicing Muskegon since 1990.</h1>
  </div>
  <p>Hackley Health Management (HHM) is a medically-supervised weight loss clinic that offers several different programs. Each program, uniquely customized for every individual, offers a comprehensive approach to weight loss. All programs include in-depth lifestyle, education, and personal coaching. HHM has serviced thousands of individuals at its Muskegon location since 1990. </p>
</div>
<div class="about-profiles-title">
  <h1>Staff Profiles</h1>
</div>
<div id="accordion">
  <h3><span class="accordion_thumbnail"><img class="accordion_thumb" src="media/wysiwyg/blairMoreau_thumb.jpg" alt="Blair Moreau" /></span> <span class="accordian_s_wrap"> <span class="accordion_title">Blair Moreau<br />
    <span class="profile-position">Director</span><br />
    </span> <span class="accordion_description">Team Member Since: 2011</span> </span> <span class="accordion_readMore">&or;</span>
    <div class="dummy-close-x"><img src="media/wysiwyg/close-about-tabs.png" alt="Close" /></div>
  </h3>
  <div>
    <div class="accordion_image"><img src="media/wysiwyg/Blair-Moreau.jpg" alt="Blair Moreau" /></div>
    <p><strong><em>How long have you worked for HHM? </em></strong> <br />
      I joined the HHM team in 2011. <br />
      <br />
      <strong><em>What is your educational background?</em></strong> <br />
      BS in Exercise Physiology from Central Michigan University in 1987 <br />
      ACSM- CES in 1998 <br />
      MSA from Central Michigan University in 2007 <br />
      <br />
      <strong><em>What is the favorite part of your job? </em></strong> <br />
      People! <br />
      <br />
      <strong><em>What are you passionate about?</em></strong> <br />
      People, Family, Team Members, Exercise and Fun! <br />
      <br />
      <strong><em>What do you like to do for fun?</em></strong> <br />
      I enjoy spending time with my wife and three daughters. I also enjoy working out, especially when I can push my body to (and past!) it's limit. <br />
      <br />
      <strong><em>Why do you enjoy living in Western Michigan? </em></strong> <br />
      I love the people here and also the beautiful area in which we live. I grew up on Lake Michigan and the lake always draws you back. <br />
      <br />
      <a href="mailto:MoreauB@mercy-health.org">MoreauB@mercy-health.org</a></p>
  </div>
  <h3><span class="accordion_thumbnail"><img class="accordion_thumb" src="media/wysiwyg/carrieKelly_thumb.jpg" alt="Carrie Kelly" /></span><span class="accordian_s_wrap"><span class="accordion_title">Carrie Kelly<br />
    <span class="profile-position"> Operations Supervisor</span><br />
    </span><span class="accordion_description"> Team Member Since: 1999</span></span><span class="accordion_readMore">&or;</span>
    <div class="dummy-close-x"><img src="media/wysiwyg/close-about-tabs.png" alt="Close" /></div>
  </h3>
  <div>
    <div class="accordion_image"><img src="media/wysiwyg/carrie-2011.jpg" alt="Carrie Kelly" /></div>
    <p><strong><em>How long have you worked for HHM?</em></strong> <br />
      Since November 1999 <br />
      <br />
      <strong><em>What is your educational background?</em></strong> <br />
      I have my Bachelors degree in Elementary Education from Western Michigan University. <br />
      <br />
      <strong><em>What is the favorite part of your job?</em></strong> <br />
      I love watching our patient's transform as they meet their health management goals. Not only does their physical appearance change, but so does their attitude and outlook on life! <br />
      <br />
      <strong><em>What are you passionate about?</em></strong> <br />
      My family! I have been blessed with a wonderful husband and two amazing sons. They teach me to enjoy life and be a better person every day! <br />
      <br />
      <strong><em>What do you like to do for fun?</em></strong> <br />
      My first preference is to pack up the family and go on an outing whether it is to the beach, to the mall, or just for a walk. If I have some time to myself, I like to scrapbook, read, or visit with my friends. <br />
      <br />
      <strong><em>Why do you enjoy living in Western Michigan ?</em></strong> <br />
      Muskegon is a wonderful place to live! Living here gives me the small town feel, but allows me to have easy access to Grand Haven or Grand Rapids if I need a change of scenery. Western Michigan has a large variety of things to do year around. You can attend an art fair or visit one of our many beaches in the summer, pick apples and pumpkins in the fall, find a good sledding hill or visit an indoor waterpark in the winter, or see the butterflies hatch at Meijer Gardens in the spring. This is a fabulous place to have fun with your family! <br />
      <br />
      <a href="mailto:kellyca@mercy-health.org">kellyca@mercy-health.org</a></p>
  </div>
  <h3><span class="accordion_thumbnail"><img class="accordion_thumb" src="media/wysiwyg/drDavidFolkmier_thumb.jpg" alt="Dr. David Folkmier" /></span><span class="accordian_s_wrap"><span class="accordion_title">Dr. David Folkmier<br />
    <span class="profile-position">Medical Director</span><br />
    </span><span class="accordion_description"> Team Member Since: 2008</span></span><span class="accordion_readMore">&or;</span>
    <div class="dummy-close-x"><img src="media/wysiwyg/close-about-tabs.png" alt="Close" /></div>
  </h3>
  <div>
    <div class="accordion_image"><img src="media/wysiwyg/Dr-David-Folkmier-DO.jpg" alt="Dr. David Folkmier" /></div>
    <p><strong><em>How long have you worked for HHM?</em></strong> <br />
      I became their Medical Director in 2008. <br />
      <br />
      <strong><em>What is your educational background?</em></strong> <br />
      I graduated from Michigan State University in 1986 with a BS in Medical Technology, and from MSU's College of Osteopathic Medicine in 1990. <br />
      1990-1993 I had my residency at Detroit Hospital/ BiCounty Community Hospital and been Board Certified in Internal Medicine since 1993. <br />
      <br />
      <strong><em>What is the favorite part of your job?</em></strong> <br />
      I enjoy the interaction with my patients and helping them learn how to achieve optimum health through a healthy lifestyle. <br />
      <br />
      <strong><em>What are you passionate about?</em></strong> <br />
      Helping people achieve excellent health!! It shouldn't be found through medical intervention, tests and pills, but in choosing a diet of nutritional excellence and regular physical activity. <br />
      <br />
      <strong><em>What do you like to do for fun?</em></strong> <br />
      Be active! Bike, Run and Kayak. <br />
      <br />
      <strong><em>Why do you enjoy living in Western Michigan?</em></strong> <br />
      I love the natural beauty of the outdoors. The Lake and beaches are exceptional. I enjoy biking, the hiking trails and of course all the summertime festivals.</p>
  </div>
  <h3><span class="accordion_thumbnail"><img class="accordion_thumb" src="media/wysiwyg/deborahSkinner_thumb.jpg" alt="Deborah Skinner" /></span><span class="accordian_s_wrap"><span class="accordion_title">Deborah Skinner<br />
    <span class="profile-position">NP</span><br />
    </span><span class="accordion_description"> Team Member Since: 2008</span></span><span class="accordion_readMore">&or;</span>
    <div class="dummy-close-x"><img src="media/wysiwyg/close-about-tabs.png" alt="Close" /></div>
  </h3>
  <div>
    <div class="accordion_image"><img src="media/wysiwyg/DebSkinner.jpg" alt="Deborah Skinner" /></div>
    <p><strong><em>How long have you worked for HHM?</em></strong><br />
      Since October 2008 <br />
      <br />
      <strong><em>What is your educational background?</em></strong><br />
      Deborah (or Deb as our patients know her) has a Bachelors of Science in Nursing from Ferris State University and Deb completed her graduate work with a specialty in family practice from Michigan State University. <br />
      <br />
      <strong><em>What is the favorite part of your job?</em></strong> <br />
      I have worked for HHM for a few years in the late 90s and decided to come back. The process is very similar so it was easy for me to slide back into the position. I love the people who work there. It is actually a very calming environment. My favorite part of the job is working with the patients. I love to hear where they are coming from as far as their strengths and weaknesses. <br />
      <br />
      <strong><em> What do you like to do for fun? </em></strong> <br />
      I enjoy reading, photography, and playing tennis on the weekends.</p>
  </div>
  <h3><span class="accordion_thumbnail"><img class="accordion_thumb" src="media/wysiwyg/donnamarieReed_thumb.jpg" alt="Donnamarie Welch" /></span><span class="accordian_s_wrap"><span class="accordion_title">Donnamarie Welch<br />
    <span class="profile-position"> Health Educator/Program Support Specialist</span><br />
    </span><span class="accordion_description"> Team Member Since: 2009</span></span><span class="accordion_readMore">&or;</span>
    <div class="dummy-close-x"><img src="media/wysiwyg/close-about-tabs.png" alt="Close" /></div>
  </h3>
  <div>
    <div class="accordion_image"><img src="media/wysiwyg/Donna-Phillips-New-Img.jpg" alt="Donnamarie Welch" /></div>
    <p><strong><em>How long have you worked for HHM?</em></strong> <br />
      I have had the privilege to be a Health Educator/Program Support Specialist with Hackley Health Management since November 5, 2009. <br />
      <br />
      <strong><em>What is your educational background?</em></strong> <br />
      I have been involved with fitness and nutrition for the past 20 years with certifications as fitness instructor/personal trainer, nutrition educator, and massage therapist. <br />
      <br />
      <strong><em>What is the favorite part of your job?</em></strong> <br />
      Being a part of the team at Hackley Health Management gives me the opportunity to meet many people and help them achieve their weight loss goals. It is such a celebration when we see patients succeed and become vibrant, happy and HEALTHY!!! <br />
      <br />
      <strong><em>What are you passionate about?</em></strong> <br />
      I am very passionate about people being the very best that they can be, both physically and emotionally and always reaching for new accomplishments in life. If I can be a small part of making a big difference in someone's life, that's HUGE! <br />
      <br />
      <strong><em>What do you like to do for fun?</em></strong> <br />
      I love spending my time at, on or in Lake Michigan along with riding all the great bike trails in the area. I'm always up for trying the new fitness craze! <br />
      <br />
      <a href="mailto:reeddma@mercy-health.org">reeddma@mercy-health.org</a></p>
  </div>
  <h3><span class="accordion_thumbnail"><img class="accordion_thumb" src="media/wysiwyg/lisaKraus_thumb.jpg" alt="Lisa Kraus" /></span><span class="accordian_s_wrap"><span class="accordion_title">Lisa Kraus<br />
    <span class="profile-position"> Program Coordinator / Health Educator</span><br />
    </span><span class="accordion_description"> Team Member Since: 2006</span></span><span class="accordion_readMore">&or;</span>
    <div class="dummy-close-x"><img src="media/wysiwyg/close-about-tabs.png" alt="Close" /></div>
  </h3>
  <div>
    <div class="accordion_image"><img src="media/wysiwyg/Lisa_Kraus.jpg" alt="Lisa Kraus" /></div>
    <p><strong><em>How long have you worked for HHM?</em></strong> <br />
      Since 2006 <br />
      <br />
      <strong><em>What is your educational background?</em></strong> <br />
      Bachelors in Business from MSU <br />
      <br />
      <strong><em>What is the favorite part of your job?</em></strong> <br />
      I love to see the confidence the patients gain as they lose weight. <br />
      <br />
      <strong><em>What are you passionate about?</em></strong> <br />
      I am passionate about learning in every part of my life. <br />
      <br />
      <strong><em>What do you like to do for fun?</em></strong> <br />
      Skate, read, and travel <br />
      <br />
      <strong><em>Why do you enjoy living in Western Michigan?</em></strong> <br />
      Sunsets and walking on the beach. <br />
      <br />
      <a href="mailto:krauslr@mercy-health.org">krauslr@mercy-health.org</a></p>
  </div>
  <h3><span class="accordion_thumbnail"><img class="accordion_thumb" src="media/wysiwyg/deborahPeabody_thumb.jpg" alt="Deborah Peabody" /></span><span class="accordian_s_wrap"><span class="accordion_title">Deborah Peabody<br />
    <span class="profile-position">Web Specialist</span><br />
    </span><span class="accordion_description"> Team Member Since: 2007</span></span><span class="accordion_readMore">&or;</span>
    <div class="dummy-close-x"><img src="media/wysiwyg/close-about-tabs.png" alt="Close" /></div>
  </h3>
  <div>
    <div class="accordion_image"><img src="media/wysiwyg/7.jpg" alt="Deborah Peabody" /></div>
    <p><strong><em>How long have you worked for HHM?</em></strong> <br />
      Since June 4, 2007. <br />
      <br />
      <strong><em>What is your educational background?</em></strong> <br />
      I have an associates degree with a major in business and marketing. <br />
      <br />
      <strong><em>What is the favorite part of your job?</em></strong> <br />
      Some of our customers call to place their orders and while on the phone they share their success stories and you can hear the pride in their voices. It makes my day. <br />
      <br />
      <strong><em>What are you passionate about?</em></strong> <br />
      I'm passionate about the environment and how I interact in it and with others. <br />
      <br />
      <strong><em>What do you like to do for fun?</em></strong> <br />
      I enjoy backpacking and when I can't do that you can't beat our nature trails for long walks. <br />
      <br />
      <strong><em>Why do you enjoy living in Western Michigan?</em></strong> <br />
      Western Michigan is my home. I love the lakes and all the nature trails. You can't ask for a better back yard. I have traveled a bit and I am never disappointed in coming home. <br />
      <br />
      <a href="mailto:orders@hackleyhealthmanagement.com">orders@hackleyhealthmanagement.com</a></p>
  </div>
</div>
<script src="http://code.jquery.com/ui/1.9.2/jquery-ui.js"></script> 
<script type="text/javascript">
//<![CDATA[
    jQuery(function() {
        jQuery("#accordion").accordion({
            collapsible: true,
			autoHeight: false,
			active: false
        });
    });
	//]]>
</script>