<div class="about-header">
	<div class="about-us-title">
		<h1>Hackley Health Management has been servicing Muskegon since 1990.</h1>
	</div>
	<p>Hackley Health Management (HHM) is a medically-supervised weight loss clinic that offers several different programs. Each program, uniquely customized for every individual, offers a comprehensive approach to weight loss. All programs include in-depth lifestyle, education, and personal coaching. HHM has serviced thousands of individuals at its Muskegon location since 1990. </p>
</div>
<div class="about-profiles-title">
	<h1>Staff Profiles</h1>
</div>
<div id="accordion">
	<h3><span class="accordion_thumbnail"><img class="accordion_thumb" src="media/wysiwyg/blairMoreau_thumb.jpg" alt="Blair Moreau" /></span> <span class="accordian_s_wrap"> <span class="accordion_title">Blair Moreau<br />
    <span class="profile-position">Director</span><br />
    </span> <span class="accordion_description">Team Member Since: 2011</span> </span> <span class="accordion_readMore">&or;</span>
		<span class="dummy-close-x"><img src="media/wysiwyg/close-about-tabs.png" alt="Close" /></span>
	</h3>
	<div>
		<div class="accordion_image"><img src="media/wysiwyg/Blair-Moreau.jpg" alt="Blair Moreau" /></div>
		<p><strong><em>How long have you worked for HHM? </em></strong> <br />
			I joined the HHM team in 2011. <br />
			<br />
			<strong><em>What is your educational background?</em></strong> <br />
			BS in Exercise Physiology from Central Michigan University in 1987 <br />
			ACSM- CES in 1998 <br />
			MSA from Central Michigan University in 2007 <br />
			<br />
			<strong><em>What is the favorite part of your job? </em></strong> <br />
			People! <br />
			<br />
			<strong><em>What are you passionate about?</em></strong> <br />
			People, Family, Team Members, Exercise and Fun! <br />
			<br />
			<strong><em>What do you like to do for fun?</em></strong> <br />
			I enjoy spending time with my wife and three daughters. I also enjoy working out, especially when I can push my body to (and past!) it's limit. <br />
			<br />
			<strong><em>Why do you enjoy living in Western Michigan? </em></strong> <br />
			I love the people here and also the beautiful area in which we live. I grew up on Lake Michigan and the lake always draws you back. <br />
			<br />
			Blair's Email: <a href="mailto:moreaub@mercyhealth.com">moreaub@mercyhealth.com</a></p>
	</div>
	<h3><span class="accordion_thumbnail"><img class="accordion_thumb" src="media/wysiwyg/carrieKelly_thumb.jpg" alt="Carrie Kelly" /></span><span class="accordian_s_wrap"><span class="accordion_title">Carrie Kelly<br />
    <span class="profile-position"> Operations Supervisor</span><br />
    </span><span class="accordion_description"> Team Member Since: 1999</span></span><span class="accordion_readMore">&or;</span>
		<span class="dummy-close-x"><img src="media/wysiwyg/close-about-tabs.png" alt="Close" /></span>
	</h3>
	<div>
		<div class="accordion_image"><img src="media/wysiwyg/carrie-2011.jpg" alt="Carrie Kelly" /></div>
		<p><strong><em>How long have you worked for HHM?</em></strong> <br />
			Since November 1999<br />
			<br />
			<strong><em>What is your educational background?</em></strong> <br />
			I have my Bachelors degree in Elementary Education from Western Michigan University.<br />
			<br />
			<strong><em>What is the favorite part of your job?</em></strong> <br />
			I love watching our patient's transform as they meet their health management goals. Not only does their physical appearance change, but so does their attitude and outlook on life!<br />
			<br />
			<strong><em>What are you passionate about?</em></strong> <br />
			My family! I have been blessed with a wonderful husband and three amazing sons. They teach me to enjoy life and be a better person every day!<br />
			<br />
			<strong><em>What do you like to do for fun?</em></strong> <br />
			My first preference is to pack up the family and go on an outing whether it is to the beach, to the mall, or just for a bike ride. If I have some time to myself, I like to read, go for a walk or visit with my friends.<br />
			<br />
			<strong><em>Why do you enjoy living in West Michigan?</em></strong> <br />
			Muskegon is a wonderful place to live! Living here gives me the small town feel, but allows me to have easy access to Grand Haven or Grand Rapids if I need a change of scenery. West Michigan has a large variety of things to do year around. You can attend an art fair or visit one of our many beaches in the summer, pick apples and pumpkins in the fall, find a good sledding hill or visit an indoor waterpark in the winter, or see the butterflies hatch at Meijer Gardens in the spring. This is a fabulous place to have fun with your family!<br />
			<br />
			Carrie's Email: <a href="mailto:kellyca@mercyhealth.com">kellyca@mercyhealth.com</a></p>
	</div>
	<h3><span class="accordion_thumbnail"><img class="accordion_thumb" src="media/wysiwyg/drDavidFolkmier_thumb.jpg" alt="Dr. David Folkmier" /></span><span class="accordian_s_wrap"><span class="accordion_title">Dr. David Folkmier<br />
    <span class="profile-position">Medical Director</span><br />
    </span><span class="accordion_description"> Team Member Since: 2008</span></span><span class="accordion_readMore">&or;</span>
		<span class="dummy-close-x"><img src="media/wysiwyg/close-about-tabs.png" alt="Close" /></span>
	</h3>
	<div>
		<div class="accordion_image"><img src="media/wysiwyg/Dr-David-Folkmier-DO.jpg" alt="Dr. David Folkmier" /></div>
		<p><strong><em>How long have you worked for HHM?</em></strong> <br />
			I became their Medical Director in 2008. <br />
			<br />
			<strong><em>What is your educational background?</em></strong> <br />
			I graduated from Michigan State University in 1986 with a BS in Medical Technology, and from MSU's College of Osteopathic Medicine in 1990. <br />
			1990-1993 I had my residency at Detroit Hospital/ BiCounty Community Hospital and been Board Certified in Internal Medicine since 1993. <br />
			<br />
			<strong><em>What is the favorite part of your job?</em></strong> <br />
			I enjoy the interaction with my patients and helping them learn how to achieve optimum health through a healthy lifestyle. <br />
			<br />
			<strong><em>What are you passionate about?</em></strong> <br />
			Helping people achieve excellent health!! It shouldn't be found through medical intervention, tests and pills, but in choosing a diet of nutritional excellence and regular physical activity. <br />
			<br />
			<strong><em>What do you like to do for fun?</em></strong> <br />
			Be active! Bike, Run and Kayak. <br />
			<br />
			<strong><em>Why do you enjoy living in Western Michigan?</em></strong> <br />
			I love the natural beauty of the outdoors. The Lake and beaches are exceptional. I enjoy biking, the hiking trails and of course all the summertime festivals.</p>
	</div>
	<h3><span class="accordion_thumbnail"><img class="accordion_thumb" src="media/wysiwyg/deborahSkinner_thumb.jpg" alt="Deborah Skinner" /></span><span class="accordian_s_wrap"><span class="accordion_title">Deborah Skinner<br />
    <span class="profile-position">NP</span><br />
    </span><span class="accordion_description"> Team Member Since: 2008</span></span><span class="accordion_readMore">&or;</span>
		<span class="dummy-close-x"><img src="media/wysiwyg/close-about-tabs.png" alt="Close" /></span>
	</h3>
	<div>
		<div class="accordion_image"><img src="media/wysiwyg/DebSkinner.jpg" alt="Deborah Skinner" /></div>
		<p><strong><em>How long have you worked for HHM?</em></strong><br />
			Since October 2008 <br />
			<br />
			<strong><em>What is your educational background?</em></strong><br />
			Deborah (or Deb as our patients know her) has a Bachelors of Science in Nursing from Ferris State University and Deb completed her graduate work with a specialty in family practice from Michigan State University. <br />
			<br />
			<strong><em>What is the favorite part of your job?</em></strong> <br />
			I have worked for HHM for a few years in the late 90s and decided to come back. The process is very similar so it was easy for me to slide back into the position. I love the people who work there. It is actually a very calming environment. My favorite part of the job is working with the patients. I love to hear where they are coming from as far as their strengths and weaknesses. <br />
			<br />
			<strong><em> What do you like to do for fun? </em></strong> <br />
			I enjoy reading, photography, and playing tennis on the weekends.</p>
	</div>
	<h3><span class="accordion_thumbnail"><img class="accordion_thumb" src="media/about/rob-considine-2014-thumbs.jpg" alt="Rob Considine" /></span><span class="accordian_s_wrap"><span class="accordion_title">Rob Considine<br />
    <span class="profile-position">Health Educator</span><br />
    </span><span class="accordion_description">Team Member Since: 2014</span></span><span class="accordion_readMore">&or;</span>
		<span class="dummy-close-x"><img src="media/wysiwyg/close-about-tabs.png" alt="Close" /></span>
	</h3>
	<div>
		<div class="accordion_image"><img src="media/about/rob-considine-2014-profile.jpg" alt="Rob Considine" /></div>
		<p><strong><em>How long have you worked for HHM?</em></strong> <br />
			I have worked for Mercy Health Weight Management since the end of January 2014.<br />
			<br />
			<strong><em>What is your educational background?</em></strong> <br />
			I have a B.S. in Clinical Exercise Science.<br />
			<br />
			<strong><em>What is the favorite part of your job?</em></strong> <br />
			I am very thankful for the opportunity to change a person's outlook on life. I enjoy educating people on risk factor management and improving their lifestyle. The absolute favorite part of my job would be seeing the passion in our patients while they fight for a healthier, better quality life.<br />
			<br />
			<strong><em>What are you passionate about?</em></strong> <br />
			I am passionate about being a true role model for a healthier lifestyle and bringing the best out of people. I am blessed with a wonderful wife and family. I am very passionate about being thankful for everything the good Lord has blessed upon you.<br />
			<br />
			<strong><em>What do you like to do for fun?</em></strong> <br />
			I love doing things outside. In Michigan our nice days are numbered, so I try to get my fill. I always love going for walks downtown. I am currently going for a second degree so there is not much time for fun. However, I always enjoy going to the in-laws for a day by the pool.<br />
			<strong><em>Why do you enjoy living in West Michigan?</em></strong> <br />
			West Michigan is a wonderful place. I live in Grand Rapids which is full of great opportunities for enjoyment. Some of these opportunities include a new farmers market, many 5k races and awesome bike trails to keep you busy. Running through the city at night is always a great time. Living in West Michigan, we also have the option of driving to Grand Haven for a beach day. Lake Michigan is so beautiful and relaxing. The winters take a little getting used to but they can be fun as well.<br />
			<br />
			Rob's Email: <a href="mailto:considrs@mercyhealth.com">considrs@mercyhealth.com</a></p>
	</div>
	<h3><span class="accordion_thumbnail"><img class="accordion_thumb" src="media/about/donna-welch-2014-thumbs.jpg" alt="Donnamarie Welch" /></span><span class="accordian_s_wrap"><span class="accordion_title">Donnamarie Welch<br />
    <span class="profile-position">Health Educator / Fitness Instructor</span><br />
    </span><span class="accordion_description"> Team Member Since: 2009</span></span><span class="accordion_readMore">&or;</span>
		<span class="dummy-close-x"><img src="media/wysiwyg/close-about-tabs.png" alt="Close" /></span>
	</h3>
	<div>
		<div class="accordion_image"><img src="media/about/donna-welch-2014-profile.jpg" alt="Donnamarie Welch" /></div>
		<p><strong><em>How long have you worked for HHM?</em></strong> <br />
			I have had the privilege to be a Health Educator/Program Support Specialist with Hackley Health Management since November 5, 2009. <br />
			<br />
			<strong><em>What is your educational background?</em></strong> <br />
			I have been involved with fitness and nutrition for the past 20 years with certifications as fitness instructor/personal trainer, nutrition educator, and massage therapist. <br />
			<br />
			<strong><em>What is the favorite part of your job?</em></strong> <br />
			Being a part of the team at Hackley Health Management gives me the opportunity to meet many people and help them achieve their weight loss goals. It is such a celebration when we see patients succeed and become vibrant, happy and HEALTHY!!! <br />
			<br />
			<strong><em>What are you passionate about?</em></strong> <br />
			I am very passionate about people being the very best that they can be, both physically and emotionally and always reaching for new accomplishments in life. If I can be a small part of making a big difference in someone's life, that's HUGE! <br />
			<br />
			<strong><em>What do you like to do for fun?</em></strong> <br />
			I love spending my time at, on or in Lake Michigan along with riding all the great bike trails in the area. I'm always up for trying the new fitness craze! <br />
			<br />
			Donna's Email: <a href="mailto:donna.welch@mercyhealth.com">donna.welch@mercyhealth.com</a></p>
	</div>
	<h3><span class="accordion_thumbnail"><img class="accordion_thumb" src="media/about/jennifer-pannucci-2014a-thumbs.jpg" alt="Jennifer Pannucci" /></span><span class="accordian_s_wrap"><span class="accordion_title">Jennifer Pannucci<br />
    <span class="profile-position">Program Coordinator</span><br />
    </span><span class="accordion_description">Team Member Since: 2013</span></span><span class="accordion_readMore">&or;</span>
		<span class="dummy-close-x"><img src="media/wysiwyg/close-about-tabs.png" alt="Close" /></span>
	</h3>
	<div>
		<div class="accordion_image"><img src="media/about/jennifer-pannucci-2014a-profile.jpg" alt="Jennifer Pannucci" /></div>
		<p><strong><em>How long have you worked for HHM?</em></strong> <br />
			I have worked for HHM since October 2013.<br />
			<br />
			<strong><em>What is your educational background?</em></strong> <br />
			After graduating from Alpena High School, I attended Alpena Community College for two years and then transferred to Western Michigan University.<br />
			<br />
			<strong><em>What is the favorite part of your job?</em></strong> <br />
			I am a people person!! The favorite part of my job is interacting with my co-workers and our patients.<br />
			<br />
			<strong><em>What are you passionate about?</em></strong> <br />
			I am passionate about my family. I love being a Mom to my daughter and two sons.<br />
			<br />
			<strong><em>What do you like to do for fun?</em></strong> <br />
			I love spending time with my family! In the summer we go boating and we like to ski in the winter. I also really enjoy watching all of my kids play sports.<br />
			<strong><em>Why do you enjoy living in West Michigan?</em></strong> <br />
			West Michigan is a beautiful place to live! We love to spend time at Lake Michigan and enjoy watching the seasons change. Every season brings something new to do and that brings so much variety to our family outings!<br />
			<br />
			Jennifer's Email: <a href="mailto:pannuccj@mercyhealth.com">pannuccj@mercyhealth.com</a></p>
	</div>
	<h3><span class="accordion_thumbnail"><img class="accordion_thumb" src="media/about/deborah-peabody-2014-thumbs.jpg" alt="Deborah Peabody" /></span><span class="accordian_s_wrap"><span class="accordion_title">Deborah Peabody<br />
    <span class="profile-position">Internet Commerce Coordinator</span><br />
    </span><span class="accordion_description"> Team Member Since: 2007</span></span><span class="accordion_readMore">&or;</span>
		<span class="dummy-close-x"><img src="media/wysiwyg/close-about-tabs.png" alt="Close" /></span>
	</h3>
	<div>
		<div class="accordion_image"><img src="media/about/deborah-peabody-2014-profile.jpg" alt="Deborah Peabody" /></div>
		<p><strong><em>How long have you worked for HHM?</em></strong> <br />
			Since June 4, 2007. <br />
			<br />
			<strong><em>What is your educational background?</em></strong> <br />
			I have an associates degree with a major in business and marketing. <br />
			<br />
			<strong><em>What is the favorite part of your job?</em></strong> <br />
			Some of our customers call to place their orders and while on the phone they share their success stories and you can hear the pride in their voices. It makes my day. <br />
			<br />
			<strong><em>What are you passionate about?</em></strong> <br />
			I'm passionate about the environment and how I interact in it and with others. <br />
			<br />
			<strong><em>What do you like to do for fun?</em></strong> <br />
			I enjoy backpacking and when I can't do that you can't beat our nature trails for long walks. <br />
			<br />
			<strong><em>Why do you enjoy living in Western Michigan?</em></strong> <br />
			Western Michigan is my home. I love the lakes and all the nature trails. You can't ask for a better back yard. I have traveled a bit and I am never disappointed in coming home. <br />
			<br />
			<a href="mailto:orders@hackleyhealthmanagement.com">orders@hackleyhealthmanagement.com</a></p>
	</div>
</div>
<script src="http://code.jquery.com/ui/1.9.2/jquery-ui.js"></script>
<script type="text/javascript">
	//<![CDATA[
	jQuery(function() {
		jQuery("#accordion").accordion({
			collapsible: true,
			autoHeight: false,
			active: false
		});
	});
	//]]>
</script>