<div id="patientSupportMaterials_header">
  <h3>Patient Support Materials</h3>
</div>
<div id="patientSupportMaterials_banner">
  <div id="patientSupportMaterials_label">
    <div id="patientSupportMaterials_caption">
      <h3>Watch This!<br />
        Fitness Tip</h3>
    </div>
    <div id="patientSupportMaterials_button">
      <p>More Support<br />
        Materials Below!</p>
    </div>
  </div>
  <div id="patientSupportMaterials_video">
    <iframe width="420" height="315" src="http://www.youtube.com/embed/A8nHxWJVxt8" frameborder="0" allowfullscreen></iframe>
  </div>
</div>
<div id="patientSupportMaterials_body">
  <div class="patientSupportMaterials_section"><a href="../media/patient-support-materials/bmiChart.pdf" target="_blank">BMI Chart</a>
    <p>Body Mass Index Chart</p>
  </div>
  <div class="patientSupportMaterials_section"><a href="../media/patient-support-materials/gsBookletWeb.pdf" target="_blank">Getting Started with Weight Loss</a>
    <p><span class="patientSupportMaterials_highlight">Your Guide to Weight Management</span><br />
      This handbook is a simple guide for individuals that are interested in weight loss and are looking for helpful hints to get started on their own.</p>
  </div>
  <div class="patientSupportMaterials_section"> <a href="http://www.hmrdiet.com/Succeed/WalkOMeter#Acct%28hackleyhealthmanagement%29;" target="_blank">Interactive Diet Tools</a>
    <p>Whether you want to lose weight, gain weight or maintain your current weight, we have designed clever weight management tools that can help you realize your personal goals.</p>
  </div>
  <div class="patientSupportMaterials_section"><a href="/success">HMR Success Stories</a>
    <p>Inspiring real life stories of HMR Success!</p>
  </div>
  <div class="patientSupportMaterials_section"><a target="_blank" href="http://www.hmrdiet.com/FAQs#Acct(hackleyhealthmanagement);">HMR FAQ</a>
    <p>HMR Commonly Asked Questions</p>
  </div>
</div>
