<?php
/**
 * Product list template
 *
 * @see Mage_Catalog_Block_Product_List
 */
?>
<?php
$_productCollection=$this->getLoadedProductCollection();
Mage::getModel('review/review')->appendSummary($_productCollection);
$_helper = $this->helper('catalog/output');
$helper = $this->helper('shoppersettings/image');

$imgX = 252;
$imgY = $helper->calculateHeight($imgX);
?>
<?php if($_productCollection->count()): ?>

<div class="category-products">
	<!--<div class="sales-banners-wrapper">
		<div class="blackfriday-banner-home"><a href="/black-friday"><img src="/media/blackfriday/2014/black-friday-home-banner.png" alt="Black Friday Sale Coming Soon!" /></a></div>
		<div class="cybermonday-banner-home"><a href="/cyber-monday"><img src="/media/cybermonday/2014/cyber-monday-home-banner.png" alt="Cyber Monday Sale Coming Soon!" /></a></div>
	</div>-->
  <h2><?php echo $this->__($this->getBlockTitle());?></h2>
  <?php $_collectionSize = $_productCollection->count(); ?>
  <ul class="products-grid">
<!--
Add At Home Program to Home Page!
-->
    <li class="item calc-price-box" style="height: 327px;">
      <div class="regular"><a class="product-image" title="HMR&reg; At Home Program" href="/hmr-at-home-program"> <img src="/media/categories/at-home-cat.jpg" alt="HMR&reg; At Home Program" /> </a> <a class="product-name" title="HMR&reg; At Home Program" href="/hmr-at-home-program">HMR&reg; At Home Program</a>
        <p class="shop-now-sub">Automatic food delivery, personalized support, &amp; extra savings!</p>
      </div>
      <div class="hover" style="display: none;"><a class="product-image" title="HMR&reg; At Home Program" href="/hmr-at-home-program"> <img width="252" height="252" alt="HMR&reg; At Home Program" data-srcx2="/media/categories/at-home-cat.jpg" src="/media/categories/at-home-cat.jpg"> </a> <a title="HMR&reg; At Home Program" href="/hmr-at-home-program" style="">
        <div class="price-box" style="opacity: 1; padding: 36px 15px; margin: -120px 0px 0px;"> <span id="product-price-0" class="regular-price"><span class="price">10<sup>%</sup> off</span></span></div>
        </a> <a class="product-name" title="HMR&reg; At Home Program" href="/hmr-at-home-program">HMR&reg; At Home Program</a>
        <div class="button-container">
          <p class="shop-now-sub" style="font-size:16px;text-transform:uppercase;"><strong>Free Shipping!</strong></p>
        </div>
        <span id="ajax_loading6" class="ajax_loading"> <img alt="ajax loader progress" src="/skin/frontend/default/shopper/images/ajax-loader.gif"> </span> 
        <ul class="add-to-links">
          <li>Customizable HMR&reg; Auto-Delivery Program</li>
        </ul>
      </div>
    </li>
<!--
End of At Home Program!
-->
    <?php foreach ($_productCollection as $_product): ?>
    <li class="item">
      <div class="regular"> <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>" class="product-image"> <?php echo $this->helper('shoppersettings')->getLabel($_product);  ?> <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($imgX, $imgY) ?>" data-srcX2="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($imgX*2, $imgY*2) ?>" width="<?php echo $imgX; ?>" height="<?php echo $imgY; ?>" alt="<?php echo $this->htmlEscape($_product->getName()) ?>" /> </a>
        <div class="button-container">
          <?php if($_product->isSaleable()): ?>
          <?php if (Mage::getStoreConfig('shoppersettings/ajax/cart')) : ?>
          <?php if ( !($_product->getTypeInstance(true)->hasRequiredOptions($_product) || $_product->isGrouped()) ) { ?>
          <p>
            <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart ajax-cart" data-url="<?php echo $this->getAddToCartUrl($_product); ?>" data-id="<?php echo $_product->getId(); ?>"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
          </p>
          <?php } else { ?>
          <p>
	          <?php
	          $productAttributeOptions = $_product->getTypeInstance(true)->getConfigurableAttributesAsArray($_product);
	          $attributeOptions = array();
	          foreach ($productAttributeOptions as $productAttribute) {
		          foreach ($productAttribute['values'] as $attribute) {
			          $attributeOptions[$productAttribute['label']] = '';
		          }
	          }
	          $optionString = implode(' & ', array_keys($attributeOptions));
	          ?>
            <button type="button" title="<?php echo $this->getAddToCartUrl($_product) ?>" class="button btn-cart show-options" data-id="<?php echo $_product->getId(); ?>"><span><span><?php echo 'Customize '.$optionString; ?></span></span></button>
          </p>
          <?php }  ?>
          <?php else: ?>
          <p>
            <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
          </p>
          <?php endif; ?>
          <?php else: ?>
          <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
          <?php endif; ?>
        </div>
        <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
        <a class="product-name" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a> <?php echo $this->getPriceHtml($_product, true) ?> </div>
      <div class="hover">
        <?php if (Mage::getStoreConfig('shoppersettings/ajax/cart')) : //quick view button ?>
        <a href='<?php echo $this->getUrl('ajax/index/options',array('product_id'=>$_product->getId()));?>' data-fancybox-group="gallery" class='fancybox quick-view' id='fancybox<?php echo $_product->getId()?>'><?php echo $this->__('quick view')?></a>
        <?php endif; ?>
        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>" class="product-image"> <?php echo $this->helper('shoppersettings')->getLabel($_product);  ?>
        <?php
                $back_img = $_product->getMediaGalleryImages()->getItemByColumnValue('label', 'back');
                if ( $back_img ) : ?>
        <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image', $back_img->getFile())->resize($imgX, $imgY) ?>" data-srcX2="<?php echo $this->helper('catalog/image')->init($_product, 'small_image', $back_img->getFile())->resize($imgX*2, $imgY*2) ?>" width="<?php echo $imgX; ?>" height="<?php echo $imgY; ?>" alt="<?php echo $this->htmlEscape($_product->getName()) ?>" />
        <?php else : ?>
        <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($imgX, $imgY) ?>" data-srcX2="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($imgX*2, $imgY*2) ?>" width="<?php echo $imgX; ?>" height="<?php echo $imgY; ?>" alt="<?php echo $this->htmlEscape($_product->getName()) ?>" />
        <?php endif; ?>
        </a> <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>"> <?php echo $this->helper('shoppersettings/data')->priceFormat( $this->getPriceHtml($_product, true) ); ?> </a>
        <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
        <a class="product-name" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a>
        <?php if($_product->getRatingSummary()){ echo $this->getReviewsSummaryHtml($_product); } ?>
		  <?php $symbols = $_product->getHealthSymbols();
			  $symbols = explode(',', $symbols);
		  ?>
		  <?php if (isset($symbols)) { ?>
			  <div class="health-symbols-wrap" style="text-align: center;">

				  <?php foreach($symbols as $symbol){
					  if (!empty($symbol)) {
						  if ($symbol == '99') {
							  $title =  "Kosher";
						  } elseif ($symbol == '98') {
							  $title =  "Gluten Free";
						  } elseif ($symbol == '97') {
							  $title =  "Vegetarian";
						  }
						  echo '<img class="health-symbol-icon" src="/media/health-symbols/'.$symbol.'.png" alt="'.$title.'" title="'.$title.'" />&nbsp;';

					  	}
				  	}
				  ?>
			  </div>
		  <?php }?>
        <div class="button-container">
          <?php if($_product->isSaleable()): ?>
          <?php if (Mage::getStoreConfig('shoppersettings/ajax/cart')) : ?>
          <?php if ( !($_product->getTypeInstance(true)->hasRequiredOptions($_product) || $_product->isGrouped()) ) { ?>
          <p>
            <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart ajax-cart" data-url="<?php echo $this->getAddToCartUrl($_product); ?>" data-id="<?php echo $_product->getId(); ?>"><span><span><em></em><?php echo $this->__('Add to Cart') ?></span></span></button>
          </p>
          <?php } else { ?>
          <p>
            <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart show-options" data-id="<?php echo $_product->getId(); ?>"><span><span><em></em><?php echo 'Customize '.$optionString; ?></span></span></button>
          </p>
          <?php }  ?>
          <?php else: ?>
          <p>
            <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><em></em><?php echo $this->__('Add to Cart') ?></span></span></button>
          </p>
          <?php endif; ?>
          <?php else: ?>
          <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
          <?php endif; ?>
        </div>
        <span class="ajax_loading" id='ajax_loading<?php echo $_product->getId()?>'><img alt="ajax loader progress" src='<?php echo $this->getSkinUrl('images/ajax-loader.gif')?>'/></span>
        <ul class="add-to-links">
          <?php if ($this->helper('wishlist')->isAllow()) : ?>
          <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist" data-id="<?php echo $_product->getId(); ?>"><span>+</span><?php echo $this->__('Add to Wishlist') ?></a></li>
          <?php endif; ?>
          <?php if ($_compareUrl=$this->getAddToCompareUrl($_product)) : ?>
          <li><a href="<?php echo $_compareUrl ?>" class="link-compare" data-id="<?php echo $_product->getId(); ?>"><span>+</span><?php echo $this->__('Add to Compare') ?></a></li>
          <?php endif; ?>
        </ul>
      </div>
    </li>
    <?php endforeach ?>
  </ul>
</div>
<?php endif; ?>
