<?php 

	  $resource = Mage::getSingleton('core/resource');
	  $readConnection = $resource->getConnection('core_read');

	  $orderId = $this->getRequest()->getParam('order_id'); 

	  $quoteitemid =  $readConnection->fetchOne('SELECT `quote_item_id` FROM `sales_flat_order_item` WHERE order_id='.$orderId);

         $orderDetails =  $readConnection->fetchAll('SELECT * FROM `sales_flat_quote_item` WHERE `item_id`='.$quoteitemid); 

        $allEntrees_result = $readConnection->fetchAll('SELECT * FROM custom_hmr_entrees');

        $first_product = Mage::getModel('catalog/product')->load($orderDetails[0]['product_id']);

       $hmr_product_2_week_product = $readConnection->fetchOne('SELECT `second_week_product_id` FROM `custom_hmr_product_2_week_product` WHERE product_id = ' . $orderDetails[0]['product_id']);

      $second_product = Mage::getModel('catalog/product')->load($hmr_product_2_week_product);

?>

<?php 
$firstprodoptions = explode(",", $orderDetails[0]['variety_entrees']);
$secondprodoptions = explode(",", $orderDetails[0]['subscribed_variety_entree']);
?>

<div>
         <ul>

<li><h3><?php echo $first_product->getName();?></h3></li>
            <?php foreach($allEntrees_result as $key=>$value){ ?>
                        <div <?php if(($key+1)%2!=0) { ?>class="entrees-left" <?php } else {?>class="entrees-right" <?php } ?> >   
                          <li style="overflow:hidden; margin:0 0 10px 0;" id="<?php echo $key;?>"> <div class="" style="float:left;"> <input type="checkbox" value="entree_<?php echo $value['entree_id'];?>" onclick="" id="chk_<?php echo $value['entree_id'];?>" />  Qty: 
                            <span> <input size="5" name="entree_<?php echo $value['entree_id'];?>" id="entree_<?php echo $value['entree_id'];?>" type="text" onblur="getCountEntrees();" value="<?php echo $firstprodoptions[$key]?>" class="varietyentree"> 
                            </span>
                          </div> 
<span style="float:left;"><?php echo $value['entree_name'];?></span></li>
                          </div>
                <?php } ?>

         </ul>
  </div>


<div>
         <ul>

<li><h3><?php echo $second_product->getName();?></h3></li>
            <?php foreach($allEntrees_result as $key=>$value){ ?>
                        <div <?php if(($key+1)%2!=0) { ?>class="entrees-left" <?php } else {?>class="entrees-right" <?php } ?> >   
                          <li style="overflow:hidden; margin:0 0 10px 0;" id="<?php echo $key;?>"> <div class="" style="float:left;"> <input type="checkbox" value="entree_<?php echo $value['entree_id'];?>" onclick="" id="chk_<?php echo $value['entree_id'];?>" />  Qty: 
                            <span> <input size="5" name="entree_<?php echo $value['entree_id'];?>" id="entree_<?php echo $value['entree_id'];?>" type="text" onblur="getCountEntrees();" value="<?php echo $secondprodoptions[$key];?>" class="varietyentree"> 
                            </span>
                          </div> 
<span style="float:left;"><?php echo $value['entree_name'];?></span></li>
                          </div>
                <?php } ?>

         </ul>
  </div>