<div id="beatTheHolidayWeightGain_header">
  <h3>Beat the Holiday Weight Gain Tradition</h3>
  <h4>Who says you have to gain weight over the holidays?</h4>
</div>
<div id="beatTheHolidayWeightGain_subHeader">
  <p>Delicious, low calorie HMR&#174; weight loss foods
    used as a meal replacement just a few times a day
    can save you thousands of calories each week.</p>
  <h6>They're a delicious and nutritious way to keep extra pounds away!</h6>
</div>
<div id="beatTheHolidayWeightGain_body">
  <div id="beatTheHolidayWeightGain_shakes">
    <h6>Meal Replacement Shakes</h6>
    <p>HMR&#174; 120</p>
    <ul>
      <li>120 calorie per serving</li>
      <li>11 grams of protein</li>
      <li>1.5 grams of fat</li>
    </ul>
    <p>HMR&#174; 500</p>
    <ul>
      <li>104 calorie per serving</li>
      <li>10 grams of protein</li>
      <li>.2 grams of fat</li>
    </ul>
    <p>HMR&#174; 70+ Lactose-Free</p>
    <ul>
      <li>104 calorie per serving</li>
      <li>12.6 grams of protein</li>
      <li>.2 grams of fat</li>
    </ul>
    <p>HMR&#174; 800</p>
    <ul>
      <li>160 calorie per serving</li>
      <li>16 grams of protein</li>
      <li>2 grams of fat</li>
    </ul>
    <p id="beatTheHolidayWeightGain_shakesFooter">Bonus: HMR&#174; shakes are loaded with calcium!</p>
  </div>
  <div id="beatTheHolidayWeightGain_entrees">
    <h6>Delicious, Low Calorie Entrees</h6>
    <p id="beatTheHolidayWeightGain_entreeIntro">Protein-packed HMR&#174; entrees have all the taste you crave without all of the calories. Mixed with vegetables, they're a quick and easy way to get your servings in! Averages just 200 calories.</p>
    <p>HMR&#174; Chicken Soup</p>
    <p class="beatTheHolidayWeightGain_listIntro">The Hot Alternative Meal Replacement</p>
    <ul>
      <li>102 calories per serving</li>
      <li>10 grams of protein</li>
      <li>1 gram of fat</li>
    </ul>
    <p>HMR BeneFit&#8482; Nutrition Bar</p>
    <p class="beatTheHolidayWeightGain_listIntro">35% of the USRDA in every bar</p>
    <ul>
      <li>160 calories per serving</li>
      <li>6 grams of protein</li>
      <li>5 gram of fat</li>
    </ul>
  </div>
</div>
<div id="beatTheHolidayWeightGain_footer">
  <h6>For easy ways to cut calories and increase nutrition, try:</h6>
  <ul>
    <li>a double shake for breakfast</li>
    <li>a shake w/ fruit added for breakfast</li>
    <li>a shake for lunch</li>
    <li>an all shake and entree day</li>
    <li>an all shake, vegetable, & fruit day</li>
    <li>a shake before going to a holiday party</li>
    <li>an entree w/ 2 cups of vegetables added for lunch or dinner</li>
    <li>a BeneFit&#174; Bar for a low-fat dessert</li>
    <li>a BeneFit&#174; Bar on the way home from work</li>
    <li>an entree and BeneFit&#174; bar for lunch</li>
  </ul>
</div>
