<div id="celebrateWithoutGaining_header">
  <h3>Celebrate Without Gaining Weight</h3>
</div>
<div id="celebrateWithoutGaining_body">
  <h3>Slimming Strategies for the Holiday Party Season</h3>
  <ul>
    <li>Sit or stand away from the food table</li>
    <li>During the party, walk around with a glass of diet soda or other low-calorie beverage to keep your hands occupied.</li>
    <li>Bring a low-fat food to the party.</li>
    <li>Fill your plate with only vegetables the first time through the buffet line.<br />
      (This will take the edge off your hunger and may result in choosing less high-fat items!)</li>
    <li>Eat a low-fat snack before you leave for the party<br />
      (i.e., toast with jam, fruit, baked potato with low-fat sour cream)</li>
    <li>Chew sugar-free gum or mints instead of food!</li>
    <li>Do some extra physical activity the day of the party (i.e., add a 20 minute walk to your routine).</li>
  </ul>
  <p>If you do indulge and overeat, don’t get discouraged.<br />
    Compensate by reducing your intake for a few days later that week to “balance” the extra calories.<br />
    <br />
    These ideas are from the weight management experts at:<br />
    Hackley Health Management<br />
    Muskegon, Michigan<br />
    (231)830-9684<br />
    1-800-521-9054</p>
</div>
<div id="celebrateWithoutGaining_footer">
  <p>Excerpts &#169; 2003 Health Management Resources Corporation, Boston, MA</p>
</div>
