<div id="consideringAtkins_header">
  <h3>Considering Atkins? Consider This...</h3>
</div>
<div id="consideringAtkins_body">
  <p>Data from the HMR&#174; Program for Weight Management&#8482; show greater weight loss than Atkins’ published results<span class="consideringAtkins_sup">1</span>!</p>
  <p id="consideringAtkins_data">HMR&#174; data:<br />
    25-50 pounds average weight loss in just 3-4 months<span class="consideringAtkins_sup">2</span></p>
  <ul>
    <li><span class="consideringAtkins_highlight">Lose weight with a research-based,</span> proven approach used by over 200 prestigious medical centers across the country</li>
    <li><span class="consideringAtkins_highlight">Options include: Rapid weight loss</span> under medical supervision, <span class="consideringAtkins_highlight">moderate weight loss</span> with Healthy Solutions&#174; or <span class="consideringAtkins_highlight">HMR at Home&#174;-classes by phone and meal replacements delivered to your door</span></li>
    <li><span class="consideringAtkins_highlight">In-depth lifestyle education, personalized attention, and intensive follow-up</span></li>
    <li><span class="consideringAtkins_highlight">Long-term maintenance program</span></li>
    <li>Program developed by Health Management Resources&#8482; (HMR&#174;), the nation’s leading provider of weight management programs to the medical community</li>
  </ul>
  <p id="consideringAtkins_footnotes"><span class="consideringAtkins_sup">1</span>Based on a survey of most recent available data<br />
    <span class="consideringAtkins_sup">2</span>Reported averages for patients in HMR's Healthy Solutions&#174; and medically supervised clinic programs</p>
</div>
<div id="consideringAtkins_footer">
  <p>Excerpts &#169; 2003 Health Management Resources Corporation, Boston, MA</p>
</div>
