<div id="dedicatedToYourHealth_header">
  <h3>Dedicated to Your Better Health</h3>
</div>
<div id="dedicatedToYourHealth_body">
  <p>Health Management Resources&#8482; (HMR&#174;) is a national health care company specializing in programs for weight and health management. HMR&#174;’s staff of health care professionals has provided programs for dietitians, nurses, psychologists, and exercise physiologists to establish more than 400 medically supervised weight management programs nationwide.<br />
    HMR&#174;’s wellness initiatives have provided treatment for more than 800,000 patients in medical settings, and thousands of employees in corporations. HMR&#174;’s expertise is in developing lifestyle-related weight loss programs and exceptional-tasting nutritional products for hospitals, medical centers, corporations, and individuals.<br />
    HMR&#174;’s medical research, weight loss, and weight maintenance data have been published in the Journal of the American Dietetic Association, American Journal of Gastroenterology, American Journal of Clinical Nutrition, New England Journal of Medicine, Journal of the American Medical Association, and Diabetes Care.<br />
    Many patients in HMR&#174; programs have experienced dramatic improvements in their overall health as a result of participating in the program and learning how to make sensible changes in diet and lifestyle.<br />
    Data from health risk appraisals of 1,000 “high risk” HMR&#174; patients show that while in the program, these patients experienced&#42;:</p>
  <ul>
    <li>REDUCED CANCER RISK</li>
    <li>64% decrease in the number of patients at high or very high risk for cancer</li>
    <li>REDUCED RISK FOR HEART DISEASE</li>
    <li>61% decrease in the number of patients at high or very high risk for heart disease</li>
  </ul>
  <p id="dedicatedToYourHealth_bodyFooter">&#42;HMR&#174; makes no claim that all participants will experience similar results or that such results are permanent.<br />
    Health Management Resources&#8482;<br />
    59 Temple Place, Suite 704<br />
    Boston, MA 02111<br />
    Phone: (617) 357-9876<br />
    Fax: (617) 357-9690<br />
    If you are interested in losing weight with the HMR&#174; Program for Weight Management&#8482; in your area, call: 1-800-418-1367 or click the Programs Page.<br />
    If you are interested in purchasing HMR&#174; foods and materials for personal use, call for a free mail order catalog: 1-800-418-1367.</p>
</div>
<div id="dedicatedToYourHealth_footer">
  <p>Excerpts &#169; 2003 Health Management Resources Corporation, Boston, MA</p>
</div>
