<div id="healthyFoodForYourFamily_header">
  <h3>HMR&#174; Healthy Solutions Quick Start&#8482; Diet Kit</h3>
  <p>The Healthy Solutions&#174; diet provides structure and convenience through the use of HMR&#174; meal replacements(shakes and entrees) along with five or more servings of vegetables and fruits daily.</p>
</div>
<div id="healthyFoodForYourFamily_body">
  <div class="healthyFoodForYourFamily_kits">
    <p>Healthy Solutions Quick Start&#8482; Intro Diet Kit (3 Week Supply)</p>
  </div>
  <div class="healthyFoodForYourFamily_images"> <img src="../media/health-articles/customizeYourKit.jpg" alt="Customize Your Kit" /> </div>
  <div class="healthyFoodForYourFamily_kits">
    <p>Healthy Solutions&#174; Quick Start&#8482; Intro Diet Kit (3 Week) Lactose Free</p>
  </div>
  <div class="healthyFoodForYourFamily_images"> <img src="../media/health-articles/customizeYourKit.jpg" alt="Customize Your Kit" /> </div>
  <div class="healthyFoodForYourFamily_kits">
    <p>Healthy Solutions Re-order Kit - (2 Week Supply)</p>
  </div>
  <div class="healthyFoodForYourFamily_images"> <img src="../media/health-articles/customizeYourKit.jpg" alt="Customize Your Kit" /> </div>
  <div class="healthyFoodForYourFamily_kits">
    <p>Healthy Solutions Re-order Kit - (2 Week) Lactose Free</p>
  </div>
  <div class="healthyFoodForYourFamily_images"> <img src="../media/health-articles/customizeYourKit.jpg" alt="Customize Your Kit" /> </div>
  <div class="healthyFoodForYourFamily_kits">
    <p>Healthy Solutions Re-order Kit - (4 Week Supply)</p>
  </div>
  <div class="healthyFoodForYourFamily_images"> <img src="../media/health-articles/customizeYourKit.jpg" alt="Customize Your Kit" /> </div>
  <div class="healthyFoodForYourFamily_kits">
    <p>Healthy Solutions Re-order Kit - (4 Week) Lactose Free</p>
  </div>
  <div class="healthyFoodForYourFamily_images"> <img src="../media/health-articles/customizeYourKit.jpg" alt="Customize Your Kit" /> </div>
</div>
