<div class="healthManagementResources_header">
  <h3>Health Management Resources&#8482; (HMR&#174;) Meal Replacements</h3>
</div>
<div class="healthManagementResources_subHeader">
  <h6>HMR&#174; Shakes and Entrees are the primary weight-loss tools used in all HMR&#174; Programs. They are used either on their own or in conjunction with fruits and vegetables (based on the program). HMR&#174; meal replacements and diet plans are nutritionally complete and provide high quality protein with low-fat intake.</h6>
</div>
<div id="healthManagementResources_ordered">
  <p>Meal replacements contribute to better compliance with weight-loss regimens because they are:</p>
  <ol>
    <li>Highly structured</li>
    <li>Satisfying and filling</li>
    <li>Portable and do not require refrigeration</li>
    <li>Convenient and can be prepared in less than 2 minutes</li>
    <li>Versatile (can be made in a variety of ways)</li>
  </ol>
</div>
<div id="healthManagementResources_unordered">
  <h6>Shakes/Soup</h6>
  <p>(100-170 calories per serving. Shakes available in chocolate and vanilla.)</p>
  <ul>
    <li>HMR&#174; 120 Shake</li>
    <li>HMR&#174; 500 Shake and</li>
    <li>HMR&#174; 500 Chicken Soup</li>
    <li>HMR&#174; 70 Plus Shake<br />
      (lactose-free shakes and puddings)</li>
    <li>HMR&#174; 800 Shake</li>
  </ul>
</div>
<div id="healthManagementResources_unordered">
  <h6>Entrees</h6>
  <p>(140-270 calories per serving.)</p>
  <ul>
    <li>Chicken Pasta Parmesan</li>
    <li>Mexican Style Bean and Beef Enchiladas</li>
    <li>Chicken Creole</li>
    <li>Chicken with Barbecue Sauce</li>
    <li>Cheese and Basil Ravioli in Tomato Sauce</li>
    <li>Five Bean Casserole</li>
    <li>Lasagna with Meat Sauce</li>
    <li>Mushroom Risotto</li>
    <li>Savory Chicken</li>
    <li>Turkey Chili with Beans</li>
    <li>Vegetable Stew with Beef</li>
  </ul>
</div>
<div id="healthManagementResources_unordered">
  <h6>BeneFit Bars&#174;</h6>
  <p>(150-160 calories per serving.)</p>
  <ul>
    <li>Peanut Butter</li>
    <li>Honey Graham</li>
    <li>Blueberry</li>
    <li>Oatmeal Raisin</li>
  </ul>
</div>
<div class="healthManagementResources_footer">
  <p><em>HMR&#174; Shakes and nutrition bars are, Kosher approved by established rabbinical associations.</em></p>
</div>
