<div id="container" class="cf">
  <div id="main" role="main">
    <section class="slider">
      <div class="flexslider health-articles">
        <ul class="slides">
          <li><a href="../media/health-articles/HMR_orientation.pdf" target="_blank"><img src="http://hhm.next-it.net/media/health-articles/placeholder1.jpg" alt="Fall 2012" /></a> </li>
          <li> <img src="http://hhm.next-it.net/media/health-articles/placeholder2.jpg" alt="Spring 2012" /> </li>
          <li> <img src="http://hhm.next-it.net/media/health-articles/placeholder3.jpg" alt="Spring 2011" /> </li>
        </ul>
      </div>
    </section>
  </div>
  <div id="health-articles_thumbnails">
    <div class="health-articles_row">
      <div class="health-articles_issue">
        <h3><a href="/health-articles/hmr-at-home-174-meal-replacement-for-special-diet-issues">HMR at Home Meal Replacement</a></h3>
        <a href="/health-articles/hmr-at-home-174-meal-replacement-for-special-diet-issues"><img src="../media/health-articles/HMR-at-Home-Meal-Replacement-for-Special-Diet-Issues.jpg" alt="HMR at Home Meal Replacement for Special Diet Issues" /></a></div>
      <div class="health-articles_issue health-articles_middle">
        <h3><a href="/health-articles/managing-your-diabetes-the-basics">Managing Your Diabetes</a></h3>
        <a href="/health-articles/managing-your-diabetes-the-basics"><img src="../media/health-articles/Managing-Your-Diabetes---the-basics.jpg" alt="Managing Your Diabetes" /></a></div>
      <div class="health-articles_issue">
        <h3><a href="/health-articles/health-management-resources">Health Management Resources</a></h3>
        <a href="/health-articles/health-management-resources"><img src="../media/health-articles/Health-Management-Resources-HMR-Meal-Replacements.jpg" alt="Health Management Resources" /></a></div>
    </div>
    <div class="health-articles_row">
      <div class="health-articles_issue">
        <h3><a href="http://www.hmrdiet.com/FAQs#Acct(hackleyhealthmanagement);" target="_blank">Health Management Resources</a></h3>
        <a href="http://www.hmrdiet.com/FAQs#Acct(hackleyhealthmanagement);" target="_blank"><img src="../media/health-articles/Health-Management-Resources-FAQs.jpg" alt="Winter2009" /></a></div>
      <div class="health-articles_issue health-articles_middle">
        <h3><a href="/health-articles/10-tips-to-weight-loss-success">10 Tips to Weight-Loss Success</a></h3>
        <a href="/health-articles/10-tips-to-weight-loss-success"><img src="../media/health-articles/10-Tips-to-Weight-Loss-Success.jpg" alt="10 Tips to Weight-Loss Success" /></a></div>
      <div class="health-articles_issue">
        <h3><a href="/health-articles/party-without-gaining-weight">Party Without Gaining Weight!</a></h3>
        <a href="/health-articles/party-without-gaining-weight"><img src="../media/health-articles/Its-Possible-to-Party-Without-Gaining-Weight.jpg" alt="It's Possible to Party Without Gaining Weights!" /></a></div>
    </div>
    <div class="health-articles_row">

      <div class="health-articles_issue">
        <h3><a href="/health-articles/beat-the-holiday-weight-gain">Beat the Holiday Weight Gain</a></h3>
        <a href="/health-articles/beat-the-holiday-weight-gain"><img src="../media/health-articles/Beat-the-Holiday-Weight-Gain-Tradition.jpg" alt="Beat the Holiday Weight Gain Tradition" /></a></div>
      <div class="health-articles_issue health-articles_middle">
        <h3><a href="/health-articles/power-of-meal-replacements">POWER of Meal Replacements</a></h3>
        <a href="/health-articles/power-of-meal-replacements"><img src="../media/health-articles/The-POWER-of-Meal-Replacements-IN-ACTION.jpg" alt="The POWER of Meal Replacements IN ACTION" /></a></div>
      <div class="health-articles_issue">
        <h3><a href="/health-articles/healthy-food-for-your-family">Healthy Food for Your Family</a></h3>
        <a href="/health-articles/healthy-food-for-your-family"><img src="../media/health-articles/Creating-Healthy-Food-Environments-for-Your-Family.jpg" alt="Creating Healthy Food Environments for Your Family" /></a></div>
    </div>
    <div class="health-articles_row">

      <div class="health-articles_issue">
        <h3><a href="/health-articles/substitutions-for-weight-loss">Substitutions for Weight Loss</a></h3>
        <a href="/health-articles/substitutions-for-weight-loss"><img src="../media/health-articles/Winning-Substitutions-for-Weight-Loss.jpg" alt="Winning Substitutions for Weight Loss" /></a></div>
      <div class="health-articles_issue health-articles_middle">
        <h3><a href="/health-articles/like-no-other-program">Like No Other Program</a></h3>
        <a href="/health-articles/like-no-other-program"><img src="../media/health-articles/Like-No-Other-Weight-Loss-Program.jpg" alt="Like No Other Weight Loss Program" /></a></div>
      <div class="health-articles_issue">
        <h3><a href="/health-articles/dedicated-to-your-health">Dedicated to Your Health</a></h3>
        <a href="/health-articles/dedicated-to-your-health"><img src="../media/health-articles/Dedicated-to-Your-Better-Health.jpg" alt="Dedicated to Your Better Health" /></a></div>
    </div>
    <div class="health-articles_row">

      <div class="health-articles_issue">
        <h3><a href="../media/health-articles/bmichart.pdf" target="_blank">BMI Chart</a></h3>
        <a href="../media/health-articles/bmichart.pdf" target="_blank"><img src="../media/health-articles/BMI-Chart-pdf.jpg" alt="BMI Chart" /></a></div>
      <div class="health-articles_issue health-articles_middle">
        <h3><a href="/health-articles/51-ways-to-get-more-exercise">51 WAYS TO GET MORE EXERCISE</a></h3>
        <a href="/health-articles/51-ways-to-get-more-exercise"><img src="../media/health-articles/51-WAYS-TO-GET-MORE-EXERCISE.jpg" alt="51 WAYS TO GET MORE EXERCISE" /></a></div>
      <div class="health-articles_issue">
        <h3><a href="/health-articles/celebrate-without-gaining">Celebrate Without Gaining</a></h3>
        <a href="/health-articles/celebrate-without-gaining"><img src="../media/health-articles/Celebrate-Without-Gaining-Weight.jpg" alt="Celebrate Without Gaining Weight" /></a></div>
    </div>
    <div class="health-articles_row">

      <div class="health-articles_issue">
        <h3><a href="/health-articles/considering-atkins">Considering Atkins?</a></h3>
        <a href="/health-articles/considering-atkins"><img src="../media/health-articles/Considering-Atkins.jpg" alt="Considering Atkins?" /></a></div>
      <div class="health-articles_issue health-articles_middle">
        <h3><a href="/health-articles/successful-weight-management">Successful Weight Management</a></h3>
        <a href="/health-articles/successful-weight-management"><img src="../media/health-articles/Steps-for-Successful-Weight-Management.jpg" alt="Steps for Successful Weight Management" /></a></div>
    </div>
  </div>
</div>

<!-- jQuery -->
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="js/libs/jquery-1.7.min.js">\x3C/script>')</script>

<!-- FlexSlider -->
<script defer src="http://hhm.next-it.net/skin/frontend/default/shopper/js/jquery.flexslider.js"></script>
<script type="text/javascript">
  $(function(){
    SyntaxHighlighter.all();
  });
  $(window).load(function(){
    $('.flexslider').flexslider({
      animation: "slide",
      start: function(slider){
        $('body').removeClass('loading');
      }
    });
  });
</script>

<!-- Syntax Highlighter -->
<script type="text/javascript" src="http://hhm.next-it.net/skin/frontend/default/shopper/js/shCore.js"></script>
<script type="text/javascript" src="http://hhm.next-it.net/skin/frontend/default/shopper/js/shBrushXml.js"></script>
<script type="text/javascript" src="http://hhm.next-it.net/skin/frontend/default/shopper/js/shBrushJScript.js"></script>

<!-- Optional FlexSlider Additions -->
<script src="http://hhm.next-it.net/skin/frontend/default/shopper/js/jquery.easing.js"></script>
<script src="http://hhm.next-it.net/skin/frontend/default/shopper/js/jquery.mousewheel.js"></script>
<script defer src="http://hhm.next-it.net/skin/frontend/default/shopper/js/demo.js"></script>