<div class="hmrAtHome_header">
  <h3>HMR at Home&#174; Meal Replacement for Special Diet Issues</h3>
</div>
<div class="hmrAtHome_table">
  <table border="1">
    <thead>
      <tr>
        <th>HMR&#174; Products</th>
        <th>Gluten-free diet (Celiac Disease)</th>
        <th>Purine-restricted Diet (Gout)&#42;</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>Turkey Chili</td>
        <td>X</td>
        <td>Square</td>
      </tr>
      <tr>
        <td>Savory Chicken</td>
        <td>X</td>
        <td>Circle</td>
      </tr>
      <tr>
        <td>Five Bean Casserole</td>
        <td>Circle</td>
        <td>Square</td>
      </tr>
      <tr>
        <td>Chicken with BBQ Sauce</td>
        <td>Circle</td>
        <td>Circle</td>
      </tr>
      <tr>
        <td>Chicken Pasta Parmesan</td>
        <td>X</td>
        <td>Circle</td>
      </tr>
      <tr>
        <td>Chicken Creole with Brown Rice</td>
        <td>Circle</td>
        <td>Circle</td>
      </tr>
      <tr>
        <td>Beef &#38; Bean Enchilada</td>
        <td>X</td>
        <td>Square</td>
      </tr>
      <tr>
        <td>Vegetable Beef Stew</td>
        <td>X</td>
        <td>Square</td>
      </tr>
      <tr>
        <td>HMR&#174; 120 Shakes</td>
        <td>Circle</td>
        <td>Circle</td>
      </tr>
      <tr>
        <td>HMR&#174; 70 Shakes</td>
        <td>Circle</td>
        <td>Circle</td>
      </tr>
      <tr>
        <td>HMR&#174; 500 Shakes</td>
        <td>Circle</td>
        <td>Circle</td>
      </tr>
      <tr>
        <td>HMR&#174; 800 Shakes</td>
        <td>Circle</td>
        <td>Circle</td>
      </tr>
      <tr>
        <td>HMR BeneFit&#174; Bars - Honey Graham</td>
        <td>Circle</td>
        <td>Square</td>
      </tr>
      <tr>
        <td>HMR BeneFit&#174; Bars - Peanut Butter</td>
        <td>X</td>
        <td>Square</td>
      </tr>
      <tr>
        <td>HMR&#174; 500 Chicken Soup</td>
        <td>X</td>
        <td>Square</td>
      </tr>
      <tr>
        <td>HMR&#174; Vitamins</td>
        <td>Circle</td>
        <td>Square</td>
      </tr>
    </tbody>
    <tfoot>
      <tr>
        <td>Circle - May be used with out restriction</td>
        <td>X - May NOT be used at all</td>
        <td>May be used with some restrictions</td>
      </tr>
    </tfoot>
  </table>
</div>
