<div id="likeNoOtherProgram_header">
  <h3>Like No Other Weight Loss Program</h3>
</div>
<div id="likeNoOtherProgram_body">
  <div id="likeNoOtherProgram_article">
    <p>Whether you have 200 pounds to lose or just 10, we can help.<br />
      More than just a diet, the HMR&#174; Program will provide you with lifelong skills for your health and weight management.</p>
  </div>
  <div id="likeNoOtherProgram_aside">
    <h3>Published Results Show</h3>
    <h6>62 lbs.</h6>
    <p>Average Weight Loss for patients after 21 weeks on the HMR&#174; very low calorie diet program. Data collected from three groups of patients treated at the HMR&#174; Program, University of Kentucky. HMR&#174;'s medical research, weight loss, and weight maintenance data have been published in several leading medical and nutritional journals. HMR&#174; makes no claim that the results are representative of all patients in the HMR&#174; Program.</p>
    <p id="likeNoOtherProgram_asideFooter">These data include some patients that participated in maintenance during the two-year period. For many dieters, weight-loss is temporary.</p>
  </div>
  <div id="likeNoOtherProgram_list">
    <ul>
      <li>Specializing in rapid and significant weight loss</li>
      <li>A variety of dieting options available</li>
      <li>Offered in hospitals and medical centers nationwide</li>
      <li>Weekly classes teach the specific "how to's" for successful weight management</li>
      <li>Personal weight loss coaches provide support and encouragement</li>
      <li>Extensive maintenance program</li>
    </ul>
    <p>If you're ready to lose weight and improve your health, contact us today</p>
  </div>
</div>
<div id="likeNoOtherProgram_footer">
  <p>Excerpts &#169; 2003 Health Management Resources Corporation, Boston, MA</p>
</div>
