<h3>Managing Your Diabetes - the basics</h3>
<div class="managingYourDiabetes-wrapper">
  <div class="managingYourDiabetes-item no-border">
    <h3>Managing Your Diabetes – the basics<br />
      The Importance of Glucose Control</h3>
    <p>Diabetes can lead to other problems such as heart disease or stroke, nerve damage or eye damage. Keeping your blood sugar under control can prevent these problems.</p>
  </div>
  <div class="managingYourDiabetes-item">
    <h3>The GlycoHemoglobin or A1C Test</h3>
    <p>This is a blood test that measures your average blood sugar for the past two to three months.</p>
  </div>
  <div class="managingYourDiabetes-item">
    <h3>The Importance of an Eye Exam</h3>
    <p>People with diabetes need to have their eyes dilated every year to check for any damage. Early detection of eye problems can help to preserve your eyesight.</p>
  </div>
  <div class="managingYourDiabetes-item">
    <h3>The Importance of a Foot Exam</h3>
    <p>Diabetes can cause nerve damage or problems with blood flow to your legs and feet. Ask your doctor to examine your feet to check for any problems. Keep your feet clean and dry. Do not walk barefoot.</p>
  </div>
  <div class="managingYourDiabetes-item">
    <h3>The MicroAlbuminuria Test</h3>
    <p>This is a lab test to monitor your kidney function. It is very important to have this test done every year to take good care of your kidneys.</p>
  </div>
  <div class="managingYourDiabetes-item">
    <h3>Blood Pressure Control is Important</h3>
    <p>High blood pressure can cause stress or damage to your heart, and may lead to a stroke. Diabetes increases your risks for these problems, so it is very important for your blood pressure to be controlled.</p>
  </div>
  <div class="managingYourDiabetes-item">
    <h3>Cholesterol Control</h3>
    <p>High cholesterol can also lead to heart disease and stroke. It is very important for you to have a blood test to check your "good" and "bad" cholesterol. Your doctor may advise you to change your diet, exercise more, or use a medication to help control your cholesterol.</p>
  </div>
  <div class="managingYourDiabetes-item">
    <h3>Diabetes Education</h3>
    <p>A diabetes education program can help you to understand diabetes and take better care of yourself. An education program will help you plan your meals, and teach you what to do if you are sick. You will also learn how to monitor your blood sugar level at home. This will help your doctor to manage your diabetes. Medicare and most other health insurance plans will pay for diabetes education.</p>
  </div>
  <h3>Hackley Resources</h3>
  <div class="managingYourDiabetes-item">
    <h4>Education</h4>
    <p>Hackley Hospital Diabetes Self-Management Program<br />
      231.728.4810<br />
      Hackley Lakeshore Hospital</p>
    <h4>Diabetes Program</h4>
    <p>231.861.3018</p>
  </div>
  <div class="managingYourDiabetes-item">
    <h4>Home Monitors</h4>
    <p>Hackley Healthcare Equipment<br />
      231.728.5711<br />
      <a target="_blank" href="http://www.hackleyhme.com/">www.hackleyhme.com</a></p>
  </div>
  <div class="managingYourDiabetes-item">
    <h4>Home Care</h4>
    <p>Hackley Visiting Nurse Services<br />
      231.726.5025</p>
  </div>
  <div class="managingYourDiabetes-item">
    <h4>Weight Management</h4>
    <p>Hackley Health Management<br />
      231.830.9684<br />
      <a target="_blank" href="http://www.hackleyhealthmanagement.com/">www.hackleyhealthmanagement.com</a></p>
  </div>
  <div class="managingYourDiabetes-item">
    <h4>Medication &#38; Supplies</h4>
    <p>Hackley Pharmacies<br />
      231.728.5880<br />
      <a target="_blank" href="http://www.hackleyrx.com/">www.hackleyrx.com</a></p>
  </div>
  <div class="managingYourDiabetes-item">
    <h4>Diabetic Footwear &#38; Inserts</h4>
    <p>Hackley Orthotics &#38; Prosthetics<br />
      231.726.5025</p>
  </div>
  <div class="managingYourDiabetes-item">
    <h4>Support Groups</h4>
    <p>Diabetes Education &#38; Support, Inc.<br />
      231.798.7777</p>
  </div>
  <h3>Online Resources</h3>
  <div class="managingYourDiabetes-item">
    <h4>American Diabetes Association</h4>
    <p><a target="_blank" href="http://www.diabetes.org/">www.diabetes.org</a></p>
  </div>
  <div class="managingYourDiabetes-item">
    <h4>Centers for Disease Control</h4>
    <p><a target="_blank" href="http://www.cdc.gov/diabetes">www.cdc.gov/diabetes</a></p>
  </div>
  <div class="managingYourDiabetes-item">
    <h4>Hackley Hospital</h4>
    <p><a target="_blank" href="http://www.hackley.org/">www.hackley.org </a></p>
  </div>
  <div class="managingYourDiabetes-item">
    <h4>National Institutes of Health</h4>
    <p><a target="_blank" href="http://www.niddk.nih.gov/">www.niddk.nih.gov</a></p>
  </div>
  <div class="managingYourDiabetes-item">
    <h4>National Eye Institute</h4>
    <p><a target="_blank" href="http://www.nei.nih.gov/">www.nei.nih.gov</a></p>
  </div>
  <div class="managingYourDiabetes-item">
    <h4>National Kidney Foundation</h4>
    <p><a target="_blank" href="http://www.kidney.org/">www.kidney.org</a></p>
  </div>
  <div class="managingYourDiabetes-item">
    <h4>Medicare</h4>
    <p><a target="_blank" href="http://www.medicare.gov/">www.medicare.gov</a></p>
  </div>
  <div class="managingYourDiabetes-item">
    <h4>Juvenile Diabetes Research</h4>
    <p><a target="_blank" href="http://www.jdf.org/">www.jdf.org</a></p>
  </div>
  <div class="managingYourDiabetes-item">
    <h4>Diabetes Exercise &#38; Sports</h4>
    <p><a target="_blank" href="http://www.diabetes-exercise.org/">www.diabetes-exercise.org</a></p>
  </div>
</div>
