<div id="partyWithoutGainingWeight_header">
  <h3>It's Possible to Party Without Gaining Weight!</h3>
</div>
<div class="partyWithoutGainingWeight_subHeader">
  <p>HMR&#174; meal replacements can help you survive the social season while protecting your health and weight goals. All HMR#&174; meal replacements are available to former patients, their friends, and family members!</p>
</div>
<div id="partyWithoutGainingWeight_body">
  <div id="partyWithoutGainingWeight_shakes">
    <div class="partyWithoutGainingWeight_sectionHeader">
      <h6>Try these popular holiday shake recipes.</h6>
    </div>
    <div id="partyWithoutGainingWeight_shakesLeft">
      <h6>Creamy Eggnog</h6>
      <p>2/3 cup cold water<br />
        1 packet HMR&#174; 500&#42; Vanilla<br />
        1/4 teaspoon vanilla extranct<br />
        1/4 teaspoon rum or brandy extract<br />
        1/4 teaspoon nutmeg<br />
        4-6 ice cubes<br />
        <em>Calories: 109</em></p>
    </div>
    <div id="partyWithoutGainingWeight_shakesCenter">
      <h6>Pumpkin Pie</h6>
      <p>3/4 cup cold water<br />
        1 packet HMR&#174; 500&#42; Vanilla<br />
        1 teaspoon pumpkin pie spice<br />
        4-6 ice cubes<br />
        <em>Calories: 111</em></p>
    </div>
    <div id="partyWithoutGainingWeight_shakesRight">
      <h6>Vermont Maple Magic</h6>
      <p>1/2 cup cold water<br />
        1 packet HMR&#174; 500&#42; Vanilla<br />
        1 teaspoon maple extract<br />
        1/8 teaspoon cinnamon<br />
        4-6 ice cubes<br />
        <em>Calories: 111</em></p>
    </div>
    <div class="partyWithoutGainingWeight_sectionFooter">
      <p>&#42; HMR&#174; 800, HMR&#174; 70 Plus, or HMR&#174 120 may be substituted. Adjust calories accordingly.</p>
    </div>
  </div>
  <div id="partyWithoutGainingWeight_meals">
    <div class="partyWithoutGainingWeight_sectionHeader">
      <h6>Or, try these warm and filling recipes.</h6>
    </div>
    <div id="partyWithoutGainingWeight_mealsLeft">
      <h6>Two Carat: Turkey Chili</h6>
      <p>1 HMR&#174; Turkey Chili w/ Beans Entree<br />
        2 cups chopped carrots<br />
        <br />
        Microwave carrots until soft (3-4 minutes). Drain excess water.<br />
        Stir in Entree. Reheat until warm.<br />
        <em>Calories: 320</em><br />
        <em>Vegetable Servings: 3 </em></p>
    </div>
    <div id="partyWithoutGainingWeight_mealsRight">
      <h6>Velvet Chicken &#38; Vegetables</h6>
      <p>1 packet HMR&#174; Chicken Soup<br />
        1/4 cup water (more or less to taste)<br />
        2 cups frozen vegetables or a 16oz. can of mixed vegetables, drained<br />
        <br />
        In a mug or small bowl, add the hot water to the HMR Chicken Soup. Heat vegetables.<br />
        Drizzle soup over vegetables.<br />
        <em>Calories: 225</em> <em>Vegetable Servings: 2</em></p>
    </div>
  </div>
</div>
