<div id="powerOfMealReplacements_header">
  <h3>The POWER of Meal Replacements IN ACTION</h3>
  <h6>What Could You Do in a Day? A LOT!</h6>
</div>
<div id="powerOfMealReplacements_body">
  <p>By substituting an HMR&#174; meal replacement for a "typical" meal, you could save hundreds of calories, and not even realize it. Add in a few other meal replacements, and you've got the beginnings of a great weight loss or weight maintenance plan.</p>
  <img src="../media/health-articles/powerOfMealReplacements.jpg" alt="Power of Meal Replacements" />
  <p>Total Savings: 2,820 calories. That’s the equivalent of walking 28 miles!</p>
</div>
<div id="powerOfMealReplacements_footer">
  <p>Excerpts &#169; 2003 Health Management Resources Corporation, Boston, MA</p>
</div>
