<div id="substitutionsForWeightLoss_header">
  <h3>Winning Substitutions for Weight Loss</h3>
</div>
<div id="substitutionsForWeightLoss_body">
  <div class="substitutionsForWeightLoss_section">
    <h3>If you currently eat a donut for breakfast every morning:</h3>
    <div class="substitutionsForWeightLoss_instead">
      <p>Instead of:</p>
      <p>1 plain donut</p>
    </div>
    <div class="substitutionsForWeightLoss_try">
      <p>Just 2 days a week, try</p>
      <p>2 slices of toast with jam</p>
    </div>
    <div class="substitutionsForWeightLoss_lose">
      <p>You'll lose approximately</p>
      <p>5.1 pounds over the course of a year!</p>
    </div>
  </div>
  <div class="substitutionsForWeightLoss_section">
    <h3>If a muffin is your breakfast item of choice:</h3>
    <div class="substitutionsForWeightLoss_instead">
      <p>Instead of:</p>
      <p>1 5-oz muffin</p>
    </div>
    <div class="substitutionsForWeightLoss_try">
      <p>Just 2 days a week, try</p>
      <p>1 cup oatmeal, 1 banana, 1/2 cup skim milk</p>
    </div>
    <div class="substitutionsForWeightLoss_lose">
      <p>You'll lose approximately</p>
      <p>6.5 pounds over the course of a year!</p>
    </div>
  </div>
  <div class="substitutionsForWeightLoss_section">
    <h3>If you like to snack - and you currently eat 3 or 4 handfuls of nuts a day:</h3>
    <div class="substitutionsForWeightLoss_instead">
      <p>Instead of:</p>
      <p>1 cup of peanuts</p>
    </div>
    <div class="substitutionsForWeightLoss_try">
      <p>Just 2 days a week, try</p>
      <p>17 cups of air popped popcorn (no butter)</p>
    </div>
    <div class="substitutionsForWeightLoss_lose">
      <p>You'll lose approximately</p>
      <p>12.5 pounds over the course of a year!</p>
    </div>
  </div>
  <div class="substitutionsForWeightLoss_section">
    <h3>If you're more likely to snack on a chocolate bar:</h3>
    <div class="substitutionsForWeightLoss_instead">
      <p>Instead of:</p>
      <p>1 chocolate bar</p>
    </div>
    <div class="substitutionsForWeightLoss_try">
      <p>Just 2 days a week, try</p>
      <p>1 HMR&#174; Benefit&#174; Bar</p>
    </div>
    <div class="substitutionsForWeightLoss_lose">
      <p>You'll lose approximately</p>
      <p>3.5 pounds over the course of a year!</p>
    </div>
  </div>
  <div class="substitutionsForWeightLoss_section">
    <h3>If you love deli sandwiches for lunch:</h3>
    <div class="substitutionsForWeightLoss_instead">
      <p>Instead of:</p>
      <p>1 roast beef on white bread with mayo and cheese</p>
    </div>
    <div class="substitutionsForWeightLoss_try">
      <p>Just 2 days a week, try</p>
      <p>1 turkey on white bread with lettuce, tomato and mustard</p>
    </div>
    <div class="substitutionsForWeightLoss_lose">
      <p>You'll lose approximately</p>
      <p>18.5 pounds over the course of a year!</p>
    </div>
  </div>
  <div class="substitutionsForWeightLoss_section">
    <h3>If you think a tuna salad is a healthy choice:</h3>
    <div class="substitutionsForWeightLoss_instead">
      <p>Instead of:</p>
      <p>1 tuna salad sandwich</p>
    </div>
    <div class="substitutionsForWeightLoss_try">
      <p>Just 2 days a week, try</p>
      <p>1 HMR&#174; Shake mixed with strawberries and a banana</p>
    </div>
    <div class="substitutionsForWeightLoss_lose">
      <p>You'll lose approximately</p>
      <p>18 pounds over the course of a year!</p>
    </div>
  </div>
</div>
<div id="substitutionsForWeightLoss_footer">
  <p>This information is not intended to diagnose medical problems or substitute for appropriate medical care. Consult your physician before starting any diet.</p>
  <p>Excerpts &#169; 2003 Health Management Resources Corporation, Boston, MA</p>
</div>
