<div id="successfulWeightManagement_header">
  <h3>Steps for Successful Weight Management</h3>
</div>
<div id="successfulWeightManagement_body">
  <div class="successfulWeightManagement_section">
    <h3>Step 1: Put the Commitments in Place</h3>
    <ul>
      <li>Attend weekly and make your midweek phone call</li>
      <li>Keep daily records on the Weekly Summary Form (WSF)</li>
    </ul>
    <p>The Program Commitments are the necessary starting place for partnership and coaching.</p>
  </div>
  <div class="successfulWeightManagement_section">
    <h3>Step 2: Practice the Triple Imperative&#174;</h3>
    <p>Consistently meet or exceed the minimum goals every week</p>
    <ul>
      <li>14 meal replacements</li>
      <li>35 servings of vegetables and fruits</li>
      <li>2,000 calories of physical activity</li>
    </ul>
  </div>
  <div id="successfulWeightManagement_add">
    <p>If you are not fully achieving your weight-management goals, add the following three steps:</p>
  </div>
  <div class="successfulWeightManagement_section">
    <h3>Step 3: “Overpractice” the Triple Imperative&#174;</h3>
    <p>Establish higher minimum goals on one or more of the Imperatives. Remember, More is Better&#8482;! (Note: If there’s a question about which Imperative to target, start with meal replacements. Meal replacements are your most effective tool for displacing calories.)</p>
  </div>
  <div class="successfulWeightManagement_section">
    <h3>Step 4: Plan Decision Free&#8482; “In the Box” Days</h3>
    <p>Plan “in the box” days (minimum 3 HMR&#174; Shakes, 2 HMR&#174; Entrees, 5 servings of vegetables and fruits with no other foods—more is better!) to further structure your eating and reduce calorie intake.</p>
  </div>
  <div class="successfulWeightManagement_finally">
    <h3>Finally, to further support your weight-management efforts:</h3>
    <ul>
      <li>Use the HMR Calorie SystemSM to make food choices that can help reduce your overall calorie.</li>
      <li>Make specific environmental control plans, which may require time-limited food record analysis.</li>
    </ul>
  </div>
</div>
<div id="successfulWeightManagement_footer">
  <p>Excerpts © 2003 Health Management Resources Corporation, Boston, MA</p>
</div>
