<div class="tipsToWeightLossSuccess_header">
  <h3>10 Tips to Weight-Loss Success</h3>
</div>
<div class="tipsToWeightLossSuccess_body">
  <div class="tipsToWeightLossSuccess_subHeading">
    <h6>Choose a plan that makes sense</h6>
  </div>
  <div class="tipsToWeightLossSuccess_content">
    <p>Pick a program that focuses on strategies you can practice long-term, not just while you are "on the diet." Meal replacements, like shakes and portion -con trolled entrees, make it easier to cut out calories now and in the future. Also, a plan with an abundance of nutritious vegetables and fruits allows you to eat in volume without a lot of calories.</p>
  </div>
  <div class="tipsToWeightLossSuccess_subHeading">
    <h6>Get off to a strong start</h6>
  </div>
  <div class="tipsToWeightLossSuccess_content">
    <p>Contrary to the general belief that "slow and steady" weight loss is best articles have found that dieters who lost weight quickly lost more total weight and kept off more weight long-term. Researchers concluded that how well dieters do in the first 2-4 weeks predicts their Success LIP to five years later.</p>
  </div>
  <div class="tipsToWeightLossSuccess_subHeading">
    <h6>Make your home a safe haven</h6>
  </div>
  <div class="tipsToWeightLossSuccess_content">
    <p>Fill your home with healthy, low-fat, quick and easy food options. A bowl of fresh fruit on the counter, for example, can make it easy to have a healthy snack.</p>
  </div>
  <div class="tipsToWeightLossSuccess_subHeading">
    <h6>Make a plan</h6>
  </div>
  <div class="tipsToWeightLossSuccess_content">
    <p>If you don't plan out what you're going to do, the world has a plan for you. Map out the first day of your week to get a strong start so you can build on the rest of the week.</p>
  </div>
  <div class="tipsToWeightLossSuccess_subHeading">
    <h6>More is better</h6>
  </div>
  <div class="tipsToWeightLossSuccess_content">
    <p>This is true if your weight-loss plan includes healthy strategies like vegetables, fruits, and meal replacements. The more of these you eat, the more weight you'll lose. You don't have to be hungry to lose weight. On the contrary, if you stay full with low-fat, low-calorie foods, you're more likely to stay on your diet and lose more weight overall.</p>
  </div>
  <div class="tipsToWeightLossSuccess_subHeading">
    <h6>Target your "easy wins"</h6>
  </div>
  <div class="tipsToWeightLossSuccess_content">
    <p>Simple substitutions are often the easiest way to out calories. Drinking a diet soda instead of a regular soda every day will save you 15 or more pounds in a year. Eating a turkey sandwich with lettuce, tomato, and mustard instead of a roast beef sandwich with mayonnaise just twice a week will save you another 15 pounds.</p>
  </div>
  <div class="tipsToWeightLossSuccess_subHeading">
    <h6>Keep moving</h6>
  </div>
  <div class="tipsToWeightLossSuccess_content">
    <p>Daily physical activity, like walking, along with healthy eating is key to long-term weight-loss success and maintenance. Once again, more is better.</p>
  </div>
  <div class="tipsToWeightLossSuccess_subHeading">
    <h6>Track your progress</h6>
  </div>
  <div class="tipsToWeightLossSuccess_content">
    <p>Food and exercise records help you stay accountable to your diet plan, reinforce your success, and give you valuable feedback on how to continue to build your skills.</p>
  </div>
  <div class="tipsToWeightLossSuccess_subHeading">
    <h6>Drink your fluids</h6>
  </div>
  <div class="tipsToWeightLossSuccess_content">
    <p>It is important to stay hydrated. This is especially true when you are losing weight, because your body will naturally lose some water as the pounds come off. Make sure you drink at least eight 8 oz. glasses of noncaloric liquids per day.</p>
  </div>
  <div class="tipsToWeightLossSuccess_subHeading">
    <h6>Don't go it alone</h6>
  </div>
  <div class="tipsToWeightLossSuccess_content">
    <p>Research shows that people are often more successful when they lose weight with a friend or a group</p>
  </div>
</div>
