<div id="faq_header">
  <h3>HMR Frequently Asked Questions</h3>
</div>
<div id="faq_body">
  <div id="faqAccordion">
    <h3><span class="faq-num">1</span> <span class="faq-question">How many fruits and vegetables should I eat every day and why?</span> <span class="accordion_readMore">&or;</span><div class="dummy-close-x"><img src="media/wysiwyg/close-about-tabs.png" alt="Close" /></div></h3>
    <div>
      <p>The minimum number of servings per day is 5. Fruits and vegetables are low in fat and calories, but high in nutrition. The more fruits and vegetables you eat, the more nutrition you get and it helps to crowd out other high fat high calorie foods.</p>
    </div>
    <h3><span class="faq-num">2</span> <span class="faq-question">Why is it important to keep food records?</span> <span class="accordion_readMore">&or;</span><div class="dummy-close-x"><img src="media/wysiwyg/close-about-tabs.png" alt="Close" /></div></h3>
    <div>
      <p>Food records help you to keep track of what you are eating. It is very difficult to remember what you had, or what you did not have. They keep us accountable.</p>
    </div>
    <h3><span class="faq-num">3</span> <span class="faq-question">How much water should I drink?</span> <span class="accordion_readMore">&or;</span><div class="dummy-close-x"><img src="media/wysiwyg/close-about-tabs.png" alt="Close" /></div></h3>
    <div>
      <p>You should get a minimum of 64 ounces of fluid every day. The best bet is to make sure most of this comes from water. There are instances when you may need more. For example, when you are physically active you may need to replenish what you have lost during activity. It is important to check with your doctor regarding the correct amount for you if you have medical conditions that cause water retention.</p>
    </div>
    <h3><span class="faq-num">4</span> <span class="faq-question">What are the best fruits and vegetables to eat?</span> <span class="accordion_readMore">&or;</span><div class="dummy-close-x"><img src="media/wysiwyg/close-about-tabs.png" alt="Close" /></div></h3>
    <div>
      <p>Your best bet is to make sure that you get a good variety. Think in terms of colors. Fruits and vegetables are divided into 4 color groups: orange, red, green, and yellow/white. Set a goal to get in all 4 color groups.</p>
    </div>
    <h3><span class="faq-num">5</span> <span class="faq-question">How often and for how long do I need to exercise?</span> <span class="accordion_readMore">&or;</span><div class="dummy-close-x"><img src="media/wysiwyg/close-about-tabs.png" alt="Close" /></div></h3>
    <div>
      <p>We recommend getting physical activity every day. The idea is to create a lifestyle that includes regular activity. Some days you will have more time to dedicate to this and some days you may only have 10 minutes. With the busy lifestyle of today,it is not always easy to find that 30-60 minutes, so be sure to do 3-6 ten minute periods. Studies now show that this can be very beneficial. People who did short bouts throughout the day ended up doing more physical activity and stuck with their program longer than the people who only did longer bouts on most days.</p>
    </div>
    <h3><span class="faq-num">6</span> <span class="faq-question">What makes the HMR entrees shelf stable?</span> <span class="accordion_readMore">&or;</span><div class="dummy-close-x"><img src="media/wysiwyg/close-about-tabs.png" alt="Close" /></div></h3>
    <div>
      <p>The answer is retort packaging. Think in terms of the canning process - only the entrees are done in plastic trays.</p>
    </div>
    <h3><span class="faq-num">7</span> <span class="faq-question">What types of physical activity should I do?</span> <span class="accordion_readMore">&or;</span><div class="dummy-close-x"><img src="media/wysiwyg/close-about-tabs.png" alt="Close" /></div></h3>
    <div>
      <p>Anything that gets you moving! Variety is the key. It is easy to get burned out if you do not have a variety of activities. You also need variety in order to use all of the muscles. Think of physical activity as simply moving your body through space. It can be walking, weight training, exercise equipment, riding a bike, or even playing in the yard with the kids. Make it fun.</p>
    </div>
    <h3><span class="faq-num">8</span> <span class="faq-question">What if while I am on one of your programs, I feel hungry?</span> <span class="accordion_readMore">&or;</span><div class="dummy-close-x"><img src="media/wysiwyg/close-about-tabs.png" alt="Close" /></div></h3>
    <div>
      <p>Then you need to just simply have more of what is on your program. Because the items are all low in calorie and high in nutrition, you can just have more. Most people are used to limiting themselves when trying to lose weight, but that is not our method. We encourage you to have another shake, or eat another fruit or vegetable. If you are hungry, then that means that your body needs more fuel. You should never have to be hungry and feel that you cannot eat.</p>
    </div>
    <h3><span class="faq-num">9</span> <span class="faq-question">What do you mix HMR shakes with?</span> <span class="accordion_readMore">&or;</span><div class="dummy-close-x"><img src="media/wysiwyg/close-about-tabs.png" alt="Close" /></div></h3>
    <div>
      <p>Just water. The preferred method seems to be mixing it with water and ice in a blender to make a milkshake. You can also stir it with a spoon to make a pudding, or just shake it in a shaker cup. There is also a recipe book for the product that will give you many more ideas such as adding fruit or flavorings.</p>
    </div>
    <h3><span class="faq-num">10</span> <span class="faq-question">Which shake is for lactose intolerance? And do you mix the lactose intolerant shakes with water also?</span> <span class="accordion_readMore">&or;</span><div class="dummy-close-x"><img src="media/wysiwyg/close-about-tabs.png" alt="Close" /></div></h3>
    <div>
      <p>The HMR 70+ shake is lactose free, using an egg white for the majority of the base instead of milk. This shake DOES contain calcium caseinate and calcium phosphate.<br />
        You would still mix the shake with water as you do the others.</p>
    </div>
    <h3><span class="faq-num">11</span> <span class="faq-question">I was on the Liquid only diet before but now I have heard that with the medically supervised diet (liquids only) you are allowed a few veggies? And then after a while some fruits are added? Is this true?</span> <span class="accordion_readMore">&or;</span><div class="dummy-close-x"><img src="media/wysiwyg/close-about-tabs.png" alt="Close" /></div></h3>
    <div>
      <p>There are actually 2 different programs. There is the medically supervised program that is still meal replacements only. While you still must get in the 5 shakes per day (minimum), you can add in entrees or benefit bars, but fruits and vegetables are not allowed until you transition off of that program.<br />
        However there is another program called Healthy Solutions. With the Healthy Solutions program you take a minimum of 3 shakes, 2 entrees and a combination of 5 fruits and vegetable servings per day. These are all daily minimums. You can, at anytime, have more of the shakes, entrees, or fruits and veggies.<br />
        I hope that this clears things up a little for you.<br />
        Something else that is very new is the HMR at Home program. The HMR at Home program allows for you to do the Healthy Solution Program over the phone. We use a conference call line and have a virtual classroom. There are wonderful weight loss results with this program. If you are at all interested in getting back involved in a program, feel free to contact us to find out more.</p>
    </div>
    <h3><span class="faq-num">12</span> <span class="faq-question">What sweetners are used in HMR shakes? I cannot consume aspartame. Thanks.</span><span class="accordion_readMore">&or;</span><div class="dummy-close-x"><img src="media/wysiwyg/close-about-tabs.png" alt="Close" /></div></h3>
    <div>
      <p>The HMR 120 does have Aspartame, but the other shakes (HMR 500, HMR 800, and HMR 70+) have Saccharin.</p>
    </div>
    <h3><span class="faq-num">13</span> <span class="faq-question">A friend of mine is on the HMR Program at the hospital. The meetings are held in the evening. I am not available in the evenings. Can i buy your shakes and soup and do this myself? How many shakes or soups do you eat in a day?</span> <span class="accordion_readMore">&or;</span><div class="dummy-close-x"><img src="media/wysiwyg/close-about-tabs.png" alt="Close" /></div></h3>
    <div>
      <p>You are more than welcome to order and use the shakes, entrees and bars. The number of shakes you use would be up to you. For someone trying to lose weight we recommend using 3 shakes, 2 entrees and a combination of 5 fruits and vegetables per day. These are all minimums. So if you are still hungry then simply have more of any of those items. I wish you the best of luck in reaching your weight loss goal.</p>
    </div>
    <h3><span class="faq-num">14</span> <span class="faq-question">Is it possible to lose weight by replacing 2 meals a day with the shakes and them having a low calorie meal for the 3rd?</span> <span class="accordion_readMore">&or;</span><div class="dummy-close-x"><img src="media/wysiwyg/close-about-tabs.png" alt="Close" /></div></h3>
    <div>
      <p>Yes you can lose weight by replacing 2 meals with shakes and entrees plus one sensible meal per day. I always tell people to look to fruits and vegetables for inbetween meal snacks and be sure to use them as part of your sensible meal. Try to get in a combination of 5 fruits and vegetables minimum per day.</p>
    </div>
    <h3><span class="faq-num">15</span> <span class="faq-question">Is it ok to drink shakes 5 times a day and combine it with vegetables and fruits only? I would like to follow this plan for about 2 months.</span><span class="accordion_readMore">&or;</span><div class="dummy-close-x"><img src="media/wysiwyg/close-about-tabs.png" alt="Close" /></div></h3>
    <div>
      <p>I would suggest doing what we call 3+2+5.<br />
        That would be 3 shakes, 2 entrees and a combination of 5 fruits and vegetables per day. These would be minimums. So if you are still hungry then have more shakes, entrees, or fruits and vegetables.<br />
        You just want to be sure to keep your calories high enough if you are not medically supervised. By doing the 3+2+5, then you will be 1,000 - 1,200 calories per day.<br />
        If you would like to continue for more than the 2 months, it would not be a problem.</p>
    </div>
    <h3><span class="faq-num">16</span> <span class="faq-question">Hello, I have been following the HMR 800 plan (full fast) and just found out I was pregnant. Can I continue the shakes?</span> <span class="accordion_readMore">&or;</span><div class="dummy-close-x"><img src="media/wysiwyg/close-about-tabs.png" alt="Close" /></div></h3>
    <div>
      <p>No, actually you should discontinue your diet right away. Pregnancy is one of the contraindications to doing a Very Low calorie diet. Now is a time that you should not be cutting your calories back to so few.<br />
        You will still want to make sensible food choices, such as eating plenty of fruits and vegetables, lean cuts of meat, and making good food prep choices.<br />
        You should also consult with the program medical director and your own physician so they can give you a good meal plan.<br />
        Congratulations on your pregnancy!!</p>
    </div>
    <h3><span class="faq-num">17</span> <span class="faq-question">Would I lose weight faster on the HMR 500 instead?</span> <span class="accordion_readMore">&or;</span><div class="dummy-close-x"><img src="media/wysiwyg/close-about-tabs.png" alt="Close" /></div></h3>
    <div>
      <p>The 800 product has 160 calories per serving and the 500 has 100 calories per serving. So you would save about 240 calories per day by switching. In one weeks time that would be a calorie savings of 1,680 or 1/2 pound.<br />
        Keep in mind that for some people the 800 keeps them fuller longer because it does have more calories and is richer.<br />
        As long as you are eating entrees with it, and hopefully some fruits and veggies, you should be fine with either product.<br />
        I hope all is going well with your weight loss efforts. Best of luck!</p>
    </div>
    <h3><span class="faq-num">18</span> <span class="faq-question">I've noticed when I place my order that I am asked if I have "coupons".....<br />
      How do I receive the coupons?</span> <span class="accordion_readMore">&or;</span><div class="dummy-close-x"><img src="media/wysiwyg/close-about-tabs.png" alt="Close" /></div></h3>
    <div>
      <p>Great question. We periodically send out coupons to all of our customers. They will come to you via e-mail. They are different all of the time. Sometimes they are on a certain product and some times they are on your whole order. Since you have placed an order with us, you will get those any time they are sent out. So just watch your e-mail for them.</p>
    </div>
    <h3><span class="faq-num">19</span> <span class="faq-question">I am 40 years old and moderately active. I weigh 130 pounds and am 5'1". I would like to weigh 115-120. How much HMR should I use and what food types. Shakes, meals, veggies, fruit? What should my calorie intake be? What should my time frame be? I work for a GYN that is on HMR and she looks WONDERFUL!!!</span><span class="accordion_readMore">&or;</span><div class="dummy-close-x"><img src="media/wysiwyg/close-about-tabs.png" alt="Close" /></div></h3>
    <div>
      <p>We recommend following the Healthy Solution Program. That would be 3 shakes, 2 entrees and 5 fruit/veggies per day. These are minimums and you can always have more of any of these if you are hungry. I would also recommend 45-60 minutes per day of physical activity (most people just walk). By doing this you would lose 1 pound per week and you would be averaging 1000-1200 calories per day.<br />
        I wish you the best of luck.</p>
    </div>
    <h3><span class="faq-num">20</span> <span class="faq-question">What is considered a serving of fruit and vegtables?</span> <span class="accordion_readMore">&or;</span><div class="dummy-close-x"><img src="media/wysiwyg/close-about-tabs.png" alt="Close" /></div></h3>
    <div>
      <p>We measure a fruit serving as 6 ounces and a vegetable serving as one full cup.</p>
    </div>
    <h3><span class="faq-num">21</span> <span class="faq-question">How long would it be healthy to stay on shakes only (5) under medical supervision?</span> <span class="accordion_readMore">&or;</span><div class="dummy-close-x"><img src="media/wysiwyg/close-about-tabs.png" alt="Close" /></div></h3>
    <div>
      <p>The length of time you are on the medically supervised program will depend on how much weight you have to lose. We have had clients on this for over one year with no complications.<br />
        Your time on the program can also be affected by any health risks that you may have. The best way to get an individual answer would be to talk to an HMR clinics medical director and health educator.<br />
        If you are looking for a program in your area, call us and we can help. 1.800.521.9054</p>
    </div>
    <h3><span class="faq-num">22</span> <span class="faq-question">I did the program 12 years ago using HMR 500 with success. I would like to go back on the shakes again and wonder if I should use the HMR 500 or 800?</span> <span class="accordion_readMore">&or;</span><div class="dummy-close-x"><img src="media/wysiwyg/close-about-tabs.png" alt="Close" /></div></h3>
    <div>
      <p>If you had used the 500 product before, and you enjoyed the taste, I would recommend that you use that product again.<br />
        The difference between the 500 and the 800 is that the 800 product has more calories. There are 160 calories per serving, where the 500 has 100 calories. So you could save yourself some calories by using the 500.<br />
        The 800 also has a richer taste because there are more calories.<br />
        We do not recommend using the shakes as a sole source of nutrition if you are not on the HMR program at a clinic and are not medcially supervised by their Medical Director.<br />
        But the shakes are still a great meal/snack replacement. They taste great and can cut your calories for the day. If you want to use 3-5 per day and add fruits and vegetables, that should help you to your weight loss goal.</p>
    </div>
    <h3><span class="faq-num">23</span> <span class="faq-question">Is it safe to have less than 5 shakes a day on HMR 500? Are there any complications that could occur? Will it decrease the chance of you loosing weight?</span> <span class="accordion_readMore">&or;</span><div class="dummy-close-x"><img src="media/wysiwyg/close-about-tabs.png" alt="Close" /></div></h3>
    <div>
      <p>No, it is not safe to take less than 5 shakes a day.<br />
        The program is designed as a MINIMUM of 5 shakes per day. This is for nutritional reasons. By taking fewer calories it can actually slow down your weight loss, or you could lose lean muscle mass.<br />
        If your body is not getting enough calories it will go into a "starvation mode" and actually slow down in order to preserve calories.</p>
    </div>
    <h3><span class="faq-num">24</span> <span class="faq-question">I have done the fasting and lost 103 lbs. It has been almost three months and still doing well. What I would like to know is how to count the calories on fresh fruit.One book will say one thing and another will say something else...This is a great diet!</span><span class="accordion_readMore">&or;</span><div class="dummy-close-x"><img src="media/wysiwyg/close-about-tabs.png" alt="Close" /></div></h3>
    <div>
      <p>Congratulations on your success. I am happy to see that you are so concerned with counting calories and accounting for everything that you eat.<br />
        We do have a calorie sheet that we go by when counting calories and I would be more than happy to send one to you. You can call us at 1.800.521.9054 to give us your address.<br />
        The nice thing about fruits and vegetables are that they are low in calories to begin with, so if you miscalculate a little it will not be off by much. One way to calculate would be to look at a few of the books and take the average of them. You should also check to see what is considered a serving size, that may be why some of them are different.<br />
        The best of luck with your weight management.</p>
    </div>
    <h3><span class="faq-num">25</span> <span class="faq-question">Is corn on the cob considered a vegetable and if so, how much is a serving?</span> <span class="accordion_readMore">&or;</span><div class="dummy-close-x"><img src="media/wysiwyg/close-about-tabs.png" alt="Close" /></div></h3>
    <div>
      <p>Yes, corn on the cob is considered a vegetable. I would count a medium to large ear of corn as one serving.</p>
    </div>
    <h3><span class="faq-num">26</span> <span class="faq-question">What is the carbohydrate count in the HMR 500 Chocolate shake and the HMR 500 Vanilla shake?</span> <span class="accordion_readMore">&or;</span><div class="dummy-close-x"><img src="media/wysiwyg/close-about-tabs.png" alt="Close" /></div></h3>
    <div>
      <p>In the 500 shake the count are 16 per shake and for the vanilla there are 17 per shake.</p>
    </div>
    <h3><span class="faq-num">27</span> <span class="faq-question">I need to lose close to 100lbs. Which of the HMR shakes would allow for me to stop all food;clear my system;and re-introduce proper meals;a beginning for 'better nutrition/new eating habits?</span> <span class="accordion_readMore">&or;</span><div class="dummy-close-x"><img src="media/wysiwyg/close-about-tabs.png" alt="Close" /></div></h3>
    <div>
      <p>If you are going to go on a completely supplemented diet ( all shakes), you will want to be properly medically supervised. There are HMR programs all over the US and I would be happy to check on a location near you. You can call us at 1.800.521.9054 for a location near you.<br />
        There are also wonderful classes to help you to stay structured and on your program.<br />
        If you are looking to use some grocery store food ( try for mostly fruits and veggies) in addition to some shakes, then any of them would work. The HMR 500 has 100 calories per serving and the HMR 800 has 160 calories per serving. The HMR 70+ has 110 per serving and has no lactose.<br />
        I hope that this is helpful.</p>
    </div>
    <h3><span class="faq-num">28</span> <span class="faq-question">Do you mix the packets with water or milk?</span> <span class="accordion_readMore">&or;</span><div class="dummy-close-x"><img src="media/wysiwyg/close-about-tabs.png" alt="Close" /></div></h3>
    <div>
      <p>All of our shakes are mixed with water. To alter the flavor you can also add diet flavored soda instead.</p>
    </div>
    <h3><span class="faq-num">29</span> <span class="faq-question">I do not know much about the program but need to lose about 30 pounds. Can I have shakes, fruits, veggies and something like grilled chicken or crab soup for a meal once in a while and still lose weight?Anxious to lose but not sure of the rules. Classes are not in the area and the phone thing does not work for me since I am on the go constantly. What shakes should I start with?</span> <span class="accordion_readMore">&or;</span><div class="dummy-close-x"><img src="media/wysiwyg/close-about-tabs.png" alt="Close" /></div></h3>
    <div>
      <p>Your plan of shakes, fruits, and veggies, with a sensible meals sounds great. You can either make your own sensible meal, or you can purchase entrees. You can use either HMR entrees or grocery store entress that are 300 calories or less.<br />
        I am sorry to hear that the classes do not work for you, but if you stick with the plan that you have, then you should start to lose weight.<br />
        As far as which shakes to use, any of them will work. If you are lactose intolerant, then the 70+ shakes are the best ones. Otherwise the 500 or the 120 will be the best. The 500 comes in single serve packets and the 120 comes in a canister with a scoop. It is just a matter of whether you want the convenience of the packets.<br />
        I wish you much success.</p>
    </div>
    <h3><span class="faq-num">30</span> <span class="faq-question">I am on the Healthy Solutions plan. Can I substitute fresh fruit juice for any of the water in my shakes and still equal 1 shake and 1 fruit serving?</span> <span class="accordion_readMore">&or;</span><div class="dummy-close-x"><img src="media/wysiwyg/close-about-tabs.png" alt="Close" /></div></h3>
    <div>
      <p>In the Healthy Solution program fruit juices and vegetable juices do not count as a serving. You can put the whole fruit in the blender with your shake and count it as a serving. The fruit can be frozen, fresh or canned.</p>
    </div>
    <h3><span class="faq-num">31</span> <span class="faq-question">How often should I take the vitamins that come in the HMR 800 box?</span> <span class="accordion_readMore">&or;</span><div class="dummy-close-x"><img src="media/wysiwyg/close-about-tabs.png" alt="Close" /></div></h3>
    <div>
      <p>If you are on the medically supervised program, and doing only shakes, then you need to take two per day. Remember that you must be medically supervised by and HMR program if you are only using shakes. If you are using them as meal repleacements and using fruit and veggies in addition to the shakes, you only need one per day.</p>
    </div>
    <h3><span class="faq-num">32</span> <span class="faq-question">I was wondering if canned Fat Free Refried Beans count as a vegetable? They are fabulous with the enchiladas!</span><span class="accordion_readMore">&or;</span><div class="dummy-close-x"><img src="media/wysiwyg/close-about-tabs.png" alt="Close" /></div></h3>
    <div>
      <p>If you are involved in the Healthy Solution program at an HMR clinic, I would check with them to see what the clinics views are on that.<br />
        If you are tracking for youself and not in a clinic, then I would say yes.<br />
        You must make sure that there is nothing in the "refried" beans other than beans. So just check the label. As you are tracking your fruits and veggies remember that just half of a cup of beans is one serving.</p>
    </div>
    <h3><span class="faq-num">33</span> <span class="faq-question">Are there some fruits that are more "HMR" friendly than others?</span> <span class="accordion_readMore">&or;</span><div class="dummy-close-x"><img src="media/wysiwyg/close-about-tabs.png" alt="Close" /></div></h3>
    <div>
      <p>The great thing about the program is that you can have any fruit that you like.<br />
        Having said that, you do want to try to get a good variety. This is good for a couple of reason. One reason is that you will get a better variety of antioxidants. The other reason is to make sure you are not eating all of the highest calories fruits. This is only a factor if your daily calories are slowing down your weight loss or making it difficult to maintain weight. Remember though it is important to look at the "other" foods you are eating also.</p>
    </div>
    <h3><span class="faq-num">34</span> <span class="faq-question">I use the HMR800 4 + 1 meal/day plan. My schedule often won't let me stop to make a shake within my 3-4 hour intervals. Can I pre-mix one or more shakes and then portion them out during the day? Would they need refrigeration? If not advisable, is there an unsafe time interval to hold off drinking a shake after mixing?</span> <span class="accordion_readMore">&or;</span><div class="dummy-close-x"><img src="media/wysiwyg/close-about-tabs.png" alt="Close" /></div></h3>
    <div>
      <p>We have a lot of patients with your same situation.<br />
        It is fine to mix shakes ahead of time. They will need to be refrigerated until you drink them, or you can make them up ahead of time and freeze them.<br />
        You then can leave them out to thaw and drink them when you are ready. If it is too frozen to drink when you want it, you can put it in the microwave for about 20-30 seconds at a time.<br />
        I have many patients that will make and freeze several at a time.<br />
        I hope that this is helpful.</p>
    </div>
    <h3><span class="faq-num">35</span> <span class="faq-question">I want to lose 25 lbs and I would like to know what program I should be on for this and how long would it take to lose the weight I want to.</span><span class="accordion_readMore">&or;</span><div class="dummy-close-x"><img src="media/wysiwyg/close-about-tabs.png" alt="Close" /></div></h3>
    <div>
      <p>I would suggest the "Healthy Solutions" program. It is a program that uses meal replacements and fruits and veggies.<br />
        You can do this program at an HMR clinic or you can do it via telephone. We have a new option call "HMR at Home". This is a phone based conference line program where you have your class over the conference line.<br />
        The average person loses 1-3 pounds per week.<br />
        If you wold like to know more, just call us at 1.800.521.9054. We can see if there is a clinic in your area if you would like to do the program on site. If there is not a clinic near you, we can give you information on the "HMR at Home" program.</p>
    </div>
    <h3><span class="faq-num">36</span> <span class="faq-question">Is it OK to have wine on the HMR program?</span> <span class="accordion_readMore">&or;</span><div class="dummy-close-x"><img src="media/wysiwyg/close-about-tabs.png" alt="Close" /></div></h3>
    <div>
      <p>If you are in either of the weight loss phases (medically supervised or Healthy Solutions) there is no alcohol allowed.<br />
        As far as beverages go, the programs only allow for non-caloric beverages. Such as diet soda, WATER, crystal light, etc.</p>
    </div>
    <h3><span class="faq-num">37</span> <span class="faq-question">Other than the low calories and the maintenance program.... I dont see any other thing in the food that would cause weight loss than less calories is this correct?</span> <span class="accordion_readMore">&or;</span><div class="dummy-close-x"><img src="media/wysiwyg/close-about-tabs.png" alt="Close" /></div></h3>
    <div>
      <p>You are correct. There are not appetite suppressants, or stimulants.<br />
        The food is all low in calorie, so it helps you to eat enough to stay full without a lot of calories.<br />
        The classes are also very important. They help with structure and accountability. Most people know how to lose weight and can buy low calorie products, but are still unable to do it on their own. This is where the classes and coaching are very crucial to weight loss.</p>
    </div>
    <h3><span class="faq-num">38</span> <span class="faq-question">If I am using the HMR 500 shakes how many entrees is okay to eat?</span> <span class="accordion_readMore">&or;</span><div class="dummy-close-x"><img src="media/wysiwyg/close-about-tabs.png" alt="Close" /></div></h3>
    <div>
      <p>If you are on the VLCD (very-low calorie diet) at an HMR center I would check with their medical director.<br />
        If you are using some of the shakes on your own (you should never use just shakes if you are not medically supervised by an HMR physician) in addition to fruits, veggies and low calorie items, I would recommend 2 entrees per day. What we generally recommend are 3 shakes, 2 entrees, and 5 fruits and veggies.<br />
        This recommendation is for weight loss.<br />
        I hope that this is helpful for you.</p>
    </div>
    <h3><span class="faq-num">39</span> <span class="faq-question">I have seen amazing results with some friends. I would just like to lose ten pounds and wondering which program is best for me.</span><span class="accordion_readMore">&or;</span><div class="dummy-close-x"><img src="media/wysiwyg/close-about-tabs.png" alt="Close" /></div></h3>
    <div>
      <p>You really can use any of the products.<br />
        If you are not lactose intollerant, I think that the best one would be the HMR 500. This is because it has the fewest calories. There are only 100 calories per shake. I would also suggest using entrees to help with portion control. Then of course add in fruits and veggies.<br />
        If you are lactose intollerant, then I suggest using the HMR 70+. This product has not milk in it at all. It has about 110 calories per shake, so it is still very low in calories.</p>
    </div>
    <h3><span class="faq-num">40</span> <span class="faq-question">Are potatoes ok to have as a vegetable?</span> <span class="accordion_readMore">&or;</span><div class="dummy-close-x"><img src="media/wysiwyg/close-about-tabs.png" alt="Close" /></div></h3>
    <div>
      <p>Yes, potatos are considered a vegetable.</p>
    </div>
    <h3><span class="faq-num">41</span> <span class="faq-question">I have diabetes and my blood sugar is running about 220 - on insulin and medications. I am only about 20 lb. overweight. Will your program help my diabetes?</span> <span class="accordion_readMore">&or;</span><div class="dummy-close-x"><img src="media/wysiwyg/close-about-tabs.png" alt="Close" /></div></h3>
    <div>
      <p>We have many diabetics in our program and they find it very helpful in regulating their blood sugar and losing weight.<br />
        All of the diabetics are medically monitored by our medical director as everyone is different.<br />
        I would be more than happy to see if there is a clinic near you.<br />
        You can call us at 1.800.521.9054</p>
    </div>
  </div>
</div>
<script src="http://code.jquery.com/ui/1.9.2/jquery-ui.js"></script>
<script type="text/javascript">
//<![CDATA[
    jQuery(function() {
        jQuery("#faqAccordion").accordion({
			animated: 'easeInSine',
            collapsible: true,
			autoHeight: false,
        });
    });
	//]]>
</script>