<?php /* @var $this Queldorei_ShopperSettings_Block_Navigation */ ?>
<?php
/**
 * Top menu for store
 *
 * @see Queldorei_Navigation_Block_Navigation
 */
?>
<?php
/**
 * $this->renderCategoriesMenuHtml() supports optional arguments:
 * int Level number for list item class to start from
 * string Extra class of outermost list items
 * string If specified wraps children list in div with this class
 */
?>
<!-- 	!!!
		!!!
		UNCOMMENT THE PHP LINE BELOW
		AND ALL HTML COMMENTS TO RESTORE NAV
		!!!
		!!!
<?php //$_menu = $this->renderCategoriesMenuHtml(0, 'level-top', 'sub-wrapper' ) ?>
<?php if(isset($_menu) && $_menu): ?>
<nav class="queldorei">
    <ul id="queldoreiNav">
	    <?php if (Mage::getStoreConfig('shoppersettings/navigation/home')): ?>
         <li class="level0 level-top">
         	<a href="<?php echo $this->getBaseUrl(); ?>"><span><?php echo $this->__('Home'); ?></span></a>
         </li>
     <?php endif; ?>
        <?php
        echo $_menu;
        $custom_tab = Mage::getModel('cms/block')->load('shopper_navigation_block');
        if($custom_tab->getIsActive()) {
            echo '
            <li class="level0 level-top parent custom-block">
                <a href="#" class="level-top">
                    <span>'.$custom_tab->getTitle().'</span>
                </a>
                <div class="sub-wrapper" style="width:'.Mage::getStoreConfig('shoppersettings/navigation/custom_block_width').'px">'.$this->getLayout()->createBlock('cms/block')->setBlockId('shopper_navigation_block')->toHtml().'</div>
            </li>';
        }
        ?>
		<li class="hhm-nav-divider hide-divider"></li><li id="" class="level0 nav-2 level-top">
			<a href="/hmr-at-home-program" class="level-top">
				<span>HMR at Home</span>
			</a>
		</li>
		<li class="hhm-nav-divider"></li><li id="" class="level0 nav-3 level-top">
			<a href="/hmr-recipes" class="level-top">
				<span>Recipes</span>
			</a>
		</li>
		<li class="hhm-nav-divider"></li><li id="" class="level0 nav-4 level-top">
			<a href="/success" class="level-top">
				<span>Success</span>
			</a>
		</li>
		<li class="hhm-nav-divider"></li><li id="" class="level0 nav-5 level-top">
			<a href="/about" class="level-top">
				<span>About</span>
			</a>
		</li>
		<li class="hhm-nav-divider"></li><li id="" class="level0 nav-6 level-top last over">
			<a href="/contact" class="level-top">
				<span>Contact</span>
			</a>
		</li>
    </ul>
    <div class="nav-top-title"><?php echo $this->__('Navigation'); ?></div>
    <select id="navigation_select" name="navigation_select" onchange="if(this.value!='')window.location=this.value">
        <?php //$m = new Queldorei_ShopperSettings_Block_Navigation(); echo $m->renderCategoriesSelectOptions(); ?>
    </select>
</nav>
<?php endif ?>
<script type="text/javascript">
var separatorHtml = '<li class="hhm-nav-divider"></li>'
jQuery('ul#queldoreiNav').children('li').after(separatorHtml);
jQuery('ul#queldoreiNav li.hhm-nav-divider:first').addClass('hide-divider');
jQuery('ul#queldoreiNav li.hhm-nav-divider:last').addClass('hide-divider');
</script>
 -->

<nav class="queldorei">
  <h1 class="nav-header">HMR Diet Foods</h1>
  <ul id="queldoreiNav">
    <li class="level0 nav-1 level-top first last parent"> <a href="/shop" class="level-top"> <span>Shop Now</span> </a>
      <div class="sub-wrapper" style="left: -9999px;">
        <ul class="level0">
          <li class="over">
            <ol>
              <li id="hhm_active" class="level1 nav-1-1 first"> <a href="/fastselect"> <span>HMR Fast Select</span> </a> </li>
              <li id="hhm_active" class="level1 nav-1-2"> <a href="/hmr-at-home-program"> <span>HMR at Home</span> </a> </li>
              <li id="hhm_active" class="level1 nav-1-3"> <a href="/diet-accessories"> <span>Diet Accessories</span> </a> </li>
              <li id="hhm_active" class="level1 nav-1-4"> <a href="/hmr-entrees"> <span>HMR Entrees</span> </a> </li>
              <li id="hhm_active" class="level1 nav-1-5"> <a href="/hmr-shakes"> <span>HMR Shakes</span> </a> </li>
              <li id="hhm_active" class="level1 nav-1-6"> <a href="/hmr-multigrain-cereal"> <span>HMR Multigrain Cereal</span> </a> </li>
              <li id="hhm_active" class="level1 nav-1-7"> <a href="/hmr-benefit-bars"> <span>HMR BeneFit Bars</span> </a> </li>
              <li id="hhm_active" class="level1 nav-1-8"> <a href="/hmr-500-chicken-soup"> <span>HMR 500 Chicken Soup</span> </a> </li>
              <li id="hhm_active" class="level1 nav-1-9"> <a href="/hmr-healthy-shakes-kit"> <span>HMR Healthy Shakes Kit</span> </a> </li>
              <li id="hhm_active" class="level1 nav-1-10"> <a href="/kit-hs-variety"> <span>HMR Healthy Solutions Variety Pack</span> </a> </li>
              <li id="hhm_active" class="level1 nav-1-11"> <a href="/lorann-extract-flavorings"> <span>LorAnn Extract Flavorings</span> </a> </li>
              <li id="hhm_active" class="level1 nav-1-12 last"> <a href="/specials"> <span>Specials</span> </a> </li>
            </ol>
          </li>
        </ul>
      </div>
    </li>
    <li class="hhm-nav-divider hide-divider"></li>
    <li id="" class="level0 nav-2 level-top"> <a href="/hmr-at-home-program" class="level-top"> <span>HMR at Home</span> </a> </li>
    <li class="hhm-nav-divider"></li>
    <li id="" class="level0 nav-3 level-top"> <a href="/hmr-recipes" class="level-top"> <span>Recipes</span> </a> </li>
    <li class="hhm-nav-divider"></li>
    <li id="" class="level0 nav-4 level-top"> <a href="/success" class="level-top"> <span>Success</span> </a> </li>
    <li class="hhm-nav-divider"></li>
    <li id="" class="level0 nav-5 level-top"> <a href="/about" class="level-top"> <span>About</span> </a> </li>
    <li class="hhm-nav-divider"></li>
    <li id="" class="level0 nav-6 level-top last over"> <a href="/contact" class="level-top"> <span>Contact</span> </a> </li>
    <li class="hhm-nav-divider hide-divider"></li>
  </ul>
  <div class="nav-top-title">Navigation</div>
  <select id="navigation_select" name="navigation_select" onchange="if(this.value!='')window.location=this.value">
    <option value="">- Please select category -</option>
    <option value="/shop" selected="selected">Shop Now</option>
    <option value="/fastselect">&nbsp;&nbsp;&nbsp;&nbsp;HMR Fast Select</option>
    <option value="/shop/hmr-at-home" selected="selected">&nbsp;&nbsp;&nbsp;&nbsp;HMR at Home</option>
    <option value="/shop/diet-accessories">&nbsp;&nbsp;&nbsp;&nbsp;Diet Accessories</option>
    <option value="/shop/hmr-entrees">&nbsp;&nbsp;&nbsp;&nbsp;HMR Entrees</option>
    <option value="/shop/hmr-shakes">&nbsp;&nbsp;&nbsp;&nbsp;HMR Shakes</option>
    <option value="/shop/hmr-multigrain-cereal">&nbsp;&nbsp;&nbsp;&nbsp;HMR Multigrain Cereal</option>
    <option value="/shop/hmr-benefit-bars">&nbsp;&nbsp;&nbsp;&nbsp;HMR BeneFit Bars</option>
    <option value="/shop/hmr-500-chicken-soup">&nbsp;&nbsp;&nbsp;&nbsp;HMR 500 Chicken Soup</option>
    <option value="/shop/hmr-healthy-shakes-kit">&nbsp;&nbsp;&nbsp;&nbsp;HMR Healthy Shakes Kit</option>
    <option value="/shop/hmr-healthy-solutions-variety-pack">&nbsp;&nbsp;&nbsp;&nbsp;HMR Healthy Solutions Variety Pack</option>
    <option value="/shop/lorann-extract-flavorings">&nbsp;&nbsp;&nbsp;&nbsp;LorAnn Extract Flavorings</option>
  </select>
</nav>
