<div class="contact-wrapper">
  <div class="contact-top">
    <div class="contact-column">
      <h4>Contact Information</h4>
      <p><strong>Hackley Health Management</strong><br />
        1212 E. Sherman Blvd<br />
        Muskegon, MI 49444<br />
        <strong>Toll Free</strong>: <span style="color:#4576A2;font-weight:bold;">800-521-9054</span><br />
        <strong>Local</strong>: 231-672-4325<br />
        <strong>Fax</strong>: 231-672-3822</p>
    </div>
    <div class="contact-column">
      <h4>Hours of Operation</h4>
      <p><strong>Monday - Thursday</strong><br />
        9:00 a.m. - 5:30 p.m.<br />
        <strong>Friday</strong><br />
        9:00 a.m. - 3:00 p.m.<br />
        <strong>Weekends</strong><br />
        CLOSED</p>
    </div>
  </div>
  <div class="contact-bottom">
    <div class="hhm-contact-map">
      <iframe src="https://maps.google.com/maps?q=1212+E.+Sherman+Blvd+Muskegon,+MI+49444&amp;gl=us&amp;t=h&amp;ie=UTF8&amp;hq=&amp;hnear=1212+E+Sherman+Blvd,+Muskegon,+Michigan+49444&amp;z=16&amp;ll=43.205421,-86.214053&amp;output=embed&amp;iwloc=near" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" width="466" height="466"></iframe>
      <small><a style="color: #0000ff; text-align: left;" href="https://maps.google.com/maps?q=1212+E.+Sherman+Blvd+Muskegon,+MI+49444&amp;gl=us&amp;t=h&amp;ie=UTF8&amp;hq=&amp;hnear=1212+E+Sherman+Blvd,+Muskegon,+Michigan+49444&amp;z=14&amp;ll=43.205421,-86.214053&amp;source=embed" target="_blank">View Larger Map</a></small></div>
    <div class="hhm-contact-form"><?php include 'app/design/frontend/default/shopper/template/contacts/form.phtml'; ?></div>
  </div>
</div>
