  <div class="cyber-content-wrapper-full">
    <div class="category-description std">
      <h1>Cyber WEEK - Sale Extended Through December 6<sup>th</sup>, 2013!</span></h1>
    </div>
    <div class="cyber-box-wrapper">
      <div class="cyber-wrapper">
        <div class="cyber-content">
          <p>This past Monday was the biggest online shopping day of the year! Hackley Health Management participates in Cyber Monday to pass down exceptional savings to you, our customer. We have extended this sale through the end of the week, but the only way to take advantage of these phenomenal savings is to receive our discounts and special offers in your email inbox, so be sure to <strong>register today</strong> for our exclusive mailing list to receive these great offers!</p>
        </div>
        <div class="cyber-cta-wrapper"><br />
          <img class="cyber-mobile" src="/media/wysiwyg/arrow-signup-cta-mobile.png" />
          <img class="cyber-not-mobile" src="/media/wysiwyg/arrow-signup-cta.png" />
          <div class="cyber-cta">Register<br />
            Today!</div>
        </div>
      </div>
      <div class="xmas-girl"><img src="/media/wysiwyg/santa-healthy-diet-girl.png" /></div>
    </div>
  </div>